-- Space-Time Smackdown (A2): 155 main-set cards and 52 secret cards.
-- Source checked 2026-06-24: https://pocket.limitlesstcg.com/cards/A2
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A2-001', 'A2', 1, 'Oddish', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_001_EN_SM.webp'),
  ('A2-002', 'A2', 2, 'Gloom', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_002_EN_SM.webp'),
  ('A2-003', 'A2', 3, 'Bellossom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_003_EN_SM.webp'),
  ('A2-004', 'A2', 4, 'Tangela', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_004_EN_SM.webp'),
  ('A2-005', 'A2', 5, 'Tangrowth', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_005_EN_SM.webp'),
  ('A2-006', 'A2', 6, 'Yanma', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_006_EN_SM.webp'),
  ('A2-007', 'A2', 7, 'Yanmega ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_007_EN_SM.webp'),
  ('A2-008', 'A2', 8, 'Roselia', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_008_EN_SM.webp'),
  ('A2-009', 'A2', 9, 'Roserade', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_009_EN_SM.webp'),
  ('A2-010', 'A2', 10, 'Turtwig', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_010_EN_SM.webp'),
  ('A2-011', 'A2', 11, 'Grotle', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_011_EN_SM.webp'),
  ('A2-012', 'A2', 12, 'Torterra', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_012_EN_SM.webp'),
  ('A2-013', 'A2', 13, 'Kricketot', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_013_EN_SM.webp'),
  ('A2-014', 'A2', 14, 'Kricketune', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_014_EN_SM.webp'),
  ('A2-015', 'A2', 15, 'Burmy', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_015_EN_SM.webp'),
  ('A2-016', 'A2', 16, 'Wormadam', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_016_EN_SM.webp'),
  ('A2-017', 'A2', 17, 'Combee', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_017_EN_SM.webp'),
  ('A2-018', 'A2', 18, 'Vespiquen', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_018_EN_SM.webp'),
  ('A2-019', 'A2', 19, 'Carnivine', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_019_EN_SM.webp'),
  ('A2-020', 'A2', 20, 'Leafeon', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_020_EN_SM.webp'),
  ('A2-021', 'A2', 21, 'Mow Rotom', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_021_EN_SM.webp'),
  ('A2-022', 'A2', 22, 'Shaymin', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_022_EN_SM.webp'),
  ('A2-023', 'A2', 23, 'Magmar', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_023_EN_SM.webp'),
  ('A2-024', 'A2', 24, 'Magmortar', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_024_EN_SM.webp'),
  ('A2-025', 'A2', 25, 'Slugma', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_025_EN_SM.webp'),
  ('A2-026', 'A2', 26, 'Magcargo', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_026_EN_SM.webp'),
  ('A2-027', 'A2', 27, 'Chimchar', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_027_EN_SM.webp'),
  ('A2-028', 'A2', 28, 'Monferno', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_028_EN_SM.webp'),
  ('A2-029', 'A2', 29, 'Infernape ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_029_EN_SM.webp'),
  ('A2-030', 'A2', 30, 'Heat Rotom', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_030_EN_SM.webp'),
  ('A2-031', 'A2', 31, 'Swinub', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_031_EN_SM.webp'),
  ('A2-032', 'A2', 32, 'Piloswine', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_032_EN_SM.webp'),
  ('A2-033', 'A2', 33, 'Mamoswine', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_033_EN_SM.webp'),
  ('A2-034', 'A2', 34, 'Regice', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_034_EN_SM.webp'),
  ('A2-035', 'A2', 35, 'Piplup', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_035_EN_SM.webp'),
  ('A2-036', 'A2', 36, 'Prinplup', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_036_EN_SM.webp'),
  ('A2-037', 'A2', 37, 'Empoleon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_037_EN_SM.webp'),
  ('A2-038', 'A2', 38, 'Buizel', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_038_EN_SM.webp'),
  ('A2-039', 'A2', 39, 'Floatzel', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_039_EN_SM.webp'),
  ('A2-040', 'A2', 40, 'Shellos', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_040_EN_SM.webp'),
  ('A2-041', 'A2', 41, 'Gastrodon', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_041_EN_SM.webp'),
  ('A2-042', 'A2', 42, 'Finneon', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_042_EN_SM.webp'),
  ('A2-043', 'A2', 43, 'Lumineon', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_043_EN_SM.webp'),
  ('A2-044', 'A2', 44, 'Snover', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_044_EN_SM.webp'),
  ('A2-045', 'A2', 45, 'Abomasnow', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_045_EN_SM.webp'),
  ('A2-046', 'A2', 46, 'Glaceon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_046_EN_SM.webp'),
  ('A2-047', 'A2', 47, 'Wash Rotom', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_047_EN_SM.webp'),
  ('A2-048', 'A2', 48, 'Frost Rotom', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_048_EN_SM.webp'),
  ('A2-049', 'A2', 49, 'Palkia ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_049_EN_SM.webp'),
  ('A2-050', 'A2', 50, 'Manaphy', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_050_EN_SM.webp'),
  ('A2-051', 'A2', 51, 'Magnemite', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_051_EN_SM.webp'),
  ('A2-052', 'A2', 52, 'Magneton', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_052_EN_SM.webp'),
  ('A2-053', 'A2', 53, 'Magnezone', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_053_EN_SM.webp'),
  ('A2-054', 'A2', 54, 'Voltorb', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_054_EN_SM.webp'),
  ('A2-055', 'A2', 55, 'Electrode', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_055_EN_SM.webp'),
  ('A2-056', 'A2', 56, 'Electabuzz', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_056_EN_SM.webp'),
  ('A2-057', 'A2', 57, 'Electivire', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_057_EN_SM.webp'),
  ('A2-058', 'A2', 58, 'Shinx', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_058_EN_SM.webp'),
  ('A2-059', 'A2', 59, 'Luxio', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_059_EN_SM.webp'),
  ('A2-060', 'A2', 60, 'Luxray', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_060_EN_SM.webp'),
  ('A2-061', 'A2', 61, 'Pachirisu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_061_EN_SM.webp'),
  ('A2-062', 'A2', 62, 'Rotom', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_062_EN_SM.webp'),
  ('A2-063', 'A2', 63, 'Togepi', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_063_EN_SM.webp'),
  ('A2-064', 'A2', 64, 'Togetic', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_064_EN_SM.webp'),
  ('A2-065', 'A2', 65, 'Togekiss', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_065_EN_SM.webp'),
  ('A2-066', 'A2', 66, 'Misdreavus', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_066_EN_SM.webp'),
  ('A2-067', 'A2', 67, 'Mismagius ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_067_EN_SM.webp'),
  ('A2-068', 'A2', 68, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_068_EN_SM.webp'),
  ('A2-069', 'A2', 69, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_069_EN_SM.webp'),
  ('A2-070', 'A2', 70, 'Duskull', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_070_EN_SM.webp'),
  ('A2-071', 'A2', 71, 'Dusclops', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_071_EN_SM.webp'),
  ('A2-072', 'A2', 72, 'Dusknoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_072_EN_SM.webp'),
  ('A2-073', 'A2', 73, 'Drifloon', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_073_EN_SM.webp'),
  ('A2-074', 'A2', 74, 'Drifblim', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_074_EN_SM.webp'),
  ('A2-075', 'A2', 75, 'Uxie', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_075_EN_SM.webp'),
  ('A2-076', 'A2', 76, 'Mesprit', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_076_EN_SM.webp'),
  ('A2-077', 'A2', 77, 'Azelf', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_077_EN_SM.webp'),
  ('A2-078', 'A2', 78, 'Giratina', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_078_EN_SM.webp'),
  ('A2-079', 'A2', 79, 'Cresselia', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_079_EN_SM.webp'),
  ('A2-080', 'A2', 80, 'Rhyhorn', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_080_EN_SM.webp'),
  ('A2-081', 'A2', 81, 'Rhydon', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_081_EN_SM.webp'),
  ('A2-082', 'A2', 82, 'Rhyperior', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_082_EN_SM.webp'),
  ('A2-083', 'A2', 83, 'Gligar', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_083_EN_SM.webp'),
  ('A2-084', 'A2', 84, 'Gliscor', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_084_EN_SM.webp'),
  ('A2-085', 'A2', 85, 'Hitmontop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_085_EN_SM.webp'),
  ('A2-086', 'A2', 86, 'Nosepass', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_086_EN_SM.webp'),
  ('A2-087', 'A2', 87, 'Regirock', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_087_EN_SM.webp'),
  ('A2-088', 'A2', 88, 'Cranidos', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_088_EN_SM.webp'),
  ('A2-089', 'A2', 89, 'Rampardos', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_089_EN_SM.webp'),
  ('A2-090', 'A2', 90, 'Wormadam', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_090_EN_SM.webp'),
  ('A2-091', 'A2', 91, 'Riolu', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_091_EN_SM.webp'),
  ('A2-092', 'A2', 92, 'Lucario', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_092_EN_SM.webp'),
  ('A2-093', 'A2', 93, 'Hippopotas', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_093_EN_SM.webp'),
  ('A2-094', 'A2', 94, 'Hippowdon', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_094_EN_SM.webp'),
  ('A2-095', 'A2', 95, 'Gallade ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_095_EN_SM.webp'),
  ('A2-096', 'A2', 96, 'Murkrow', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_096_EN_SM.webp'),
  ('A2-097', 'A2', 97, 'Honchkrow', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_097_EN_SM.webp'),
  ('A2-098', 'A2', 98, 'Sneasel', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_098_EN_SM.webp'),
  ('A2-099', 'A2', 99, 'Weavile ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_099_EN_SM.webp'),
  ('A2-100', 'A2', 100, 'Poochyena', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_100_EN_SM.webp'),
  ('A2-101', 'A2', 101, 'Mightyena', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_101_EN_SM.webp'),
  ('A2-102', 'A2', 102, 'Stunky', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_102_EN_SM.webp'),
  ('A2-103', 'A2', 103, 'Skuntank', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_103_EN_SM.webp'),
  ('A2-104', 'A2', 104, 'Spiritomb', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_104_EN_SM.webp'),
  ('A2-105', 'A2', 105, 'Skorupi', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_105_EN_SM.webp'),
  ('A2-106', 'A2', 106, 'Drapion', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_106_EN_SM.webp'),
  ('A2-107', 'A2', 107, 'Croagunk', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_107_EN_SM.webp'),
  ('A2-108', 'A2', 108, 'Toxicroak', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_108_EN_SM.webp'),
  ('A2-109', 'A2', 109, 'Darkrai', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_109_EN_SM.webp'),
  ('A2-110', 'A2', 110, 'Darkrai ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_110_EN_SM.webp'),
  ('A2-111', 'A2', 111, 'Skarmory', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_111_EN_SM.webp'),
  ('A2-112', 'A2', 112, 'Registeel', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_112_EN_SM.webp'),
  ('A2-113', 'A2', 113, 'Shieldon', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_113_EN_SM.webp'),
  ('A2-114', 'A2', 114, 'Bastiodon', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_114_EN_SM.webp'),
  ('A2-115', 'A2', 115, 'Wormadam', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_115_EN_SM.webp'),
  ('A2-116', 'A2', 116, 'Bronzor', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_116_EN_SM.webp'),
  ('A2-117', 'A2', 117, 'Bronzong', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_117_EN_SM.webp'),
  ('A2-118', 'A2', 118, 'Probopass', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_118_EN_SM.webp'),
  ('A2-119', 'A2', 119, 'Dialga ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_119_EN_SM.webp'),
  ('A2-120', 'A2', 120, 'Heatran', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_120_EN_SM.webp'),
  ('A2-121', 'A2', 121, 'Gible', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_121_EN_SM.webp'),
  ('A2-122', 'A2', 122, 'Gabite', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_122_EN_SM.webp'),
  ('A2-123', 'A2', 123, 'Garchomp', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_123_EN_SM.webp'),
  ('A2-124', 'A2', 124, 'Lickitung', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_124_EN_SM.webp'),
  ('A2-125', 'A2', 125, 'Lickilicky ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_125_EN_SM.webp'),
  ('A2-126', 'A2', 126, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_126_EN_SM.webp'),
  ('A2-127', 'A2', 127, 'Porygon', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_127_EN_SM.webp'),
  ('A2-128', 'A2', 128, 'Porygon2', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_128_EN_SM.webp'),
  ('A2-129', 'A2', 129, 'Porygon-Z', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_129_EN_SM.webp'),
  ('A2-130', 'A2', 130, 'Aipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_130_EN_SM.webp'),
  ('A2-131', 'A2', 131, 'Ambipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_131_EN_SM.webp'),
  ('A2-132', 'A2', 132, 'Starly', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_132_EN_SM.webp'),
  ('A2-133', 'A2', 133, 'Staravia', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_133_EN_SM.webp'),
  ('A2-134', 'A2', 134, 'Staraptor', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_134_EN_SM.webp'),
  ('A2-135', 'A2', 135, 'Bidoof', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_135_EN_SM.webp'),
  ('A2-136', 'A2', 136, 'Bibarel', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_136_EN_SM.webp'),
  ('A2-137', 'A2', 137, 'Buneary', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_137_EN_SM.webp'),
  ('A2-138', 'A2', 138, 'Lopunny', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_138_EN_SM.webp'),
  ('A2-139', 'A2', 139, 'Glameow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_139_EN_SM.webp'),
  ('A2-140', 'A2', 140, 'Purugly', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_140_EN_SM.webp'),
  ('A2-141', 'A2', 141, 'Chatot', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_141_EN_SM.webp'),
  ('A2-142', 'A2', 142, 'Fan Rotom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_142_EN_SM.webp'),
  ('A2-143', 'A2', 143, 'Regigigas', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_143_EN_SM.webp'),
  ('A2-144', 'A2', 144, 'Skull Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_144_EN_SM.webp'),
  ('A2-145', 'A2', 145, 'Armor Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_145_EN_SM.webp'),
  ('A2-146', 'A2', 146, 'Pokémon Communication', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_146_EN_SM.webp'),
  ('A2-147', 'A2', 147, 'Giant Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_147_EN_SM.webp'),
  ('A2-148', 'A2', 148, 'Rocky Helmet', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_148_EN_SM.webp'),
  ('A2-149', 'A2', 149, 'Lum Berry', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_149_EN_SM.webp'),
  ('A2-150', 'A2', 150, 'Cyrus', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_150_EN_SM.webp'),
  ('A2-151', 'A2', 151, 'Team Galactic Grunt', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_151_EN_SM.webp'),
  ('A2-152', 'A2', 152, 'Cynthia', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_152_EN_SM.webp'),
  ('A2-153', 'A2', 153, 'Volkner', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_153_EN_SM.webp'),
  ('A2-154', 'A2', 154, 'Dawn', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_154_EN_SM.webp'),
  ('A2-155', 'A2', 155, 'Mars', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_155_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A2-156', 'A2', 156, 'Tangrowth', 'pokemon', 'grass', null, 'star_1', 'A2-005', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_156_EN_SM.webp'),
  ('A2-157', 'A2', 157, 'Combee', 'pokemon', 'grass', null, 'star_1', 'A2-017', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_157_EN_SM.webp'),
  ('A2-158', 'A2', 158, 'Carnivine', 'pokemon', 'grass', null, 'star_1', 'A2-019', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_158_EN_SM.webp'),
  ('A2-159', 'A2', 159, 'Shaymin', 'pokemon', 'grass', null, 'star_1', 'A2-022', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_159_EN_SM.webp'),
  ('A2-160', 'A2', 160, 'Mamoswine', 'pokemon', 'water', null, 'star_1', 'A2-033', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_160_EN_SM.webp'),
  ('A2-161', 'A2', 161, 'Gastrodon', 'pokemon', 'water', null, 'star_1', 'A2-041', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_161_EN_SM.webp'),
  ('A2-162', 'A2', 162, 'Manaphy', 'pokemon', 'water', null, 'star_1', 'A2-050', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_162_EN_SM.webp'),
  ('A2-163', 'A2', 163, 'Shinx', 'pokemon', 'lightning', null, 'star_1', 'A2-058', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_163_EN_SM.webp'),
  ('A2-164', 'A2', 164, 'Rotom', 'pokemon', 'lightning', null, 'star_1', 'A2-062', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_164_EN_SM.webp'),
  ('A2-165', 'A2', 165, 'Drifloon', 'pokemon', 'psychic', null, 'star_1', 'A2-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_165_EN_SM.webp'),
  ('A2-166', 'A2', 166, 'Mesprit', 'pokemon', 'psychic', null, 'star_1', 'A2-076', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_166_EN_SM.webp'),
  ('A2-167', 'A2', 167, 'Giratina', 'pokemon', 'psychic', null, 'star_1', 'A2-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_167_EN_SM.webp'),
  ('A2-168', 'A2', 168, 'Cresselia', 'pokemon', 'psychic', null, 'star_1', 'A2-079', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_168_EN_SM.webp'),
  ('A2-169', 'A2', 169, 'Rhyperior', 'pokemon', 'fighting', null, 'star_1', 'A2-082', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_169_EN_SM.webp'),
  ('A2-170', 'A2', 170, 'Lucario', 'pokemon', 'fighting', null, 'star_1', 'A2-092', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_170_EN_SM.webp'),
  ('A2-171', 'A2', 171, 'Hippopotas', 'pokemon', 'fighting', null, 'star_1', 'A2-093', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_171_EN_SM.webp'),
  ('A2-172', 'A2', 172, 'Spiritomb', 'pokemon', 'darkness', null, 'star_1', 'A2-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_172_EN_SM.webp'),
  ('A2-173', 'A2', 173, 'Croagunk', 'pokemon', 'darkness', null, 'star_1', 'A2-107', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_173_EN_SM.webp'),
  ('A2-174', 'A2', 174, 'Heatran', 'pokemon', 'metal', null, 'star_1', 'A2-120', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_174_EN_SM.webp'),
  ('A2-175', 'A2', 175, 'Garchomp', 'pokemon', 'dragon', null, 'star_1', 'A2-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_175_EN_SM.webp'),
  ('A2-176', 'A2', 176, 'Staraptor', 'pokemon', 'colorless', null, 'star_1', 'A2-134', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_176_EN_SM.webp'),
  ('A2-177', 'A2', 177, 'Bidoof', 'pokemon', 'colorless', null, 'star_1', 'A2-135', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_177_EN_SM.webp'),
  ('A2-178', 'A2', 178, 'Glameow', 'pokemon', 'colorless', null, 'star_1', 'A2-139', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_178_EN_SM.webp'),
  ('A2-179', 'A2', 179, 'Regigigas', 'pokemon', 'colorless', null, 'star_1', 'A2-143', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_179_EN_SM.webp'),
  ('A2-180', 'A2', 180, 'Yanmega ex', 'pokemon', 'grass', null, 'star_2', 'A2-007', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_180_EN_SM.webp'),
  ('A2-181', 'A2', 181, 'Infernape ex', 'pokemon', 'fire', null, 'star_2', 'A2-029', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_181_EN_SM.webp'),
  ('A2-182', 'A2', 182, 'Palkia ex', 'pokemon', 'water', null, 'star_2', 'A2-049', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_182_EN_SM.webp'),
  ('A2-183', 'A2', 183, 'Pachirisu ex', 'pokemon', 'lightning', null, 'star_2', 'A2-061', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_183_EN_SM.webp'),
  ('A2-184', 'A2', 184, 'Mismagius ex', 'pokemon', 'psychic', null, 'star_2', 'A2-067', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_184_EN_SM.webp'),
  ('A2-185', 'A2', 185, 'Gallade ex', 'pokemon', 'fighting', null, 'star_2', 'A2-095', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_185_EN_SM.webp'),
  ('A2-186', 'A2', 186, 'Weavile ex', 'pokemon', 'darkness', null, 'star_2', 'A2-099', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_186_EN_SM.webp'),
  ('A2-187', 'A2', 187, 'Darkrai ex', 'pokemon', 'darkness', null, 'star_2', 'A2-110', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_187_EN_SM.webp'),
  ('A2-188', 'A2', 188, 'Dialga ex', 'pokemon', 'metal', null, 'star_2', 'A2-119', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_188_EN_SM.webp'),
  ('A2-189', 'A2', 189, 'Lickilicky ex', 'pokemon', 'colorless', null, 'star_2', 'A2-125', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_189_EN_SM.webp'),
  ('A2-190', 'A2', 190, 'Cyrus', 'trainer', null, 'supporter', 'star_2', 'A2-150', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_190_EN_SM.webp'),
  ('A2-191', 'A2', 191, 'Team Galactic Grunt', 'trainer', null, 'supporter', 'star_2', 'A2-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_191_EN_SM.webp'),
  ('A2-192', 'A2', 192, 'Cynthia', 'trainer', null, 'supporter', 'star_2', 'A2-152', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_192_EN_SM.webp'),
  ('A2-193', 'A2', 193, 'Volkner', 'trainer', null, 'supporter', 'star_2', 'A2-153', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_193_EN_SM.webp'),
  ('A2-194', 'A2', 194, 'Dawn', 'trainer', null, 'supporter', 'star_2', 'A2-154', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_194_EN_SM.webp'),
  ('A2-195', 'A2', 195, 'Mars', 'trainer', null, 'supporter', 'star_2', 'A2-155', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_195_EN_SM.webp'),
  ('A2-196', 'A2', 196, 'Yanmega ex', 'pokemon', 'grass', null, 'star_2', 'A2-007', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_196_EN_SM.webp'),
  ('A2-197', 'A2', 197, 'Infernape ex', 'pokemon', 'fire', null, 'star_2', 'A2-029', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_197_EN_SM.webp'),
  ('A2-198', 'A2', 198, 'Pachirisu ex', 'pokemon', 'lightning', null, 'star_2', 'A2-061', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_198_EN_SM.webp'),
  ('A2-199', 'A2', 199, 'Mismagius ex', 'pokemon', 'psychic', null, 'star_2', 'A2-067', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_199_EN_SM.webp'),
  ('A2-200', 'A2', 200, 'Gallade ex', 'pokemon', 'fighting', null, 'star_2', 'A2-095', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_200_EN_SM.webp'),
  ('A2-201', 'A2', 201, 'Weavile ex', 'pokemon', 'darkness', null, 'star_2', 'A2-099', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_201_EN_SM.webp'),
  ('A2-202', 'A2', 202, 'Darkrai ex', 'pokemon', 'darkness', null, 'star_2', 'A2-110', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_202_EN_SM.webp'),
  ('A2-203', 'A2', 203, 'Lickilicky ex', 'pokemon', 'colorless', null, 'star_2', 'A2-125', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_203_EN_SM.webp'),
  ('A2-204', 'A2', 204, 'Palkia ex', 'pokemon', 'water', null, 'star_3', 'A2-049', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_204_EN_SM.webp'),
  ('A2-205', 'A2', 205, 'Dialga ex', 'pokemon', 'metal', null, 'star_3', 'A2-119', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_205_EN_SM.webp'),
  ('A2-206', 'A2', 206, 'Palkia ex', 'pokemon', 'water', null, 'crown', 'A2-049', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_206_EN_SM.webp'),
  ('A2-207', 'A2', 207, 'Dialga ex', 'pokemon', 'metal', null, 'crown', 'A2-119', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_207_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 207 cards, numbered 1 through 207.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'A2';
