-- Celestial Guardians (A3): 155 main-set cards and 84 secret cards.
-- Source checked 2026-06-24: https://pocket.limitlesstcg.com/cards/A3?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A3-001', 'A3', 1, 'Exeggcute', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_001_EN_SM.webp'),
  ('A3-002', 'A3', 2, 'Alolan Exeggutor', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_002_EN_SM.webp'),
  ('A3-003', 'A3', 3, 'Surskit', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_003_EN_SM.webp'),
  ('A3-004', 'A3', 4, 'Masquerain', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_004_EN_SM.webp'),
  ('A3-005', 'A3', 5, 'Maractus', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_005_EN_SM.webp'),
  ('A3-006', 'A3', 6, 'Karrablast', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_006_EN_SM.webp'),
  ('A3-007', 'A3', 7, 'Phantump', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_007_EN_SM.webp'),
  ('A3-008', 'A3', 8, 'Trevenant', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_008_EN_SM.webp'),
  ('A3-009', 'A3', 9, 'Rowlet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_009_EN_SM.webp'),
  ('A3-010', 'A3', 10, 'Rowlet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_010_EN_SM.webp'),
  ('A3-011', 'A3', 11, 'Dartrix', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_011_EN_SM.webp'),
  ('A3-012', 'A3', 12, 'Decidueye ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_012_EN_SM.webp'),
  ('A3-013', 'A3', 13, 'Grubbin', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_013_EN_SM.webp'),
  ('A3-014', 'A3', 14, 'Fomantis', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_014_EN_SM.webp'),
  ('A3-015', 'A3', 15, 'Lurantis', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_015_EN_SM.webp'),
  ('A3-016', 'A3', 16, 'Morelull', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_016_EN_SM.webp'),
  ('A3-017', 'A3', 17, 'Shiinotic', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_017_EN_SM.webp'),
  ('A3-018', 'A3', 18, 'Bounsweet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_018_EN_SM.webp'),
  ('A3-019', 'A3', 19, 'Steenee', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_019_EN_SM.webp'),
  ('A3-020', 'A3', 20, 'Tsareena', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_020_EN_SM.webp'),
  ('A3-021', 'A3', 21, 'Wimpod', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_021_EN_SM.webp'),
  ('A3-022', 'A3', 22, 'Golisopod', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_022_EN_SM.webp'),
  ('A3-023', 'A3', 23, 'Dhelmise ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_023_EN_SM.webp'),
  ('A3-024', 'A3', 24, 'Tapu Bulu', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_024_EN_SM.webp'),
  ('A3-025', 'A3', 25, 'Growlithe', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_025_EN_SM.webp'),
  ('A3-026', 'A3', 26, 'Arcanine', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_026_EN_SM.webp'),
  ('A3-027', 'A3', 27, 'Alolan Marowak', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_027_EN_SM.webp'),
  ('A3-028', 'A3', 28, 'Fletchinder', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_028_EN_SM.webp'),
  ('A3-029', 'A3', 29, 'Talonflame', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_029_EN_SM.webp'),
  ('A3-030', 'A3', 30, 'Litten', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_030_EN_SM.webp'),
  ('A3-031', 'A3', 31, 'Litten', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_031_EN_SM.webp'),
  ('A3-032', 'A3', 32, 'Torracat', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_032_EN_SM.webp'),
  ('A3-033', 'A3', 33, 'Incineroar ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_033_EN_SM.webp'),
  ('A3-034', 'A3', 34, 'Oricorio', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_034_EN_SM.webp'),
  ('A3-035', 'A3', 35, 'Salandit', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_035_EN_SM.webp'),
  ('A3-036', 'A3', 36, 'Salazzle', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_036_EN_SM.webp'),
  ('A3-037', 'A3', 37, 'Turtonator', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_037_EN_SM.webp'),
  ('A3-038', 'A3', 38, 'Alolan Sandshrew', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_038_EN_SM.webp'),
  ('A3-039', 'A3', 39, 'Alolan Sandslash', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_039_EN_SM.webp'),
  ('A3-040', 'A3', 40, 'Alolan Vulpix', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_040_EN_SM.webp'),
  ('A3-041', 'A3', 41, 'Alolan Ninetales', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_041_EN_SM.webp'),
  ('A3-042', 'A3', 42, 'Shellder', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_042_EN_SM.webp'),
  ('A3-043', 'A3', 43, 'Cloyster', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_043_EN_SM.webp'),
  ('A3-044', 'A3', 44, 'Lapras', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_044_EN_SM.webp'),
  ('A3-045', 'A3', 45, 'Popplio', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_045_EN_SM.webp'),
  ('A3-046', 'A3', 46, 'Popplio', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_046_EN_SM.webp'),
  ('A3-047', 'A3', 47, 'Brionne', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_047_EN_SM.webp'),
  ('A3-048', 'A3', 48, 'Primarina', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_048_EN_SM.webp'),
  ('A3-049', 'A3', 49, 'Crabominable ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_049_EN_SM.webp'),
  ('A3-050', 'A3', 50, 'Wishiwashi', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_050_EN_SM.webp'),
  ('A3-051', 'A3', 51, 'Wishiwashi ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_051_EN_SM.webp'),
  ('A3-052', 'A3', 52, 'Dewpider', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_052_EN_SM.webp'),
  ('A3-053', 'A3', 53, 'Araquanid', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_053_EN_SM.webp'),
  ('A3-054', 'A3', 54, 'Pyukumuku', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_054_EN_SM.webp'),
  ('A3-055', 'A3', 55, 'Bruxish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_055_EN_SM.webp'),
  ('A3-056', 'A3', 56, 'Tapu Fini', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_056_EN_SM.webp'),
  ('A3-057', 'A3', 57, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_057_EN_SM.webp'),
  ('A3-058', 'A3', 58, 'Alolan Raichu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_058_EN_SM.webp'),
  ('A3-059', 'A3', 59, 'Alolan Geodude', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_059_EN_SM.webp'),
  ('A3-060', 'A3', 60, 'Alolan Graveler', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_060_EN_SM.webp'),
  ('A3-061', 'A3', 61, 'Alolan Golem', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_061_EN_SM.webp'),
  ('A3-062', 'A3', 62, 'Helioptile', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_062_EN_SM.webp'),
  ('A3-063', 'A3', 63, 'Heliolisk', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_063_EN_SM.webp'),
  ('A3-064', 'A3', 64, 'Charjabug', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_064_EN_SM.webp'),
  ('A3-065', 'A3', 65, 'Vikavolt', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_065_EN_SM.webp'),
  ('A3-066', 'A3', 66, 'Oricorio', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_066_EN_SM.webp'),
  ('A3-067', 'A3', 67, 'Togedemaru', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_067_EN_SM.webp'),
  ('A3-068', 'A3', 68, 'Tapu Koko', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_068_EN_SM.webp'),
  ('A3-069', 'A3', 69, 'Mr. Mime', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_069_EN_SM.webp'),
  ('A3-070', 'A3', 70, 'Sableye', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_070_EN_SM.webp'),
  ('A3-071', 'A3', 71, 'Spoink', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_071_EN_SM.webp'),
  ('A3-072', 'A3', 72, 'Grumpig', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_072_EN_SM.webp'),
  ('A3-073', 'A3', 73, 'Lunatone', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_073_EN_SM.webp'),
  ('A3-074', 'A3', 74, 'Shuppet', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_074_EN_SM.webp'),
  ('A3-075', 'A3', 75, 'Banette', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_075_EN_SM.webp'),
  ('A3-076', 'A3', 76, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_076_EN_SM.webp'),
  ('A3-077', 'A3', 77, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_077_EN_SM.webp'),
  ('A3-078', 'A3', 78, 'Cutiefly', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_078_EN_SM.webp'),
  ('A3-079', 'A3', 79, 'Ribombee', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_079_EN_SM.webp'),
  ('A3-080', 'A3', 80, 'Comfey', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_080_EN_SM.webp'),
  ('A3-081', 'A3', 81, 'Sandygast', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_081_EN_SM.webp'),
  ('A3-082', 'A3', 82, 'Palossand', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_082_EN_SM.webp'),
  ('A3-083', 'A3', 83, 'Mimikyu', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_083_EN_SM.webp'),
  ('A3-084', 'A3', 84, 'Tapu Lele', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_084_EN_SM.webp'),
  ('A3-085', 'A3', 85, 'Cosmog', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_085_EN_SM.webp'),
  ('A3-086', 'A3', 86, 'Cosmoem', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_086_EN_SM.webp'),
  ('A3-087', 'A3', 87, 'Lunala ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_087_EN_SM.webp'),
  ('A3-088', 'A3', 88, 'Necrozma', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_088_EN_SM.webp'),
  ('A3-089', 'A3', 89, 'Cubone', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_089_EN_SM.webp'),
  ('A3-090', 'A3', 90, 'Makuhita', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_090_EN_SM.webp'),
  ('A3-091', 'A3', 91, 'Hariyama', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_091_EN_SM.webp'),
  ('A3-092', 'A3', 92, 'Solrock', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_092_EN_SM.webp'),
  ('A3-093', 'A3', 93, 'Drilbur', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_093_EN_SM.webp'),
  ('A3-094', 'A3', 94, 'Timburr', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_094_EN_SM.webp'),
  ('A3-095', 'A3', 95, 'Gurdurr', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_095_EN_SM.webp'),
  ('A3-096', 'A3', 96, 'Conkeldurr', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_096_EN_SM.webp'),
  ('A3-097', 'A3', 97, 'Crabrawler', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_097_EN_SM.webp'),
  ('A3-098', 'A3', 98, 'Rockruff', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_098_EN_SM.webp'),
  ('A3-099', 'A3', 99, 'Rockruff', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_099_EN_SM.webp'),
  ('A3-100', 'A3', 100, 'Lycanroc', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_100_EN_SM.webp'),
  ('A3-101', 'A3', 101, 'Lycanroc', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_101_EN_SM.webp'),
  ('A3-102', 'A3', 102, 'Mudbray', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_102_EN_SM.webp'),
  ('A3-103', 'A3', 103, 'Mudsdale', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_103_EN_SM.webp'),
  ('A3-104', 'A3', 104, 'Passimian ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_104_EN_SM.webp'),
  ('A3-105', 'A3', 105, 'Minior', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_105_EN_SM.webp'),
  ('A3-106', 'A3', 106, 'Alolan Rattata', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_106_EN_SM.webp'),
  ('A3-107', 'A3', 107, 'Alolan Raticate', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_107_EN_SM.webp'),
  ('A3-108', 'A3', 108, 'Alolan Meowth', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_108_EN_SM.webp'),
  ('A3-109', 'A3', 109, 'Alolan Persian', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_109_EN_SM.webp'),
  ('A3-110', 'A3', 110, 'Alolan Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_110_EN_SM.webp'),
  ('A3-111', 'A3', 111, 'Alolan Muk ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_111_EN_SM.webp'),
  ('A3-112', 'A3', 112, 'Absol', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_112_EN_SM.webp'),
  ('A3-113', 'A3', 113, 'Trubbish', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_113_EN_SM.webp'),
  ('A3-114', 'A3', 114, 'Garbodor', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_114_EN_SM.webp'),
  ('A3-115', 'A3', 115, 'Mareanie', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_115_EN_SM.webp'),
  ('A3-116', 'A3', 116, 'Toxapex', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_116_EN_SM.webp'),
  ('A3-117', 'A3', 117, 'Alolan Diglett', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_117_EN_SM.webp'),
  ('A3-118', 'A3', 118, 'Alolan Dugtrio', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_118_EN_SM.webp'),
  ('A3-119', 'A3', 119, 'Excadrill', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_119_EN_SM.webp'),
  ('A3-120', 'A3', 120, 'Escavalier', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_120_EN_SM.webp'),
  ('A3-121', 'A3', 121, 'Klefki', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_121_EN_SM.webp'),
  ('A3-122', 'A3', 122, 'Solgaleo ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_122_EN_SM.webp'),
  ('A3-123', 'A3', 123, 'Magearna', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_123_EN_SM.webp'),
  ('A3-124', 'A3', 124, 'Drampa', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_124_EN_SM.webp'),
  ('A3-125', 'A3', 125, 'Jangmo-o', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_125_EN_SM.webp'),
  ('A3-126', 'A3', 126, 'Hakamo-o', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_126_EN_SM.webp'),
  ('A3-127', 'A3', 127, 'Kommo-o', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_127_EN_SM.webp'),
  ('A3-128', 'A3', 128, 'Tauros', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_128_EN_SM.webp'),
  ('A3-129', 'A3', 129, 'Skitty', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_129_EN_SM.webp'),
  ('A3-130', 'A3', 130, 'Delcatty', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_130_EN_SM.webp'),
  ('A3-131', 'A3', 131, 'Fletchling', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_131_EN_SM.webp'),
  ('A3-132', 'A3', 132, 'Hawlucha', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_132_EN_SM.webp'),
  ('A3-133', 'A3', 133, 'Pikipek', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_133_EN_SM.webp'),
  ('A3-134', 'A3', 134, 'Trumbeak', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_134_EN_SM.webp'),
  ('A3-135', 'A3', 135, 'Toucannon', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_135_EN_SM.webp'),
  ('A3-136', 'A3', 136, 'Yungoos', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_136_EN_SM.webp'),
  ('A3-137', 'A3', 137, 'Gumshoos', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_137_EN_SM.webp'),
  ('A3-138', 'A3', 138, 'Stufful', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_138_EN_SM.webp'),
  ('A3-139', 'A3', 139, 'Bewear', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_139_EN_SM.webp'),
  ('A3-140', 'A3', 140, 'Oranguru', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_140_EN_SM.webp'),
  ('A3-141', 'A3', 141, 'Komala', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_141_EN_SM.webp'),
  ('A3-142', 'A3', 142, 'Big Malasada', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_142_EN_SM.webp'),
  ('A3-143', 'A3', 143, 'Fishing Net', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_143_EN_SM.webp'),
  ('A3-144', 'A3', 144, 'Rare Candy', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_144_EN_SM.webp'),
  ('A3-145', 'A3', 145, 'Rotom Dex', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_145_EN_SM.webp'),
  ('A3-146', 'A3', 146, 'Poison Barb', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_146_EN_SM.webp'),
  ('A3-147', 'A3', 147, 'Leaf Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_147_EN_SM.webp'),
  ('A3-148', 'A3', 148, 'Acerola', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_148_EN_SM.webp'),
  ('A3-149', 'A3', 149, 'Ilima', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_149_EN_SM.webp'),
  ('A3-150', 'A3', 150, 'Kiawe', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_150_EN_SM.webp'),
  ('A3-151', 'A3', 151, 'Guzma', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_151_EN_SM.webp'),
  ('A3-152', 'A3', 152, 'Lana', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_152_EN_SM.webp'),
  ('A3-153', 'A3', 153, 'Sophocles', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_153_EN_SM.webp'),
  ('A3-154', 'A3', 154, 'Mallow', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_154_EN_SM.webp'),
  ('A3-155', 'A3', 155, 'Lillie', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_155_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A3-156', 'A3', 156, 'Alolan Exeggutor', 'pokemon', 'grass', null, 'star_1', 'A3-002', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_156_EN_SM.webp'),
  ('A3-157', 'A3', 157, 'Morelull', 'pokemon', 'grass', null, 'star_1', 'A3-016', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_157_EN_SM.webp'),
  ('A3-158', 'A3', 158, 'Tsareena', 'pokemon', 'grass', null, 'star_1', 'A3-020', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_158_EN_SM.webp'),
  ('A3-159', 'A3', 159, 'Tapu Bulu', 'pokemon', 'grass', null, 'star_1', 'A3-024', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_159_EN_SM.webp'),
  ('A3-160', 'A3', 160, 'Alolan Marowak', 'pokemon', 'fire', null, 'star_1', 'A3-027', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_160_EN_SM.webp'),
  ('A3-161', 'A3', 161, 'Turtonator', 'pokemon', 'fire', null, 'star_1', 'A3-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_161_EN_SM.webp'),
  ('A3-162', 'A3', 162, 'Alolan Vulpix', 'pokemon', 'water', null, 'star_1', 'A3-040', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_162_EN_SM.webp'),
  ('A3-163', 'A3', 163, 'Pyukumuku', 'pokemon', 'water', null, 'star_1', 'A3-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_163_EN_SM.webp'),
  ('A3-164', 'A3', 164, 'Tapu Fini', 'pokemon', 'water', null, 'star_1', 'A3-056', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_164_EN_SM.webp'),
  ('A3-165', 'A3', 165, 'Oricorio', 'pokemon', 'lightning', null, 'star_1', 'A3-034', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_165_EN_SM.webp'),
  ('A3-166', 'A3', 166, 'Tapu Koko', 'pokemon', 'lightning', null, 'star_1', 'A3-068', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_166_EN_SM.webp'),
  ('A3-167', 'A3', 167, 'Cutiefly', 'pokemon', 'psychic', null, 'star_1', 'A3-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_167_EN_SM.webp'),
  ('A3-168', 'A3', 168, 'Comfey', 'pokemon', 'psychic', null, 'star_1', 'A3-080', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_168_EN_SM.webp'),
  ('A3-169', 'A3', 169, 'Sandygast', 'pokemon', 'psychic', null, 'star_1', 'A3-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_169_EN_SM.webp'),
  ('A3-170', 'A3', 170, 'Tapu Lele', 'pokemon', 'psychic', null, 'star_1', 'A3-084', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_170_EN_SM.webp'),
  ('A3-171', 'A3', 171, 'Cosmog', 'pokemon', 'psychic', null, 'star_1', 'A3-085', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_171_EN_SM.webp'),
  ('A3-172', 'A3', 172, 'Rockruff', 'pokemon', 'fighting', null, 'star_1', 'A3-098', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_172_EN_SM.webp'),
  ('A3-173', 'A3', 173, 'Mudsdale', 'pokemon', 'fighting', null, 'star_1', 'A3-103', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_173_EN_SM.webp'),
  ('A3-174', 'A3', 174, 'Minior', 'pokemon', 'fighting', null, 'star_1', 'A3-105', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_174_EN_SM.webp'),
  ('A3-175', 'A3', 175, 'Magearna', 'pokemon', 'metal', null, 'star_1', 'A3-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_175_EN_SM.webp'),
  ('A3-176', 'A3', 176, 'Drampa', 'pokemon', 'dragon', null, 'star_1', 'A3-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_176_EN_SM.webp'),
  ('A3-177', 'A3', 177, 'Pikipek', 'pokemon', 'colorless', null, 'star_1', 'A3-133', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_177_EN_SM.webp'),
  ('A3-178', 'A3', 178, 'Bewear', 'pokemon', 'colorless', null, 'star_1', 'A3-139', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_178_EN_SM.webp'),
  ('A3-179', 'A3', 179, 'Komala', 'pokemon', 'colorless', null, 'star_1', 'A3-141', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_179_EN_SM.webp'),
  ('A3-180', 'A3', 180, 'Decidueye ex', 'pokemon', 'grass', null, 'star_2', 'A3-012', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_180_EN_SM.webp'),
  ('A3-181', 'A3', 181, 'Dhelmise ex', 'pokemon', 'grass', null, 'star_2', 'A3-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_181_EN_SM.webp'),
  ('A3-182', 'A3', 182, 'Incineroar ex', 'pokemon', 'fire', null, 'star_2', 'A3-033', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_182_EN_SM.webp'),
  ('A3-183', 'A3', 183, 'Crabominable ex', 'pokemon', 'water', null, 'star_2', 'A3-049', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_183_EN_SM.webp'),
  ('A3-184', 'A3', 184, 'Wishiwashi ex', 'pokemon', 'water', null, 'star_2', 'A3-051', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_184_EN_SM.webp'),
  ('A3-185', 'A3', 185, 'Alolan Raichu ex', 'pokemon', 'lightning', null, 'star_2', 'A3-058', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_185_EN_SM.webp'),
  ('A3-186', 'A3', 186, 'Lunala ex', 'pokemon', 'psychic', null, 'star_2', 'A3-087', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_186_EN_SM.webp'),
  ('A3-187', 'A3', 187, 'Passimian ex', 'pokemon', 'fighting', null, 'star_2', 'A3-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_187_EN_SM.webp'),
  ('A3-188', 'A3', 188, 'Alolan Muk ex', 'pokemon', 'darkness', null, 'star_2', 'A3-111', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_188_EN_SM.webp'),
  ('A3-189', 'A3', 189, 'Solgaleo ex', 'pokemon', 'metal', null, 'star_2', 'A3-122', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_189_EN_SM.webp'),
  ('A3-190', 'A3', 190, 'Acerola', 'trainer', null, 'supporter', 'star_2', 'A3-148', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_190_EN_SM.webp'),
  ('A3-191', 'A3', 191, 'Ilima', 'trainer', null, 'supporter', 'star_2', 'A3-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_191_EN_SM.webp'),
  ('A3-192', 'A3', 192, 'Kiawe', 'trainer', null, 'supporter', 'star_2', 'A3-150', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_192_EN_SM.webp'),
  ('A3-193', 'A3', 193, 'Guzma', 'trainer', null, 'supporter', 'star_2', 'A3-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_193_EN_SM.webp'),
  ('A3-194', 'A3', 194, 'Lana', 'trainer', null, 'supporter', 'star_2', 'A3-152', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_194_EN_SM.webp'),
  ('A3-195', 'A3', 195, 'Sophocles', 'trainer', null, 'supporter', 'star_2', 'A3-153', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_195_EN_SM.webp'),
  ('A3-196', 'A3', 196, 'Mallow', 'trainer', null, 'supporter', 'star_2', 'A3-154', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_196_EN_SM.webp'),
  ('A3-197', 'A3', 197, 'Lillie', 'trainer', null, 'supporter', 'star_2', 'A3-155', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_197_EN_SM.webp'),
  ('A3-198', 'A3', 198, 'Decidueye ex', 'pokemon', 'grass', null, 'star_2', 'A3-012', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_198_EN_SM.webp'),
  ('A3-199', 'A3', 199, 'Dhelmise ex', 'pokemon', 'grass', null, 'star_2', 'A3-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_199_EN_SM.webp'),
  ('A3-200', 'A3', 200, 'Incineroar ex', 'pokemon', 'fire', null, 'star_2', 'A3-033', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_200_EN_SM.webp'),
  ('A3-201', 'A3', 201, 'Crabominable ex', 'pokemon', 'water', null, 'star_2', 'A3-049', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_201_EN_SM.webp'),
  ('A3-202', 'A3', 202, 'Wishiwashi ex', 'pokemon', 'water', null, 'star_2', 'A3-051', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_202_EN_SM.webp'),
  ('A3-203', 'A3', 203, 'Alolan Raichu ex', 'pokemon', 'lightning', null, 'star_2', 'A3-058', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_203_EN_SM.webp'),
  ('A3-204', 'A3', 204, 'Lunala ex', 'pokemon', 'psychic', null, 'star_2', 'A3-087', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_204_EN_SM.webp'),
  ('A3-205', 'A3', 205, 'Passimian ex', 'pokemon', 'fighting', null, 'star_2', 'A3-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_205_EN_SM.webp'),
  ('A3-206', 'A3', 206, 'Alolan Muk ex', 'pokemon', 'darkness', null, 'star_2', 'A3-111', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_206_EN_SM.webp'),
  ('A3-207', 'A3', 207, 'Solgaleo ex', 'pokemon', 'metal', null, 'star_2', 'A3-122', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_207_EN_SM.webp'),
  ('A3-208', 'A3', 208, 'Guzma', 'trainer', null, 'supporter', 'star_3', 'A3-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_208_EN_SM.webp'),
  ('A3-209', 'A3', 209, 'Lillie', 'trainer', null, 'supporter', 'star_3', 'A3-155', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_209_EN_SM.webp'),
  ('A3-210', 'A3', 210, 'Bulbasaur', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_210_EN_SM.webp'),
  ('A3-211', 'A3', 211, 'Ivysaur', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_211_EN_SM.webp'),
  ('A3-212', 'A3', 212, 'Venusaur', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_212_EN_SM.webp'),
  ('A3-213', 'A3', 213, 'Exeggcute', 'pokemon', 'grass', null, 'star_1', 'A3-001', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_213_EN_SM.webp'),
  ('A3-214', 'A3', 214, 'Exeggutor', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_214_EN_SM.webp'),
  ('A3-215', 'A3', 215, 'Squirtle', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_215_EN_SM.webp'),
  ('A3-216', 'A3', 216, 'Wartortle', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_216_EN_SM.webp'),
  ('A3-217', 'A3', 217, 'Blastoise', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_217_EN_SM.webp'),
  ('A3-218', 'A3', 218, 'Staryu', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_218_EN_SM.webp'),
  ('A3-219', 'A3', 219, 'Starmie', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_219_EN_SM.webp'),
  ('A3-220', 'A3', 220, 'Gastly', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_220_EN_SM.webp'),
  ('A3-221', 'A3', 221, 'Haunter', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_221_EN_SM.webp'),
  ('A3-222', 'A3', 222, 'Gengar', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_222_EN_SM.webp'),
  ('A3-223', 'A3', 223, 'Machop', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_223_EN_SM.webp'),
  ('A3-224', 'A3', 224, 'Machoke', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_224_EN_SM.webp'),
  ('A3-225', 'A3', 225, 'Machamp', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_225_EN_SM.webp'),
  ('A3-226', 'A3', 226, 'Cubone', 'pokemon', 'fighting', null, 'star_1', 'A3-089', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_226_EN_SM.webp'),
  ('A3-227', 'A3', 227, 'Marowak', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_227_EN_SM.webp'),
  ('A3-228', 'A3', 228, 'Jigglypuff', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_228_EN_SM.webp'),
  ('A3-229', 'A3', 229, 'Wigglytuff', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_229_EN_SM.webp'),
  ('A3-230', 'A3', 230, 'Venusaur ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_230_EN_SM.webp'),
  ('A3-231', 'A3', 231, 'Exeggutor ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_231_EN_SM.webp'),
  ('A3-232', 'A3', 232, 'Blastoise ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_232_EN_SM.webp'),
  ('A3-233', 'A3', 233, 'Starmie ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_233_EN_SM.webp'),
  ('A3-234', 'A3', 234, 'Gengar ex', 'pokemon', 'psychic', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_234_EN_SM.webp'),
  ('A3-235', 'A3', 235, 'Machamp ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_235_EN_SM.webp'),
  ('A3-236', 'A3', 236, 'Marowak ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_236_EN_SM.webp'),
  ('A3-237', 'A3', 237, 'Wigglytuff ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_237_EN_SM.webp'),
  ('A3-238', 'A3', 238, 'Lunala ex', 'pokemon', 'psychic', null, 'crown', 'A3-087', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_238_EN_SM.webp'),
  ('A3-239', 'A3', 239, 'Solgaleo ex', 'pokemon', 'metal', null, 'crown', 'A3-122', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_239_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 239 cards, numbered 1 through 239.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'A3';
