-- Pulsing Aura (B3): 155 main-set cards and 79 secret cards.
-- Source checked 2026-06-25: https://pocket.limitlesstcg.com/cards/B3?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B3-001', 'B3', 1, 'Tangela', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_001_EN_SM.webp'),
  ('B3-002', 'B3', 2, 'Tangrowth', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_002_EN_SM.webp'),
  ('B3-003', 'B3', 3, 'Heracross', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_003_EN_SM.webp'),
  ('B3-004', 'B3', 4, 'Celebi', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_004_EN_SM.webp'),
  ('B3-005', 'B3', 5, 'Treecko', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_005_EN_SM.webp'),
  ('B3-006', 'B3', 6, 'Grovyle', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_006_EN_SM.webp'),
  ('B3-007', 'B3', 7, 'Sceptile', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_007_EN_SM.webp'),
  ('B3-008', 'B3', 8, 'Mega Sceptile ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_008_EN_SM.webp'),
  ('B3-009', 'B3', 9, 'Surskit', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_009_EN_SM.webp'),
  ('B3-010', 'B3', 10, 'Masquerain', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_010_EN_SM.webp'),
  ('B3-011', 'B3', 11, 'Shroomish', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_011_EN_SM.webp'),
  ('B3-012', 'B3', 12, 'Breloom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_012_EN_SM.webp'),
  ('B3-013', 'B3', 13, 'Budew', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_013_EN_SM.webp'),
  ('B3-014', 'B3', 14, 'Carnivine', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_014_EN_SM.webp'),
  ('B3-015', 'B3', 15, 'Sewaddle', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_015_EN_SM.webp'),
  ('B3-016', 'B3', 16, 'Swadloon', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_016_EN_SM.webp'),
  ('B3-017', 'B3', 17, 'Leavanny', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_017_EN_SM.webp'),
  ('B3-018', 'B3', 18, 'Durant', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_018_EN_SM.webp'),
  ('B3-019', 'B3', 19, 'Applin', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_019_EN_SM.webp'),
  ('B3-020', 'B3', 20, 'Flapple', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_020_EN_SM.webp'),
  ('B3-021', 'B3', 21, 'Numel', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_021_EN_SM.webp'),
  ('B3-022', 'B3', 22, 'Camerupt', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_022_EN_SM.webp'),
  ('B3-023', 'B3', 23, 'Mega Camerupt ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_023_EN_SM.webp'),
  ('B3-024', 'B3', 24, 'Castform Sunny Form', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_024_EN_SM.webp'),
  ('B3-025', 'B3', 25, 'Victini', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_025_EN_SM.webp'),
  ('B3-026', 'B3', 26, 'Tepig', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_026_EN_SM.webp'),
  ('B3-027', 'B3', 27, 'Pignite', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_027_EN_SM.webp'),
  ('B3-028', 'B3', 28, 'Emboar', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_028_EN_SM.webp'),
  ('B3-029', 'B3', 29, 'Darumaka', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_029_EN_SM.webp'),
  ('B3-030', 'B3', 30, 'Darmanitan', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_030_EN_SM.webp'),
  ('B3-031', 'B3', 31, 'Larvesta', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_031_EN_SM.webp'),
  ('B3-032', 'B3', 32, 'Volcarona', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_032_EN_SM.webp'),
  ('B3-033', 'B3', 33, 'Poliwag', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_033_EN_SM.webp'),
  ('B3-034', 'B3', 34, 'Poliwhirl', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_034_EN_SM.webp'),
  ('B3-035', 'B3', 35, 'Politoed', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_035_EN_SM.webp'),
  ('B3-036', 'B3', 36, 'Paldean Tauros', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_036_EN_SM.webp'),
  ('B3-037', 'B3', 37, 'Vaporeon ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_037_EN_SM.webp'),
  ('B3-038', 'B3', 38, 'Wooper', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_038_EN_SM.webp'),
  ('B3-039', 'B3', 39, 'Quagsire', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_039_EN_SM.webp'),
  ('B3-040', 'B3', 40, 'Castform Rainy Form', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_040_EN_SM.webp'),
  ('B3-041', 'B3', 41, 'Castform Snowy Form', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_041_EN_SM.webp'),
  ('B3-042', 'B3', 42, 'Clamperl', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_042_EN_SM.webp'),
  ('B3-043', 'B3', 43, 'Huntail', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_043_EN_SM.webp'),
  ('B3-044', 'B3', 44, 'Gorebyss', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_044_EN_SM.webp'),
  ('B3-045', 'B3', 45, 'Regice', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_045_EN_SM.webp'),
  ('B3-046', 'B3', 46, 'Cubchoo', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_046_EN_SM.webp'),
  ('B3-047', 'B3', 47, 'Beartic', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_047_EN_SM.webp'),
  ('B3-048', 'B3', 48, 'Sobble', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_048_EN_SM.webp'),
  ('B3-049', 'B3', 49, 'Drizzile', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_049_EN_SM.webp'),
  ('B3-050', 'B3', 50, 'Inteleon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_050_EN_SM.webp'),
  ('B3-051', 'B3', 51, 'Rapid Strike Urshifu', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_051_EN_SM.webp'),
  ('B3-052', 'B3', 52, 'Magnemite', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_052_EN_SM.webp'),
  ('B3-053', 'B3', 53, 'Magneton', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_053_EN_SM.webp'),
  ('B3-054', 'B3', 54, 'Magnezone ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_054_EN_SM.webp'),
  ('B3-055', 'B3', 55, 'Voltorb', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_055_EN_SM.webp'),
  ('B3-056', 'B3', 56, 'Electrode', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_056_EN_SM.webp'),
  ('B3-057', 'B3', 57, 'Chinchou', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_057_EN_SM.webp'),
  ('B3-058', 'B3', 58, 'Lanturn', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_058_EN_SM.webp'),
  ('B3-059', 'B3', 59, 'Zekrom', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_059_EN_SM.webp'),
  ('B3-060', 'B3', 60, 'Toxel', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_060_EN_SM.webp'),
  ('B3-061', 'B3', 61, 'Toxtricity', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_061_EN_SM.webp'),
  ('B3-062', 'B3', 62, 'Morpeko', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_062_EN_SM.webp'),
  ('B3-063', 'B3', 63, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_063_EN_SM.webp'),
  ('B3-064', 'B3', 64, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_064_EN_SM.webp'),
  ('B3-065', 'B3', 65, 'Espurr', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_065_EN_SM.webp'),
  ('B3-066', 'B3', 66, 'Meowstic', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_066_EN_SM.webp'),
  ('B3-067', 'B3', 67, 'Diancie', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_067_EN_SM.webp'),
  ('B3-068', 'B3', 68, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_068_EN_SM.webp'),
  ('B3-069', 'B3', 69, 'Hatenna', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_069_EN_SM.webp'),
  ('B3-070', 'B3', 70, 'Hattrem', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_070_EN_SM.webp'),
  ('B3-071', 'B3', 71, 'Hatterene', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_071_EN_SM.webp'),
  ('B3-072', 'B3', 72, 'Bramblin', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_072_EN_SM.webp'),
  ('B3-073', 'B3', 73, 'Brambleghast', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_073_EN_SM.webp'),
  ('B3-074', 'B3', 74, 'Gligar', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_074_EN_SM.webp'),
  ('B3-075', 'B3', 75, 'Gliscor', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_075_EN_SM.webp'),
  ('B3-076', 'B3', 76, 'Trapinch', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_076_EN_SM.webp'),
  ('B3-077', 'B3', 77, 'Regirock', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_077_EN_SM.webp'),
  ('B3-078', 'B3', 78, 'Bonsly', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_078_EN_SM.webp'),
  ('B3-079', 'B3', 79, 'Riolu', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_079_EN_SM.webp'),
  ('B3-080', 'B3', 80, 'Lucario', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_080_EN_SM.webp'),
  ('B3-081', 'B3', 81, 'Mega Lucario ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_081_EN_SM.webp'),
  ('B3-082', 'B3', 82, 'Croagunk', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_082_EN_SM.webp'),
  ('B3-083', 'B3', 83, 'Toxicroak', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_083_EN_SM.webp'),
  ('B3-084', 'B3', 84, 'Gallade', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_084_EN_SM.webp'),
  ('B3-085', 'B3', 85, 'Throh', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_085_EN_SM.webp'),
  ('B3-086', 'B3', 86, 'Sawk', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_086_EN_SM.webp'),
  ('B3-087', 'B3', 87, 'Dwebble', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_087_EN_SM.webp'),
  ('B3-088', 'B3', 88, 'Crustle ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_088_EN_SM.webp'),
  ('B3-089', 'B3', 89, 'Meloetta', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_089_EN_SM.webp'),
  ('B3-090', 'B3', 90, 'Stufful', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_090_EN_SM.webp'),
  ('B3-091', 'B3', 91, 'Bewear', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_091_EN_SM.webp'),
  ('B3-092', 'B3', 92, 'Rolycoly', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_092_EN_SM.webp'),
  ('B3-093', 'B3', 93, 'Carkol', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_093_EN_SM.webp'),
  ('B3-094', 'B3', 94, 'Coalossal', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_094_EN_SM.webp'),
  ('B3-095', 'B3', 95, 'Silicobra', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_095_EN_SM.webp'),
  ('B3-096', 'B3', 96, 'Sandaconda', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_096_EN_SM.webp'),
  ('B3-097', 'B3', 97, 'Kubfu', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_097_EN_SM.webp'),
  ('B3-098', 'B3', 98, 'Zubat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_098_EN_SM.webp'),
  ('B3-099', 'B3', 99, 'Golbat', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_099_EN_SM.webp'),
  ('B3-100', 'B3', 100, 'Crobat', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_100_EN_SM.webp'),
  ('B3-101', 'B3', 101, 'Koffing', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_101_EN_SM.webp'),
  ('B3-102', 'B3', 102, 'Weezing', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_102_EN_SM.webp'),
  ('B3-103', 'B3', 103, 'Qwilfish', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_103_EN_SM.webp'),
  ('B3-104', 'B3', 104, 'Seviper', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_104_EN_SM.webp'),
  ('B3-105', 'B3', 105, 'Zorua', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_105_EN_SM.webp'),
  ('B3-106', 'B3', 106, 'Zoroark ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_106_EN_SM.webp'),
  ('B3-107', 'B3', 107, 'Foongus', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_107_EN_SM.webp'),
  ('B3-108', 'B3', 108, 'Amoonguss', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_108_EN_SM.webp'),
  ('B3-109', 'B3', 109, 'Vullaby', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_109_EN_SM.webp'),
  ('B3-110', 'B3', 110, 'Mandibuzz', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_110_EN_SM.webp'),
  ('B3-111', 'B3', 111, 'Inkay', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_111_EN_SM.webp'),
  ('B3-112', 'B3', 112, 'Malamar', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_112_EN_SM.webp'),
  ('B3-113', 'B3', 113, 'Single Strike Urshifu', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_113_EN_SM.webp'),
  ('B3-114', 'B3', 114, 'Zarude', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_114_EN_SM.webp'),
  ('B3-115', 'B3', 115, 'Bombirdier', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_115_EN_SM.webp'),
  ('B3-116', 'B3', 116, 'Registeel', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_116_EN_SM.webp'),
  ('B3-117', 'B3', 117, 'Bronzor', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_117_EN_SM.webp'),
  ('B3-118', 'B3', 118, 'Bronzong', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_118_EN_SM.webp'),
  ('B3-119', 'B3', 119, 'Pawniard', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_119_EN_SM.webp'),
  ('B3-120', 'B3', 120, 'Bisharp', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_120_EN_SM.webp'),
  ('B3-121', 'B3', 121, 'Magearna', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_121_EN_SM.webp'),
  ('B3-122', 'B3', 122, 'Meltan', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_122_EN_SM.webp'),
  ('B3-123', 'B3', 123, 'Melmetal', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_123_EN_SM.webp'),
  ('B3-124', 'B3', 124, 'Corviknight ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_124_EN_SM.webp'),
  ('B3-125', 'B3', 125, 'Vibrava', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_125_EN_SM.webp'),
  ('B3-126', 'B3', 126, 'Flygon ex', 'pokemon', 'dragon', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_126_EN_SM.webp'),
  ('B3-127', 'B3', 127, 'Chansey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_127_EN_SM.webp'),
  ('B3-128', 'B3', 128, 'Blissey', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_128_EN_SM.webp'),
  ('B3-129', 'B3', 129, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_129_EN_SM.webp'),
  ('B3-130', 'B3', 130, 'Dunsparce', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_130_EN_SM.webp'),
  ('B3-131', 'B3', 131, 'Teddiursa', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_131_EN_SM.webp'),
  ('B3-132', 'B3', 132, 'Ursaring', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_132_EN_SM.webp'),
  ('B3-133', 'B3', 133, 'Castform', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_133_EN_SM.webp'),
  ('B3-134', 'B3', 134, 'Regigigas', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_134_EN_SM.webp'),
  ('B3-135', 'B3', 135, 'Patrat', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_135_EN_SM.webp'),
  ('B3-136', 'B3', 136, 'Watchog', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_136_EN_SM.webp'),
  ('B3-137', 'B3', 137, 'Lillipup', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_137_EN_SM.webp'),
  ('B3-138', 'B3', 138, 'Herdier', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_138_EN_SM.webp'),
  ('B3-139', 'B3', 139, 'Stoutland', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_139_EN_SM.webp'),
  ('B3-140', 'B3', 140, 'Audino', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_140_EN_SM.webp'),
  ('B3-141', 'B3', 141, 'Mega Audino ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_141_EN_SM.webp'),
  ('B3-142', 'B3', 142, 'Minccino', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_142_EN_SM.webp'),
  ('B3-143', 'B3', 143, 'Cinccino', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_143_EN_SM.webp'),
  ('B3-144', 'B3', 144, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_144_EN_SM.webp'),
  ('B3-145', 'B3', 145, 'Rookidee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_145_EN_SM.webp'),
  ('B3-146', 'B3', 146, 'Corvisquire', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_146_EN_SM.webp'),
  ('B3-147', 'B3', 147, 'Field Blower', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_147_EN_SM.webp'),
  ('B3-148', 'B3', 148, 'Lucky Egg', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_148_EN_SM.webp'),
  ('B3-149', 'B3', 149, 'Korrina', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_149_EN_SM.webp'),
  ('B3-150', 'B3', 150, 'Cabbie', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_150_EN_SM.webp'),
  ('B3-151', 'B3', 151, 'Cheren', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_151_EN_SM.webp'),
  ('B3-152', 'B3', 152, 'Parasol Lady', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_152_EN_SM.webp'),
  ('B3-153', 'B3', 153, 'Fragrant Forest', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_153_EN_SM.webp'),
  ('B3-154', 'B3', 154, 'Arena of Antiquity', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_154_EN_SM.webp'),
  ('B3-155', 'B3', 155, 'Bounded Field', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_155_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B3-156', 'B3', 156, 'Treecko', 'pokemon', 'grass', null, 'star_1', 'B3-005', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_156_EN_SM.webp'),
  ('B3-157', 'B3', 157, 'Grovyle', 'pokemon', 'grass', null, 'star_1', 'B3-006', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_157_EN_SM.webp'),
  ('B3-158', 'B3', 158, 'Shroomish', 'pokemon', 'grass', null, 'star_1', 'B3-011', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_158_EN_SM.webp'),
  ('B3-159', 'B3', 159, 'Budew', 'pokemon', 'grass', null, 'star_1', 'B3-013', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_159_EN_SM.webp'),
  ('B3-160', 'B3', 160, 'Flapple', 'pokemon', 'grass', null, 'star_1', 'B3-020', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_160_EN_SM.webp'),
  ('B3-161', 'B3', 161, 'Tepig', 'pokemon', 'fire', null, 'star_1', 'B3-026', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_161_EN_SM.webp'),
  ('B3-162', 'B3', 162, 'Quagsire', 'pokemon', 'water', null, 'star_1', 'B3-039', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_162_EN_SM.webp'),
  ('B3-163', 'B3', 163, 'Zekrom', 'pokemon', 'lightning', null, 'star_1', 'B3-059', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_163_EN_SM.webp'),
  ('B3-164', 'B3', 164, 'Morpeko', 'pokemon', 'lightning', null, 'star_1', 'B3-062', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_164_EN_SM.webp'),
  ('B3-165', 'B3', 165, 'Meowstic', 'pokemon', 'psychic', null, 'star_1', 'B3-066', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_165_EN_SM.webp'),
  ('B3-166', 'B3', 166, 'Oricorio', 'pokemon', 'psychic', null, 'star_1', 'B3-068', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_166_EN_SM.webp'),
  ('B3-167', 'B3', 167, 'Brambleghast', 'pokemon', 'psychic', null, 'star_1', 'B3-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_167_EN_SM.webp'),
  ('B3-168', 'B3', 168, 'Bonsly', 'pokemon', 'fighting', null, 'star_1', 'B3-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_168_EN_SM.webp'),
  ('B3-169', 'B3', 169, 'Riolu', 'pokemon', 'fighting', null, 'star_1', 'B3-079', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_169_EN_SM.webp'),
  ('B3-170', 'B3', 170, 'Meloetta', 'pokemon', 'fighting', null, 'star_1', 'B3-089', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_170_EN_SM.webp'),
  ('B3-171', 'B3', 171, 'Carkol', 'pokemon', 'fighting', null, 'star_1', 'B3-093', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_171_EN_SM.webp'),
  ('B3-172', 'B3', 172, 'Kubfu', 'pokemon', 'fighting', null, 'star_1', 'B3-097', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_172_EN_SM.webp'),
  ('B3-173', 'B3', 173, 'Seviper', 'pokemon', 'darkness', null, 'star_1', 'B3-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_173_EN_SM.webp'),
  ('B3-174', 'B3', 174, 'Zorua', 'pokemon', 'darkness', null, 'star_1', 'B3-105', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_174_EN_SM.webp'),
  ('B3-175', 'B3', 175, 'Malamar', 'pokemon', 'darkness', null, 'star_1', 'B3-112', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_175_EN_SM.webp'),
  ('B3-176', 'B3', 176, 'Bisharp', 'pokemon', 'metal', null, 'star_1', 'B3-120', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_176_EN_SM.webp'),
  ('B3-177', 'B3', 177, 'Meltan', 'pokemon', 'metal', null, 'star_1', 'B3-122', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_177_EN_SM.webp'),
  ('B3-178', 'B3', 178, 'Castform', 'pokemon', 'colorless', null, 'star_1', 'B3-133', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_178_EN_SM.webp'),
  ('B3-179', 'B3', 179, 'Cinccino', 'pokemon', 'colorless', null, 'star_1', 'B3-143', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_179_EN_SM.webp'),
  ('B3-180', 'B3', 180, 'Mega Sceptile ex', 'pokemon', 'grass', null, 'star_2', 'B3-008', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_180_EN_SM.webp'),
  ('B3-181', 'B3', 181, 'Mega Camerupt ex', 'pokemon', 'fire', null, 'star_2', 'B3-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_181_EN_SM.webp'),
  ('B3-182', 'B3', 182, 'Vaporeon ex', 'pokemon', 'water', null, 'star_2', 'B3-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_182_EN_SM.webp'),
  ('B3-183', 'B3', 183, 'Magnezone ex', 'pokemon', 'lightning', null, 'star_2', 'B3-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_183_EN_SM.webp'),
  ('B3-184', 'B3', 184, 'Mega Lucario ex', 'pokemon', 'fighting', null, 'star_2', 'B3-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_184_EN_SM.webp'),
  ('B3-185', 'B3', 185, 'Crustle ex', 'pokemon', 'fighting', null, 'star_2', 'B3-088', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_185_EN_SM.webp'),
  ('B3-186', 'B3', 186, 'Zoroark ex', 'pokemon', 'darkness', null, 'star_2', 'B3-106', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_186_EN_SM.webp'),
  ('B3-187', 'B3', 187, 'Corviknight ex', 'pokemon', 'metal', null, 'star_2', 'B3-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_187_EN_SM.webp'),
  ('B3-188', 'B3', 188, 'Flygon ex', 'pokemon', 'dragon', null, 'star_2', 'B3-126', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_188_EN_SM.webp'),
  ('B3-189', 'B3', 189, 'Mega Audino ex', 'pokemon', 'colorless', null, 'star_2', 'B3-141', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_189_EN_SM.webp'),
  ('B3-190', 'B3', 190, 'Korrina', 'trainer', null, 'supporter', 'star_2', 'B3-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_190_EN_SM.webp'),
  ('B3-191', 'B3', 191, 'Cabbie', 'trainer', null, 'supporter', 'star_2', 'B3-150', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_191_EN_SM.webp'),
  ('B3-192', 'B3', 192, 'Cheren', 'trainer', null, 'supporter', 'star_2', 'B3-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_192_EN_SM.webp'),
  ('B3-193', 'B3', 193, 'Parasol Lady', 'trainer', null, 'supporter', 'star_2', 'B3-152', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_193_EN_SM.webp'),
  ('B3-194', 'B3', 194, 'Mega Sceptile ex', 'pokemon', 'grass', null, 'star_2', 'B3-008', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_194_EN_SM.webp'),
  ('B3-195', 'B3', 195, 'Mega Camerupt ex', 'pokemon', 'fire', null, 'star_2', 'B3-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_195_EN_SM.webp'),
  ('B3-196', 'B3', 196, 'Vaporeon ex', 'pokemon', 'water', null, 'star_2', 'B3-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_196_EN_SM.webp'),
  ('B3-197', 'B3', 197, 'Magnezone ex', 'pokemon', 'lightning', null, 'star_2', 'B3-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_197_EN_SM.webp'),
  ('B3-198', 'B3', 198, 'Crustle ex', 'pokemon', 'fighting', null, 'star_2', 'B3-088', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_198_EN_SM.webp'),
  ('B3-199', 'B3', 199, 'Zoroark ex', 'pokemon', 'darkness', null, 'star_2', 'B3-106', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_199_EN_SM.webp'),
  ('B3-200', 'B3', 200, 'Corviknight ex', 'pokemon', 'metal', null, 'star_2', 'B3-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_200_EN_SM.webp'),
  ('B3-201', 'B3', 201, 'Flygon ex', 'pokemon', 'dragon', null, 'star_2', 'B3-126', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_201_EN_SM.webp'),
  ('B3-202', 'B3', 202, 'Mega Audino ex', 'pokemon', 'colorless', null, 'star_2', 'B3-141', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_202_EN_SM.webp'),
  ('B3-203', 'B3', 203, 'Sobble', 'pokemon', 'water', null, 'star_3', 'B3-048', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_203_EN_SM.webp'),
  ('B3-204', 'B3', 204, 'Mega Lucario ex', 'pokemon', 'fighting', null, 'star_3', 'B3-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_204_EN_SM.webp'),
  ('B3-205', 'B3', 205, 'Cottonee', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_205_EN_SM.webp'),
  ('B3-206', 'B3', 206, 'Torchic', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_206_EN_SM.webp'),
  ('B3-207', 'B3', 207, 'Combusken', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_207_EN_SM.webp'),
  ('B3-208', 'B3', 208, 'Blaziken', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_208_EN_SM.webp'),
  ('B3-209', 'B3', 209, 'Frillish', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_209_EN_SM.webp'),
  ('B3-210', 'B3', 210, 'Jellicent', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_210_EN_SM.webp'),
  ('B3-211', 'B3', 211, 'Onix', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_211_EN_SM.webp'),
  ('B3-212', 'B3', 212, 'Zubat', 'pokemon', 'darkness', null, 'star_1', 'B3-098', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_212_EN_SM.webp'),
  ('B3-213', 'B3', 213, 'Golbat', 'pokemon', 'darkness', null, 'star_1', 'B3-099', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_213_EN_SM.webp'),
  ('B3-214', 'B3', 214, 'Crobat', 'pokemon', 'darkness', null, 'star_1', 'B3-100', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_214_EN_SM.webp'),
  ('B3-215', 'B3', 215, 'Grimer', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_215_EN_SM.webp'),
  ('B3-216', 'B3', 216, 'Muk', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_216_EN_SM.webp'),
  ('B3-217', 'B3', 217, 'Absol', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_217_EN_SM.webp'),
  ('B3-218', 'B3', 218, 'Skrelp', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_218_EN_SM.webp'),
  ('B3-219', 'B3', 219, 'Steelix', 'pokemon', 'metal', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_219_EN_SM.webp'),
  ('B3-220', 'B3', 220, 'Chansey', 'pokemon', 'colorless', null, 'star_1', 'B3-127', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_220_EN_SM.webp'),
  ('B3-221', 'B3', 221, 'Blissey', 'pokemon', 'colorless', null, 'star_1', 'B3-128', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_221_EN_SM.webp'),
  ('B3-222', 'B3', 222, 'Porygon', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_222_EN_SM.webp'),
  ('B3-223', 'B3', 223, 'Porygon2', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_223_EN_SM.webp'),
  ('B3-224', 'B3', 224, 'Porygon-Z', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_224_EN_SM.webp'),
  ('B3-225', 'B3', 225, 'Whimsicott ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_225_EN_SM.webp'),
  ('B3-226', 'B3', 226, 'Mega Blaziken ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_226_EN_SM.webp'),
  ('B3-227', 'B3', 227, 'Greninja ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_227_EN_SM.webp'),
  ('B3-228', 'B3', 228, 'Jolteon ex', 'pokemon', 'lightning', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_228_EN_SM.webp'),
  ('B3-229', 'B3', 229, 'Hitmonchan ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_229_EN_SM.webp'),
  ('B3-230', 'B3', 230, 'Mega Absol ex', 'pokemon', 'darkness', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_230_EN_SM.webp'),
  ('B3-231', 'B3', 231, 'Dragalge ex', 'pokemon', 'darkness', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_231_EN_SM.webp'),
  ('B3-232', 'B3', 232, 'Mega Steelix ex', 'pokemon', 'metal', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_232_EN_SM.webp'),
  ('B3-233', 'B3', 233, 'Celebi', 'pokemon', 'grass', null, 'crown', 'B3-004', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_233_EN_SM.webp'),
  ('B3-234', 'B3', 234, 'Bombirdier', 'pokemon', 'darkness', null, 'crown', 'B3-115', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_234_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 234 cards, numbered 1 through 234.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'B3';
