-- Ruler of the Skies (B4): 155 main-set cards and 78 secret cards.
-- Source checked 2026-07-30: https://pocket.limitlesstcg.com/cards/B4?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B4-001', 'B4', 1, 'Wurmple', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_001_EN_SM.webp'),
  ('B4-002', 'B4', 2, 'Silcoon', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_002_EN_SM.webp'),
  ('B4-003', 'B4', 3, 'Beautifly', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_003_EN_SM.webp'),
  ('B4-004', 'B4', 4, 'Cascoon', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_004_EN_SM.webp'),
  ('B4-005', 'B4', 5, 'Dustox', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_005_EN_SM.webp'),
  ('B4-006', 'B4', 6, 'Lileep', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_006_EN_SM.webp'),
  ('B4-007', 'B4', 7, 'Cradily', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_007_EN_SM.webp'),
  ('B4-008', 'B4', 8, 'Kricketot', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_008_EN_SM.webp'),
  ('B4-009', 'B4', 9, 'Kricketune', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_009_EN_SM.webp'),
  ('B4-010', 'B4', 10, 'Combee', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_010_EN_SM.webp'),
  ('B4-011', 'B4', 11, 'Vespiquen ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_011_EN_SM.webp'),
  ('B4-012', 'B4', 12, 'Karrablast', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_012_EN_SM.webp'),
  ('B4-013', 'B4', 13, 'Shelmet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_013_EN_SM.webp'),
  ('B4-014', 'B4', 14, 'Accelgor', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_014_EN_SM.webp'),
  ('B4-015', 'B4', 15, 'Dhelmise', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_015_EN_SM.webp'),
  ('B4-016', 'B4', 16, 'Pheromosa', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_016_EN_SM.webp'),
  ('B4-017', 'B4', 17, 'Poltchageist', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_017_EN_SM.webp'),
  ('B4-018', 'B4', 18, 'Sinistcha', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_018_EN_SM.webp'),
  ('B4-019', 'B4', 19, 'Teal MaskOgerpon', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_019_EN_SM.webp'),
  ('B4-020', 'B4', 20, 'Ponyta', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_020_EN_SM.webp'),
  ('B4-021', 'B4', 21, 'Rapidash', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_021_EN_SM.webp'),
  ('B4-022', 'B4', 22, 'Flareon', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_022_EN_SM.webp'),
  ('B4-023', 'B4', 23, 'Moltres', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_023_EN_SM.webp'),
  ('B4-024', 'B4', 24, 'Cyndaquil', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_024_EN_SM.webp'),
  ('B4-025', 'B4', 25, 'Quilava', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_025_EN_SM.webp'),
  ('B4-026', 'B4', 26, 'Typhlosion ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_026_EN_SM.webp'),
  ('B4-027', 'B4', 27, 'Houndour', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_027_EN_SM.webp'),
  ('B4-028', 'B4', 28, 'Houndoom', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_028_EN_SM.webp'),
  ('B4-029', 'B4', 29, 'Heatmor', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_029_EN_SM.webp'),
  ('B4-030', 'B4', 30, 'Psyduck', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_030_EN_SM.webp'),
  ('B4-031', 'B4', 31, 'Golduck', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_031_EN_SM.webp'),
  ('B4-032', 'B4', 32, 'Staryu', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_032_EN_SM.webp'),
  ('B4-033', 'B4', 33, 'Starmie', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_033_EN_SM.webp'),
  ('B4-034', 'B4', 34, 'Carvanha', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_034_EN_SM.webp'),
  ('B4-035', 'B4', 35, 'Mega Sharpedo ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_035_EN_SM.webp'),
  ('B4-036', 'B4', 36, 'Wailmer', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_036_EN_SM.webp'),
  ('B4-037', 'B4', 37, 'Wailord ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_037_EN_SM.webp'),
  ('B4-038', 'B4', 38, 'Spheal', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_038_EN_SM.webp'),
  ('B4-039', 'B4', 39, 'Sealeo', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_039_EN_SM.webp'),
  ('B4-040', 'B4', 40, 'Walrein', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_040_EN_SM.webp'),
  ('B4-041', 'B4', 41, 'Kyogre', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_041_EN_SM.webp'),
  ('B4-042', 'B4', 42, 'Oshawott', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_042_EN_SM.webp'),
  ('B4-043', 'B4', 43, 'Dewott', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_043_EN_SM.webp'),
  ('B4-044', 'B4', 44, 'Samurott', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_044_EN_SM.webp'),
  ('B4-045', 'B4', 45, 'Alomomola', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_045_EN_SM.webp'),
  ('B4-046', 'B4', 46, 'Dewpider', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_046_EN_SM.webp'),
  ('B4-047', 'B4', 47, 'Araquanid', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_047_EN_SM.webp'),
  ('B4-048', 'B4', 48, 'Bruxish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_048_EN_SM.webp'),
  ('B4-049', 'B4', 49, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_049_EN_SM.webp'),
  ('B4-050', 'B4', 50, 'Raichu', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_050_EN_SM.webp'),
  ('B4-051', 'B4', 51, 'Shinx', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_051_EN_SM.webp'),
  ('B4-052', 'B4', 52, 'Luxio', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_052_EN_SM.webp'),
  ('B4-053', 'B4', 53, 'Luxray', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_053_EN_SM.webp'),
  ('B4-054', 'B4', 54, 'Pachirisu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_054_EN_SM.webp'),
  ('B4-055', 'B4', 55, 'Rotom ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_055_EN_SM.webp'),
  ('B4-056', 'B4', 56, 'Tynamo', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_056_EN_SM.webp'),
  ('B4-057', 'B4', 57, 'Eelektrik', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_057_EN_SM.webp'),
  ('B4-058', 'B4', 58, 'Eelektross', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_058_EN_SM.webp'),
  ('B4-059', 'B4', 59, 'Thundurus', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_059_EN_SM.webp'),
  ('B4-060', 'B4', 60, 'Helioptile', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_060_EN_SM.webp'),
  ('B4-061', 'B4', 61, 'Heliolisk', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_061_EN_SM.webp'),
  ('B4-062', 'B4', 62, 'Wattrel', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_062_EN_SM.webp'),
  ('B4-063', 'B4', 63, 'Kilowattrel', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_063_EN_SM.webp'),
  ('B4-064', 'B4', 64, 'Clefairy', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_064_EN_SM.webp'),
  ('B4-065', 'B4', 65, 'Clefable', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_065_EN_SM.webp'),
  ('B4-066', 'B4', 66, 'Drowzee', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_066_EN_SM.webp'),
  ('B4-067', 'B4', 67, 'Hypno', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_067_EN_SM.webp'),
  ('B4-068', 'B4', 68, 'Mime Jr.', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_068_EN_SM.webp'),
  ('B4-069', 'B4', 69, 'Mr. Mime', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_069_EN_SM.webp'),
  ('B4-070', 'B4', 70, 'Mewtwo', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_070_EN_SM.webp'),
  ('B4-071', 'B4', 71, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_071_EN_SM.webp'),
  ('B4-072', 'B4', 72, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_072_EN_SM.webp'),
  ('B4-073', 'B4', 73, 'Chimecho', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_073_EN_SM.webp'),
  ('B4-074', 'B4', 74, 'Wynaut', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_074_EN_SM.webp'),
  ('B4-075', 'B4', 75, 'Woobat', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_075_EN_SM.webp'),
  ('B4-076', 'B4', 76, 'Swoobat', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_076_EN_SM.webp'),
  ('B4-077', 'B4', 77, 'Hoopa', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_077_EN_SM.webp'),
  ('B4-078', 'B4', 78, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_078_EN_SM.webp'),
  ('B4-079', 'B4', 79, 'Makuhita', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_079_EN_SM.webp'),
  ('B4-080', 'B4', 80, 'Hariyama', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_080_EN_SM.webp'),
  ('B4-081', 'B4', 81, 'Anorith', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_081_EN_SM.webp'),
  ('B4-082', 'B4', 82, 'Armaldo', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_082_EN_SM.webp'),
  ('B4-083', 'B4', 83, 'Groudon', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_083_EN_SM.webp'),
  ('B4-084', 'B4', 84, 'Mega Gallade ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_084_EN_SM.webp'),
  ('B4-085', 'B4', 85, 'Drilbur', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_085_EN_SM.webp'),
  ('B4-086', 'B4', 86, 'Excadrill', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_086_EN_SM.webp'),
  ('B4-087', 'B4', 87, 'Timburr', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_087_EN_SM.webp'),
  ('B4-088', 'B4', 88, 'Gurdurr', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_088_EN_SM.webp'),
  ('B4-089', 'B4', 89, 'Conkeldurr', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_089_EN_SM.webp'),
  ('B4-090', 'B4', 90, 'Minior', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_090_EN_SM.webp'),
  ('B4-091', 'B4', 91, 'Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_091_EN_SM.webp'),
  ('B4-092', 'B4', 92, 'Muk', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_092_EN_SM.webp'),
  ('B4-093', 'B4', 93, 'Poochyena', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_093_EN_SM.webp'),
  ('B4-094', 'B4', 94, 'Mightyena', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_094_EN_SM.webp'),
  ('B4-095', 'B4', 95, 'Galarian Zigzagoon', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_095_EN_SM.webp'),
  ('B4-096', 'B4', 96, 'Galarian Linoone', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_096_EN_SM.webp'),
  ('B4-097', 'B4', 97, 'Galarian Obstagoon', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_097_EN_SM.webp'),
  ('B4-098', 'B4', 98, 'Gulpin', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_098_EN_SM.webp'),
  ('B4-099', 'B4', 99, 'Swalot', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_099_EN_SM.webp'),
  ('B4-100', 'B4', 100, 'Absol', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_100_EN_SM.webp'),
  ('B4-101', 'B4', 101, 'Vullaby', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_101_EN_SM.webp'),
  ('B4-102', 'B4', 102, 'Mandibuzz', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_102_EN_SM.webp'),
  ('B4-103', 'B4', 103, 'Hoopa ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_103_EN_SM.webp'),
  ('B4-104', 'B4', 104, 'Skarmory', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_104_EN_SM.webp'),
  ('B4-105', 'B4', 105, 'Mawile', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_105_EN_SM.webp'),
  ('B4-106', 'B4', 106, 'Beldum', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_106_EN_SM.webp'),
  ('B4-107', 'B4', 107, 'Metang', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_107_EN_SM.webp'),
  ('B4-108', 'B4', 108, 'Metagross', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_108_EN_SM.webp'),
  ('B4-109', 'B4', 109, 'Mega Metagross ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_109_EN_SM.webp'),
  ('B4-110', 'B4', 110, 'Escavalier', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_110_EN_SM.webp'),
  ('B4-111', 'B4', 111, 'Genesect', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_111_EN_SM.webp'),
  ('B4-112', 'B4', 112, 'Duraludon', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_112_EN_SM.webp'),
  ('B4-113', 'B4', 113, 'Archaludon', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_113_EN_SM.webp'),
  ('B4-114', 'B4', 114, 'Varoom', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_114_EN_SM.webp'),
  ('B4-115', 'B4', 115, 'Revavroom', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_115_EN_SM.webp'),
  ('B4-116', 'B4', 116, 'Dratini', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_116_EN_SM.webp'),
  ('B4-117', 'B4', 117, 'Dragonair', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_117_EN_SM.webp'),
  ('B4-118', 'B4', 118, 'Dragonite', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_118_EN_SM.webp'),
  ('B4-119', 'B4', 119, 'Rayquaza', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_119_EN_SM.webp'),
  ('B4-120', 'B4', 120, 'Mega Rayquaza ex', 'pokemon', 'dragon', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_120_EN_SM.webp'),
  ('B4-121', 'B4', 121, 'Noibat', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_121_EN_SM.webp'),
  ('B4-122', 'B4', 122, 'Noivern', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_122_EN_SM.webp'),
  ('B4-123', 'B4', 123, 'Turtonator', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_123_EN_SM.webp'),
  ('B4-124', 'B4', 124, 'Drampa', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_124_EN_SM.webp'),
  ('B4-125', 'B4', 125, 'Applin', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_125_EN_SM.webp'),
  ('B4-126', 'B4', 126, 'Dipplin', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_126_EN_SM.webp'),
  ('B4-127', 'B4', 127, 'Hydrapple', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_127_EN_SM.webp'),
  ('B4-128', 'B4', 128, 'Cyclizar', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_128_EN_SM.webp'),
  ('B4-129', 'B4', 129, 'Rattata', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_129_EN_SM.webp'),
  ('B4-130', 'B4', 130, 'Raticate', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_130_EN_SM.webp'),
  ('B4-131', 'B4', 131, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_131_EN_SM.webp'),
  ('B4-132', 'B4', 132, 'Aipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_132_EN_SM.webp'),
  ('B4-133', 'B4', 133, 'Ambipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_133_EN_SM.webp'),
  ('B4-134', 'B4', 134, 'Skitty', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_134_EN_SM.webp'),
  ('B4-135', 'B4', 135, 'Delcatty', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_135_EN_SM.webp'),
  ('B4-136', 'B4', 136, 'Kecleon', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_136_EN_SM.webp'),
  ('B4-137', 'B4', 137, 'Pidove', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_137_EN_SM.webp'),
  ('B4-138', 'B4', 138, 'Tranquill', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_138_EN_SM.webp'),
  ('B4-139', 'B4', 139, 'Unfezant', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_139_EN_SM.webp'),
  ('B4-140', 'B4', 140, 'Ducklett', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_140_EN_SM.webp'),
  ('B4-141', 'B4', 141, 'Swanna ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_141_EN_SM.webp'),
  ('B4-142', 'B4', 142, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_142_EN_SM.webp'),
  ('B4-143', 'B4', 143, 'Type: Null', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_143_EN_SM.webp'),
  ('B4-144', 'B4', 144, 'Silvally', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_144_EN_SM.webp'),
  ('B4-145', 'B4', 145, 'Order Pad', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_145_EN_SM.webp'),
  ('B4-146', 'B4', 146, 'Claw Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_146_EN_SM.webp'),
  ('B4-147', 'B4', 147, 'Root Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_147_EN_SM.webp'),
  ('B4-148', 'B4', 148, 'Deceptive Needle', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_148_EN_SM.webp'),
  ('B4-149', 'B4', 149, 'Clear Veil', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_149_EN_SM.webp'),
  ('B4-150', 'B4', 150, 'Psychic', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_150_EN_SM.webp'),
  ('B4-151', 'B4', 151, 'Drayden', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_151_EN_SM.webp'),
  ('B4-152', 'B4', 152, 'Skyla', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_152_EN_SM.webp'),
  ('B4-153', 'B4', 153, 'Wally', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_153_EN_SM.webp'),
  ('B4-154', 'B4', 154, 'Soothing Shore', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_154_EN_SM.webp'),
  ('B4-155', 'B4', 155, 'Rainbow Cave', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_155_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B4-156', 'B4', 156, 'Wurmple', 'pokemon', 'grass', null, 'star_1', 'B4-001', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_156_EN_SM.webp'),
  ('B4-157', 'B4', 157, 'Lileep', 'pokemon', 'grass', null, 'star_1', 'B4-006', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_157_EN_SM.webp'),
  ('B4-158', 'B4', 158, 'Kricketune', 'pokemon', 'grass', null, 'star_1', 'B4-009', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_158_EN_SM.webp'),
  ('B4-159', 'B4', 159, 'Accelgor', 'pokemon', 'grass', null, 'star_1', 'B4-014', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_159_EN_SM.webp'),
  ('B4-160', 'B4', 160, 'Ponyta', 'pokemon', 'fire', null, 'star_1', 'B4-020', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_160_EN_SM.webp'),
  ('B4-161', 'B4', 161, 'Quilava', 'pokemon', 'fire', null, 'star_1', 'B4-025', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_161_EN_SM.webp'),
  ('B4-162', 'B4', 162, 'Kyogre', 'pokemon', 'water', null, 'star_1', 'B4-041', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_162_EN_SM.webp'),
  ('B4-163', 'B4', 163, 'Samurott', 'pokemon', 'water', null, 'star_1', 'B4-044', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_163_EN_SM.webp'),
  ('B4-164', 'B4', 164, 'Raichu', 'pokemon', 'lightning', null, 'star_1', 'B4-050', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_164_EN_SM.webp'),
  ('B4-165', 'B4', 165, 'Wattrel', 'pokemon', 'lightning', null, 'star_1', 'B4-062', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_165_EN_SM.webp'),
  ('B4-166', 'B4', 166, 'Clefairy', 'pokemon', 'psychic', null, 'star_1', 'B4-064', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_166_EN_SM.webp'),
  ('B4-167', 'B4', 167, 'Ralts', 'pokemon', 'psychic', null, 'star_1', 'B4-071', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_167_EN_SM.webp'),
  ('B4-168', 'B4', 168, 'Wynaut', 'pokemon', 'psychic', null, 'star_1', 'B4-074', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_168_EN_SM.webp'),
  ('B4-169', 'B4', 169, 'Oricorio', 'pokemon', 'psychic', null, 'star_1', 'B4-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_169_EN_SM.webp'),
  ('B4-170', 'B4', 170, 'Anorith', 'pokemon', 'fighting', null, 'star_1', 'B4-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_170_EN_SM.webp'),
  ('B4-171', 'B4', 171, 'Poochyena', 'pokemon', 'darkness', null, 'star_1', 'B4-093', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_171_EN_SM.webp'),
  ('B4-172', 'B4', 172, 'Gulpin', 'pokemon', 'darkness', null, 'star_1', 'B4-098', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_172_EN_SM.webp'),
  ('B4-173', 'B4', 173, 'Vullaby', 'pokemon', 'darkness', null, 'star_1', 'B4-101', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_173_EN_SM.webp'),
  ('B4-174', 'B4', 174, 'Genesect', 'pokemon', 'metal', null, 'star_1', 'B4-111', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_174_EN_SM.webp'),
  ('B4-175', 'B4', 175, 'Dragonair', 'pokemon', 'dragon', null, 'star_1', 'B4-117', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_175_EN_SM.webp'),
  ('B4-176', 'B4', 176, 'Noivern', 'pokemon', 'dragon', null, 'star_1', 'B4-122', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_176_EN_SM.webp'),
  ('B4-177', 'B4', 177, 'Cyclizar', 'pokemon', 'dragon', null, 'star_1', 'B4-128', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_177_EN_SM.webp'),
  ('B4-178', 'B4', 178, 'Raticate', 'pokemon', 'colorless', null, 'star_1', 'B4-130', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_178_EN_SM.webp'),
  ('B4-179', 'B4', 179, 'Aipom', 'pokemon', 'colorless', null, 'star_1', 'B4-132', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_179_EN_SM.webp'),
  ('B4-180', 'B4', 180, 'Vespiquen ex', 'pokemon', 'grass', null, 'star_2', 'B4-011', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_180_EN_SM.webp'),
  ('B4-181', 'B4', 181, 'Typhlosion ex', 'pokemon', 'fire', null, 'star_2', 'B4-026', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_181_EN_SM.webp'),
  ('B4-182', 'B4', 182, 'Mega Sharpedo ex', 'pokemon', 'water', null, 'star_2', 'B4-035', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_182_EN_SM.webp'),
  ('B4-183', 'B4', 183, 'Wailord ex', 'pokemon', 'water', null, 'star_2', 'B4-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_183_EN_SM.webp'),
  ('B4-184', 'B4', 184, 'Rotom ex', 'pokemon', 'lightning', null, 'star_2', 'B4-055', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_184_EN_SM.webp'),
  ('B4-185', 'B4', 185, 'Mega Gallade ex', 'pokemon', 'fighting', null, 'star_2', 'B4-084', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_185_EN_SM.webp'),
  ('B4-186', 'B4', 186, 'Hoopa ex', 'pokemon', 'darkness', null, 'star_2', 'B4-103', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_186_EN_SM.webp'),
  ('B4-187', 'B4', 187, 'Mega Metagross ex', 'pokemon', 'metal', null, 'star_2', 'B4-109', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_187_EN_SM.webp'),
  ('B4-188', 'B4', 188, 'Mega Rayquaza ex', 'pokemon', 'dragon', null, 'star_2', 'B4-120', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_188_EN_SM.webp'),
  ('B4-189', 'B4', 189, 'Swanna ex', 'pokemon', 'colorless', null, 'star_2', 'B4-141', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_189_EN_SM.webp'),
  ('B4-190', 'B4', 190, 'Psychic', 'trainer', null, 'supporter', 'star_2', 'B4-150', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_190_EN_SM.webp'),
  ('B4-191', 'B4', 191, 'Drayden', 'trainer', null, 'supporter', 'star_2', 'B4-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_191_EN_SM.webp'),
  ('B4-192', 'B4', 192, 'Skyla', 'trainer', null, 'supporter', 'star_2', 'B4-152', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_192_EN_SM.webp'),
  ('B4-193', 'B4', 193, 'Wally', 'trainer', null, 'supporter', 'star_2', 'B4-153', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_193_EN_SM.webp'),
  ('B4-194', 'B4', 194, 'Vespiquen ex', 'pokemon', 'grass', null, 'star_2', 'B4-011', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_194_EN_SM.webp'),
  ('B4-195', 'B4', 195, 'Typhlosion ex', 'pokemon', 'fire', null, 'star_2', 'B4-026', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_195_EN_SM.webp'),
  ('B4-196', 'B4', 196, 'Mega Sharpedo ex', 'pokemon', 'water', null, 'star_2', 'B4-035', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_196_EN_SM.webp'),
  ('B4-197', 'B4', 197, 'Wailord ex', 'pokemon', 'water', null, 'star_2', 'B4-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_197_EN_SM.webp'),
  ('B4-198', 'B4', 198, 'Mega Gallade ex', 'pokemon', 'fighting', null, 'star_2', 'B4-084', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_198_EN_SM.webp'),
  ('B4-199', 'B4', 199, 'Hoopa ex', 'pokemon', 'darkness', null, 'star_2', 'B4-103', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_199_EN_SM.webp'),
  ('B4-200', 'B4', 200, 'Mega Metagross ex', 'pokemon', 'metal', null, 'star_2', 'B4-109', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_200_EN_SM.webp'),
  ('B4-201', 'B4', 201, 'Swanna ex', 'pokemon', 'colorless', null, 'star_2', 'B4-141', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_201_EN_SM.webp'),
  ('B4-202', 'B4', 202, 'Rotom ex', 'pokemon', 'lightning', null, 'star_3', 'B4-055', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_202_EN_SM.webp'),
  ('B4-203', 'B4', 203, 'Mega Rayquaza ex', 'pokemon', 'dragon', null, 'star_3', 'B4-120', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_203_EN_SM.webp'),
  ('B4-204', 'B4', 204, 'Alolan Vulpix', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_204_EN_SM.webp'),
  ('B4-205', 'B4', 205, 'Mudkip', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_205_EN_SM.webp'),
  ('B4-206', 'B4', 206, 'Marshtomp', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_206_EN_SM.webp'),
  ('B4-207', 'B4', 207, 'Swampert', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_207_EN_SM.webp'),
  ('B4-208', 'B4', 208, 'Electabuzz', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_208_EN_SM.webp'),
  ('B4-209', 'B4', 209, 'Plusle', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_209_EN_SM.webp'),
  ('B4-210', 'B4', 210, 'Minun', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_210_EN_SM.webp'),
  ('B4-211', 'B4', 211, 'Mr. Mime', 'pokemon', 'psychic', null, 'star_1', 'B4-069', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_211_EN_SM.webp'),
  ('B4-212', 'B4', 212, 'Mewtwo', 'pokemon', 'psychic', null, 'star_1', 'B4-070', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_212_EN_SM.webp'),
  ('B4-213', 'B4', 213, 'Roggenrola', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_213_EN_SM.webp'),
  ('B4-214', 'B4', 214, 'Boldore', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_214_EN_SM.webp'),
  ('B4-215', 'B4', 215, 'Falinks', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_215_EN_SM.webp'),
  ('B4-216', 'B4', 216, 'Koffing', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_216_EN_SM.webp'),
  ('B4-217', 'B4', 217, 'Weezing', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_217_EN_SM.webp'),
  ('B4-218', 'B4', 218, 'Galarian Meowth', 'pokemon', 'metal', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_218_EN_SM.webp'),
  ('B4-219', 'B4', 219, 'Galarian Perrserker', 'pokemon', 'metal', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_219_EN_SM.webp'),
  ('B4-220', 'B4', 220, 'Rattata', 'pokemon', 'colorless', null, 'star_1', 'B4-129', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_220_EN_SM.webp'),
  ('B4-221', 'B4', 221, 'Raticate', 'pokemon', 'colorless', null, 'star_1', 'B4-130', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_221_EN_SM.webp'),
  ('B4-222', 'B4', 222, 'Smeargle', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_222_EN_SM.webp'),
  ('B4-223', 'B4', 223, 'Buneary', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_223_EN_SM.webp'),
  ('B4-224', 'B4', 224, 'Blacephalon ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_224_EN_SM.webp'),
  ('B4-225', 'B4', 225, 'Alolan Ninetales ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_225_EN_SM.webp'),
  ('B4-226', 'B4', 226, 'Mega Swampert ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_226_EN_SM.webp'),
  ('B4-227', 'B4', 227, 'Mega Gardevoir ex', 'pokemon', 'psychic', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_227_EN_SM.webp'),
  ('B4-228', 'B4', 228, 'Mega Lopunny ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_228_EN_SM.webp'),
  ('B4-229', 'B4', 229, 'Gigalith ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_229_EN_SM.webp'),
  ('B4-230', 'B4', 230, 'Zoroark ex', 'pokemon', 'darkness', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_230_EN_SM.webp'),
  ('B4-231', 'B4', 231, 'Mega Kangaskhan ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_231_EN_SM.webp'),
  ('B4-232', 'B4', 232, 'Raichu', 'pokemon', 'lightning', null, 'crown', 'B4-050', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_232_EN_SM.webp'),
  ('B4-233', 'B4', 233, 'Dragonair', 'pokemon', 'dragon', null, 'crown', 'B4-117', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_233_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 233 cards, numbered 1 through 233.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'B4';
