-- Fantastical Parade (B2): 155 main-set cards and 79 secret cards.
-- Source checked 2026-06-25: https://pocket.limitlesstcg.com/cards/B2?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B2-001', 'B2', 1, 'Ledyba', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_001_EN_SM.webp'),
  ('B2-002', 'B2', 2, 'Ledian', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_002_EN_SM.webp'),
  ('B2-003', 'B2', 3, 'Shuckle', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_003_EN_SM.webp'),
  ('B2-004', 'B2', 4, 'Roselia', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_004_EN_SM.webp'),
  ('B2-005', 'B2', 5, 'Roserade', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_005_EN_SM.webp'),
  ('B2-006', 'B2', 6, 'Cacnea', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_006_EN_SM.webp'),
  ('B2-007', 'B2', 7, 'Cacturne', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_007_EN_SM.webp'),
  ('B2-008', 'B2', 8, 'Chespin', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_008_EN_SM.webp'),
  ('B2-009', 'B2', 9, 'Quilladin', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_009_EN_SM.webp'),
  ('B2-010', 'B2', 10, 'Chesnaught', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_010_EN_SM.webp'),
  ('B2-011', 'B2', 11, 'Scatterbug', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_011_EN_SM.webp'),
  ('B2-012', 'B2', 12, 'Spewpa', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_012_EN_SM.webp'),
  ('B2-013', 'B2', 13, 'Vivillon', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_013_EN_SM.webp'),
  ('B2-014', 'B2', 14, 'Buzzwole', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_014_EN_SM.webp'),
  ('B2-015', 'B2', 15, 'Gossifleur', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_015_EN_SM.webp'),
  ('B2-016', 'B2', 16, 'Eldegoss', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_016_EN_SM.webp'),
  ('B2-017', 'B2', 17, 'Teal Mask Ogerpon ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_017_EN_SM.webp'),
  ('B2-018', 'B2', 18, 'Alolan Marowak', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_018_EN_SM.webp'),
  ('B2-019', 'B2', 19, 'Reshiram', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_019_EN_SM.webp'),
  ('B2-020', 'B2', 20, 'Litleo', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_020_EN_SM.webp'),
  ('B2-021', 'B2', 21, 'Pyroar', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_021_EN_SM.webp'),
  ('B2-022', 'B2', 22, 'Oricorio', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_022_EN_SM.webp'),
  ('B2-023', 'B2', 23, 'Blacephalon ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_023_EN_SM.webp'),
  ('B2-024', 'B2', 24, 'Scorbunny', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_024_EN_SM.webp'),
  ('B2-025', 'B2', 25, 'Raboot', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_025_EN_SM.webp'),
  ('B2-026', 'B2', 26, 'Cinderace', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_026_EN_SM.webp'),
  ('B2-027', 'B2', 27, 'Hearthflame Mask Ogerpon', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_027_EN_SM.webp'),
  ('B2-028', 'B2', 28, 'Alolan Vulpix', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_028_EN_SM.webp'),
  ('B2-029', 'B2', 29, 'Alolan Ninetales ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_029_EN_SM.webp'),
  ('B2-030', 'B2', 30, 'Galarian Mr. Mime', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_030_EN_SM.webp'),
  ('B2-031', 'B2', 31, 'Galarian Mr. Rime', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_031_EN_SM.webp'),
  ('B2-032', 'B2', 32, 'Delibird', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_032_EN_SM.webp'),
  ('B2-033', 'B2', 33, 'Mudkip', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_033_EN_SM.webp'),
  ('B2-034', 'B2', 34, 'Marshtomp', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_034_EN_SM.webp'),
  ('B2-035', 'B2', 35, 'Swampert', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_035_EN_SM.webp'),
  ('B2-036', 'B2', 36, 'Mega Swampert ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_036_EN_SM.webp'),
  ('B2-037', 'B2', 37, 'Vanillite', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_037_EN_SM.webp'),
  ('B2-038', 'B2', 38, 'Vanillish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_038_EN_SM.webp'),
  ('B2-039', 'B2', 39, 'Vanilluxe', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_039_EN_SM.webp'),
  ('B2-040', 'B2', 40, 'Cryogonal', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_040_EN_SM.webp'),
  ('B2-041', 'B2', 41, 'Amaura', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_041_EN_SM.webp'),
  ('B2-042', 'B2', 42, 'Aurorus', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_042_EN_SM.webp'),
  ('B2-043', 'B2', 43, 'Chewtle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_043_EN_SM.webp'),
  ('B2-044', 'B2', 44, 'Drednaw', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_044_EN_SM.webp'),
  ('B2-045', 'B2', 45, 'Cramorant', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_045_EN_SM.webp'),
  ('B2-046', 'B2', 46, 'Arrokuda', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_046_EN_SM.webp'),
  ('B2-047', 'B2', 47, 'Barraskewda', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_047_EN_SM.webp'),
  ('B2-048', 'B2', 48, 'Wellspring Mask Ogerpon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_048_EN_SM.webp'),
  ('B2-049', 'B2', 49, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_049_EN_SM.webp'),
  ('B2-050', 'B2', 50, 'Alolan Raichu', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_050_EN_SM.webp'),
  ('B2-051', 'B2', 51, 'Zapdos', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_051_EN_SM.webp'),
  ('B2-052', 'B2', 52, 'Plusle', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_052_EN_SM.webp'),
  ('B2-053', 'B2', 53, 'Minun', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_053_EN_SM.webp'),
  ('B2-054', 'B2', 54, 'Toxel', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_054_EN_SM.webp'),
  ('B2-055', 'B2', 55, 'Toxtricity ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_055_EN_SM.webp'),
  ('B2-056', 'B2', 56, 'Tadbulb', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_056_EN_SM.webp'),
  ('B2-057', 'B2', 57, 'Bellibolt', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_057_EN_SM.webp'),
  ('B2-058', 'B2', 58, 'Galarian Ponyta', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_058_EN_SM.webp'),
  ('B2-059', 'B2', 59, 'Galarian Rapidash', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_059_EN_SM.webp'),
  ('B2-060', 'B2', 60, 'Wobbuffet', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_060_EN_SM.webp'),
  ('B2-061', 'B2', 61, 'Snubbull', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_061_EN_SM.webp'),
  ('B2-062', 'B2', 62, 'Granbull', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_062_EN_SM.webp'),
  ('B2-063', 'B2', 63, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_063_EN_SM.webp'),
  ('B2-064', 'B2', 64, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_064_EN_SM.webp'),
  ('B2-065', 'B2', 65, 'Gardevoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_065_EN_SM.webp'),
  ('B2-066', 'B2', 66, 'Mega Gardevoir ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_066_EN_SM.webp'),
  ('B2-067', 'B2', 67, 'Litwick', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_067_EN_SM.webp'),
  ('B2-068', 'B2', 68, 'Lampent', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_068_EN_SM.webp'),
  ('B2-069', 'B2', 69, 'Chandelure', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_069_EN_SM.webp'),
  ('B2-070', 'B2', 70, 'Meloetta', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_070_EN_SM.webp'),
  ('B2-071', 'B2', 71, 'Pumpkaboo', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_071_EN_SM.webp'),
  ('B2-072', 'B2', 72, 'Gourgeist', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_072_EN_SM.webp'),
  ('B2-073', 'B2', 73, 'Mimikyu ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_073_EN_SM.webp'),
  ('B2-074', 'B2', 74, 'Sinistea', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_074_EN_SM.webp'),
  ('B2-075', 'B2', 75, 'Polteageist', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_075_EN_SM.webp'),
  ('B2-076', 'B2', 76, 'Indeedee', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_076_EN_SM.webp'),
  ('B2-077', 'B2', 77, 'Sandshrew', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_077_EN_SM.webp'),
  ('B2-078', 'B2', 78, 'Sandslash', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_078_EN_SM.webp'),
  ('B2-079', 'B2', 79, 'Machop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_079_EN_SM.webp'),
  ('B2-080', 'B2', 80, 'Machoke', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_080_EN_SM.webp'),
  ('B2-081', 'B2', 81, 'Machamp', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_081_EN_SM.webp'),
  ('B2-082', 'B2', 82, 'Cubone', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_082_EN_SM.webp'),
  ('B2-083', 'B2', 83, 'Meditite', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_083_EN_SM.webp'),
  ('B2-084', 'B2', 84, 'Medicham', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_084_EN_SM.webp'),
  ('B2-085', 'B2', 85, 'Roggenrola', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_085_EN_SM.webp'),
  ('B2-086', 'B2', 86, 'Boldore', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_086_EN_SM.webp'),
  ('B2-087', 'B2', 87, 'Gigalith ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_087_EN_SM.webp'),
  ('B2-088', 'B2', 88, 'Drilbur', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_088_EN_SM.webp'),
  ('B2-089', 'B2', 89, 'Tyrunt', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_089_EN_SM.webp'),
  ('B2-090', 'B2', 90, 'Tyrantrum', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_090_EN_SM.webp'),
  ('B2-091', 'B2', 91, 'Passimian', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_091_EN_SM.webp'),
  ('B2-092', 'B2', 92, 'Falinks', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_092_EN_SM.webp'),
  ('B2-093', 'B2', 93, 'Cornerstone Mask Ogerpon', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_093_EN_SM.webp'),
  ('B2-094', 'B2', 94, 'Alolan Meowth', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_094_EN_SM.webp'),
  ('B2-095', 'B2', 95, 'Alolan Persian', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_095_EN_SM.webp'),
  ('B2-096', 'B2', 96, 'Alolan Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_096_EN_SM.webp'),
  ('B2-097', 'B2', 97, 'Alolan Muk', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_097_EN_SM.webp'),
  ('B2-098', 'B2', 98, 'Galarian Zigzagoon', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_098_EN_SM.webp'),
  ('B2-099', 'B2', 99, 'Galarian Linoone', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_099_EN_SM.webp'),
  ('B2-100', 'B2', 100, 'Galarian Obstagoon', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_100_EN_SM.webp'),
  ('B2-101', 'B2', 101, 'Stunky', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_101_EN_SM.webp'),
  ('B2-102', 'B2', 102, 'Skuntank', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_102_EN_SM.webp'),
  ('B2-103', 'B2', 103, 'Spiritomb', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_103_EN_SM.webp'),
  ('B2-104', 'B2', 104, 'Purrloin', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_104_EN_SM.webp'),
  ('B2-105', 'B2', 105, 'Liepard', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_105_EN_SM.webp'),
  ('B2-106', 'B2', 106, 'Scraggy', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_106_EN_SM.webp'),
  ('B2-107', 'B2', 107, 'Scrafty', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_107_EN_SM.webp'),
  ('B2-108', 'B2', 108, 'Yveltal', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_108_EN_SM.webp'),
  ('B2-109', 'B2', 109, 'Guzzlord', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_109_EN_SM.webp'),
  ('B2-110', 'B2', 110, 'Galarian Meowth', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_110_EN_SM.webp'),
  ('B2-111', 'B2', 111, 'Galarian Perrserker', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_111_EN_SM.webp'),
  ('B2-112', 'B2', 112, 'Mawile', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_112_EN_SM.webp'),
  ('B2-113', 'B2', 113, 'Mega Mawile ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_113_EN_SM.webp'),
  ('B2-114', 'B2', 114, 'Excadrill', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_114_EN_SM.webp'),
  ('B2-115', 'B2', 115, 'Ferroseed', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_115_EN_SM.webp'),
  ('B2-116', 'B2', 116, 'Ferrothorn', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_116_EN_SM.webp'),
  ('B2-117', 'B2', 117, 'Galarian Stunfisk', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_117_EN_SM.webp'),
  ('B2-118', 'B2', 118, 'Honedge', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_118_EN_SM.webp'),
  ('B2-119', 'B2', 119, 'Doublade', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_119_EN_SM.webp'),
  ('B2-120', 'B2', 120, 'Aegislash', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_120_EN_SM.webp'),
  ('B2-121', 'B2', 121, 'Bagon', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_121_EN_SM.webp'),
  ('B2-122', 'B2', 122, 'Shelgon', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_122_EN_SM.webp'),
  ('B2-123', 'B2', 123, 'Salamence', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_123_EN_SM.webp'),
  ('B2-124', 'B2', 124, 'Meowth', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_124_EN_SM.webp'),
  ('B2-125', 'B2', 125, 'Persian', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_125_EN_SM.webp'),
  ('B2-126', 'B2', 126, 'Kangaskhan', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_126_EN_SM.webp'),
  ('B2-127', 'B2', 127, 'Mega Kangaskhan ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_127_EN_SM.webp'),
  ('B2-128', 'B2', 128, 'Sentret', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_128_EN_SM.webp'),
  ('B2-129', 'B2', 129, 'Furret', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_129_EN_SM.webp'),
  ('B2-130', 'B2', 130, 'Smeargle', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_130_EN_SM.webp'),
  ('B2-131', 'B2', 131, 'Lugia', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_131_EN_SM.webp'),
  ('B2-132', 'B2', 132, 'Taillow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_132_EN_SM.webp'),
  ('B2-133', 'B2', 133, 'Swellow', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_133_EN_SM.webp'),
  ('B2-134', 'B2', 134, 'Slakoth', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_134_EN_SM.webp'),
  ('B2-135', 'B2', 135, 'Vigoroth', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_135_EN_SM.webp'),
  ('B2-136', 'B2', 136, 'Slaking', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_136_EN_SM.webp'),
  ('B2-137', 'B2', 137, 'Spinda', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_137_EN_SM.webp'),
  ('B2-138', 'B2', 138, 'Tornadus', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_138_EN_SM.webp'),
  ('B2-139', 'B2', 139, 'Bunnelby', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_139_EN_SM.webp'),
  ('B2-140', 'B2', 140, 'Diggersby', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_140_EN_SM.webp'),
  ('B2-141', 'B2', 141, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_141_EN_SM.webp'),
  ('B2-142', 'B2', 142, 'Tandemaus', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_142_EN_SM.webp'),
  ('B2-143', 'B2', 143, 'Maushold', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_143_EN_SM.webp'),
  ('B2-144', 'B2', 144, 'Jaw Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_144_EN_SM.webp'),
  ('B2-145', 'B2', 145, 'Lucky Ice Pop', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_145_EN_SM.webp'),
  ('B2-146', 'B2', 146, 'Sail Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_146_EN_SM.webp'),
  ('B2-147', 'B2', 147, 'Protective Poncho', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_147_EN_SM.webp'),
  ('B2-148', 'B2', 148, 'Metal Core Barrier', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_148_EN_SM.webp'),
  ('B2-149', 'B2', 149, 'Diantha', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_149_EN_SM.webp'),
  ('B2-150', 'B2', 150, 'Sightseer', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_150_EN_SM.webp'),
  ('B2-151', 'B2', 151, 'Juggler', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_151_EN_SM.webp'),
  ('B2-152', 'B2', 152, 'Piers', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_152_EN_SM.webp'),
  ('B2-153', 'B2', 153, 'Training Area', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_153_EN_SM.webp'),
  ('B2-154', 'B2', 154, 'Starting Plains', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_154_EN_SM.webp'),
  ('B2-155', 'B2', 155, 'Peculiar Plaza', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_155_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B2-156', 'B2', 156, 'Cacnea', 'pokemon', 'grass', null, 'star_1', 'B2-006', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_156_EN_SM.webp'),
  ('B2-157', 'B2', 157, 'Roserade', 'pokemon', 'grass', null, 'star_1', 'B2-005', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_157_EN_SM.webp'),
  ('B2-158', 'B2', 158, 'Vivillon', 'pokemon', 'grass', null, 'star_1', 'B2-013', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_158_EN_SM.webp'),
  ('B2-159', 'B2', 159, 'Buzzwole', 'pokemon', 'grass', null, 'star_1', 'B2-014', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_159_EN_SM.webp'),
  ('B2-160', 'B2', 160, 'Reshiram', 'pokemon', 'fire', null, 'star_1', 'B2-019', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_160_EN_SM.webp'),
  ('B2-161', 'B2', 161, 'Oricorio', 'pokemon', 'fire', null, 'star_1', 'B2-022', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_161_EN_SM.webp'),
  ('B2-162', 'B2', 162, 'Scorbunny', 'pokemon', 'fire', null, 'star_1', 'B2-024', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_162_EN_SM.webp'),
  ('B2-163', 'B2', 163, 'Aurorus', 'pokemon', 'water', null, 'star_1', 'B2-042', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_163_EN_SM.webp'),
  ('B2-164', 'B2', 164, 'Cramorant', 'pokemon', 'water', null, 'star_1', 'B2-045', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_164_EN_SM.webp'),
  ('B2-165', 'B2', 165, 'Minun', 'pokemon', 'lightning', null, 'star_1', 'B2-053', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_165_EN_SM.webp'),
  ('B2-166', 'B2', 166, 'Toxel', 'pokemon', 'lightning', null, 'star_1', 'B2-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_166_EN_SM.webp'),
  ('B2-167', 'B2', 167, 'Galarian Ponyta', 'pokemon', 'psychic', null, 'star_1', 'B2-058', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_167_EN_SM.webp'),
  ('B2-168', 'B2', 168, 'Snubbull', 'pokemon', 'psychic', null, 'star_1', 'B2-061', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_168_EN_SM.webp'),
  ('B2-169', 'B2', 169, 'Indeedee', 'pokemon', 'psychic', null, 'star_1', 'B2-076', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_169_EN_SM.webp'),
  ('B2-170', 'B2', 170, 'Sandshrew', 'pokemon', 'fighting', null, 'star_1', 'B2-077', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_170_EN_SM.webp'),
  ('B2-171', 'B2', 171, 'Tyrantrum', 'pokemon', 'fighting', null, 'star_1', 'B2-090', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_171_EN_SM.webp'),
  ('B2-172', 'B2', 172, 'Falinks', 'pokemon', 'fighting', null, 'star_1', 'B2-092', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_172_EN_SM.webp'),
  ('B2-173', 'B2', 173, 'Alolan Muk', 'pokemon', 'darkness', null, 'star_1', 'B2-097', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_173_EN_SM.webp'),
  ('B2-174', 'B2', 174, 'Purrloin', 'pokemon', 'darkness', null, 'star_1', 'B2-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_174_EN_SM.webp'),
  ('B2-175', 'B2', 175, 'Yveltal', 'pokemon', 'darkness', null, 'star_1', 'B2-108', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_175_EN_SM.webp'),
  ('B2-176', 'B2', 176, 'Galarian Obstagoon', 'pokemon', 'darkness', null, 'star_1', 'B2-100', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_176_EN_SM.webp'),
  ('B2-177', 'B2', 177, 'Galarian Perrserker', 'pokemon', 'metal', null, 'star_1', 'B2-111', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_177_EN_SM.webp'),
  ('B2-178', 'B2', 178, 'Salamence', 'pokemon', 'dragon', null, 'star_1', 'B2-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_178_EN_SM.webp'),
  ('B2-179', 'B2', 179, 'Slakoth', 'pokemon', 'colorless', null, 'star_1', 'B2-134', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_179_EN_SM.webp'),
  ('B2-180', 'B2', 180, 'Teal Mask Ogerpon ex', 'pokemon', 'grass', null, 'star_2', 'B2-017', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_180_EN_SM.webp'),
  ('B2-181', 'B2', 181, 'Blacephalon ex', 'pokemon', 'fire', null, 'star_2', 'B2-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_181_EN_SM.webp'),
  ('B2-182', 'B2', 182, 'Alolan Ninetales ex', 'pokemon', 'water', null, 'star_2', 'B2-029', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_182_EN_SM.webp'),
  ('B2-183', 'B2', 183, 'Mega Swampert ex', 'pokemon', 'water', null, 'star_2', 'B2-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_183_EN_SM.webp'),
  ('B2-184', 'B2', 184, 'Toxtricity ex', 'pokemon', 'lightning', null, 'star_2', 'B2-055', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_184_EN_SM.webp'),
  ('B2-185', 'B2', 185, 'Mega Gardevoir ex', 'pokemon', 'psychic', null, 'star_2', 'B2-066', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_185_EN_SM.webp'),
  ('B2-186', 'B2', 186, 'Mimikyu ex', 'pokemon', 'psychic', null, 'star_2', 'B2-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_186_EN_SM.webp'),
  ('B2-187', 'B2', 187, 'Gigalith ex', 'pokemon', 'fighting', null, 'star_2', 'B2-087', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_187_EN_SM.webp'),
  ('B2-188', 'B2', 188, 'Mega Mawile ex', 'pokemon', 'metal', null, 'star_2', 'B2-113', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_188_EN_SM.webp'),
  ('B2-189', 'B2', 189, 'Mega Kangaskhan ex', 'pokemon', 'colorless', null, 'star_2', 'B2-127', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_189_EN_SM.webp'),
  ('B2-190', 'B2', 190, 'Diantha', 'trainer', null, 'supporter', 'star_2', 'B2-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_190_EN_SM.webp'),
  ('B2-191', 'B2', 191, 'Sightseer', 'trainer', null, 'supporter', 'star_2', 'B2-150', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_191_EN_SM.webp'),
  ('B2-192', 'B2', 192, 'Juggler', 'trainer', null, 'supporter', 'star_2', 'B2-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_192_EN_SM.webp'),
  ('B2-193', 'B2', 193, 'Piers', 'trainer', null, 'supporter', 'star_2', 'B2-152', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_193_EN_SM.webp'),
  ('B2-194', 'B2', 194, 'Teal Mask Ogerpon ex', 'pokemon', 'grass', null, 'star_2', 'B2-017', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_194_EN_SM.webp'),
  ('B2-195', 'B2', 195, 'Blacephalon ex', 'pokemon', 'fire', null, 'star_2', 'B2-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_195_EN_SM.webp'),
  ('B2-196', 'B2', 196, 'Alolan Ninetales ex', 'pokemon', 'water', null, 'star_2', 'B2-029', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_196_EN_SM.webp'),
  ('B2-197', 'B2', 197, 'Mega Swampert ex', 'pokemon', 'water', null, 'star_2', 'B2-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_197_EN_SM.webp'),
  ('B2-198', 'B2', 198, 'Toxtricity ex', 'pokemon', 'lightning', null, 'star_2', 'B2-055', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_198_EN_SM.webp'),
  ('B2-199', 'B2', 199, 'Mimikyu ex', 'pokemon', 'psychic', null, 'star_2', 'B2-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_199_EN_SM.webp'),
  ('B2-200', 'B2', 200, 'Gigalith ex', 'pokemon', 'fighting', null, 'star_2', 'B2-087', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_200_EN_SM.webp'),
  ('B2-201', 'B2', 201, 'Mega Mawile ex', 'pokemon', 'metal', null, 'star_2', 'B2-113', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_201_EN_SM.webp'),
  ('B2-202', 'B2', 202, 'Mega Kangaskhan ex', 'pokemon', 'colorless', null, 'star_2', 'B2-127', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_202_EN_SM.webp'),
  ('B2-203', 'B2', 203, 'Mega Gardevoir ex', 'pokemon', 'psychic', null, 'star_3', 'B2-066', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_203_EN_SM.webp'),
  ('B2-204', 'B2', 204, 'Meowth', 'pokemon', 'colorless', null, 'star_3', 'B2-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_204_EN_SM.webp'),
  ('B2-205', 'B2', 205, 'Tangela', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_205_EN_SM.webp'),
  ('B2-206', 'B2', 206, 'Magby', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_206_EN_SM.webp'),
  ('B2-207', 'B2', 207, 'Magmar', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_207_EN_SM.webp'),
  ('B2-208', 'B2', 208, 'Horsea', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_208_EN_SM.webp'),
  ('B2-209', 'B2', 209, 'Seadra', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_209_EN_SM.webp'),
  ('B2-210', 'B2', 210, 'Mantyke', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_210_EN_SM.webp'),
  ('B2-211', 'B2', 211, 'Omanyte', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_211_EN_SM.webp'),
  ('B2-212', 'B2', 212, 'Omastar', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_212_EN_SM.webp'),
  ('B2-213', 'B2', 213, 'Pichu', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_213_EN_SM.webp'),
  ('B2-214', 'B2', 214, 'Clefairy', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_214_EN_SM.webp'),
  ('B2-215', 'B2', 215, 'Clefable', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_215_EN_SM.webp'),
  ('B2-216', 'B2', 216, 'Latias', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_216_EN_SM.webp'),
  ('B2-217', 'B2', 217, 'Latios', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_217_EN_SM.webp'),
  ('B2-218', 'B2', 218, 'Hitmonlee', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_218_EN_SM.webp'),
  ('B2-219', 'B2', 219, 'Hitmonchan', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_219_EN_SM.webp'),
  ('B2-220', 'B2', 220, 'Kabuto', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_220_EN_SM.webp'),
  ('B2-221', 'B2', 221, 'Kabutops', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_221_EN_SM.webp'),
  ('B2-222', 'B2', 222, 'Phanpy', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_222_EN_SM.webp'),
  ('B2-223', 'B2', 223, 'Tyrogue', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_223_EN_SM.webp'),
  ('B2-224', 'B2', 224, 'Tauros', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_224_EN_SM.webp'),
  ('B2-225', 'B2', 225, 'Flareon ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_225_EN_SM.webp'),
  ('B2-226', 'B2', 226, 'Ho-Oh ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_226_EN_SM.webp'),
  ('B2-227', 'B2', 227, 'Kingdra ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_227_EN_SM.webp'),
  ('B2-228', 'B2', 228, 'Espeon ex', 'pokemon', 'psychic', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_228_EN_SM.webp'),
  ('B2-229', 'B2', 229, 'Sylveon ex', 'pokemon', 'psychic', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_229_EN_SM.webp'),
  ('B2-230', 'B2', 230, 'Donphan ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_230_EN_SM.webp'),
  ('B2-231', 'B2', 231, 'Umbreon ex', 'pokemon', 'darkness', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_231_EN_SM.webp'),
  ('B2-232', 'B2', 232, 'Lugia ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_232_EN_SM.webp'),
  ('B2-233', 'B2', 233, 'Meloetta', 'pokemon', 'psychic', null, 'crown', 'B2-070', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_233_EN_SM.webp'),
  ('B2-234', 'B2', 234, 'Protective Poncho', 'trainer', null, 'pokemon_tool', 'crown', 'B2-147', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_234_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 234 cards, numbered 1 through 234.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'B2';
