-- Deluxe Pack: ex (A4b): 353 main-set cards and 26 secret cards.
-- Source checked 2026-06-24: https://pocket.limitlesstcg.com/cards/A4b?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Deluxe Pack: ex contains many same-name reprints in its main set. Secret
-- cards are linked to the first same-name main-set card to preserve the
-- existing seed convention without inventing cross-set references.
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A4b-001', 'A4b', 1, 'Bulbasaur', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_001_EN_SM.webp'),
  ('A4b-002', 'A4b', 2, 'Bulbasaur', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_002_EN_SM.webp'),
  ('A4b-003', 'A4b', 3, 'Ivysaur', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_003_EN_SM.webp'),
  ('A4b-004', 'A4b', 4, 'Ivysaur', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_004_EN_SM.webp'),
  ('A4b-005', 'A4b', 5, 'Venusaur ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_005_EN_SM.webp'),
  ('A4b-006', 'A4b', 6, 'Weedle', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_006_EN_SM.webp'),
  ('A4b-007', 'A4b', 7, 'Weedle', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_007_EN_SM.webp'),
  ('A4b-008', 'A4b', 8, 'Kakuna', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_008_EN_SM.webp'),
  ('A4b-009', 'A4b', 9, 'Kakuna', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_009_EN_SM.webp'),
  ('A4b-010', 'A4b', 10, 'Beedrill ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_010_EN_SM.webp'),
  ('A4b-011', 'A4b', 11, 'Exeggcute', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_011_EN_SM.webp'),
  ('A4b-012', 'A4b', 12, 'Exeggcute', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_012_EN_SM.webp'),
  ('A4b-013', 'A4b', 13, 'Exeggutor ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_013_EN_SM.webp'),
  ('A4b-014', 'A4b', 14, 'Hoppip', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_014_EN_SM.webp'),
  ('A4b-015', 'A4b', 15, 'Hoppip', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_015_EN_SM.webp'),
  ('A4b-016', 'A4b', 16, 'Skiploom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_016_EN_SM.webp'),
  ('A4b-017', 'A4b', 17, 'Skiploom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_017_EN_SM.webp'),
  ('A4b-018', 'A4b', 18, 'Jumpluff', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_018_EN_SM.webp'),
  ('A4b-019', 'A4b', 19, 'Jumpluff', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_019_EN_SM.webp'),
  ('A4b-020', 'A4b', 20, 'Yanma', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_020_EN_SM.webp'),
  ('A4b-021', 'A4b', 21, 'Yanma', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_021_EN_SM.webp'),
  ('A4b-022', 'A4b', 22, 'Yanmega ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_022_EN_SM.webp'),
  ('A4b-023', 'A4b', 23, 'Shuckle ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_023_EN_SM.webp'),
  ('A4b-024', 'A4b', 24, 'Celebi ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_024_EN_SM.webp'),
  ('A4b-025', 'A4b', 25, 'Cherubi', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_025_EN_SM.webp'),
  ('A4b-026', 'A4b', 26, 'Cherubi', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_026_EN_SM.webp'),
  ('A4b-027', 'A4b', 27, 'Cherrim', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_027_EN_SM.webp'),
  ('A4b-028', 'A4b', 28, 'Cherrim', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_028_EN_SM.webp'),
  ('A4b-029', 'A4b', 29, 'Leafeon ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_029_EN_SM.webp'),
  ('A4b-030', 'A4b', 30, 'Shaymin', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_030_EN_SM.webp'),
  ('A4b-031', 'A4b', 31, 'Shaymin', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_031_EN_SM.webp'),
  ('A4b-032', 'A4b', 32, 'Snivy', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_032_EN_SM.webp'),
  ('A4b-033', 'A4b', 33, 'Snivy', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_033_EN_SM.webp'),
  ('A4b-034', 'A4b', 34, 'Servine', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_034_EN_SM.webp'),
  ('A4b-035', 'A4b', 35, 'Servine', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_035_EN_SM.webp'),
  ('A4b-036', 'A4b', 36, 'Serperior', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_036_EN_SM.webp'),
  ('A4b-037', 'A4b', 37, 'Serperior', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_037_EN_SM.webp'),
  ('A4b-038', 'A4b', 38, 'Rowlet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_038_EN_SM.webp'),
  ('A4b-039', 'A4b', 39, 'Rowlet', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_039_EN_SM.webp'),
  ('A4b-040', 'A4b', 40, 'Dartrix', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_040_EN_SM.webp'),
  ('A4b-041', 'A4b', 41, 'Dartrix', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_041_EN_SM.webp'),
  ('A4b-042', 'A4b', 42, 'Decidueye ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_042_EN_SM.webp'),
  ('A4b-043', 'A4b', 43, 'Dhelmise ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_043_EN_SM.webp'),
  ('A4b-044', 'A4b', 44, 'Buzzwole ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_044_EN_SM.webp'),
  ('A4b-045', 'A4b', 45, 'Pheromosa', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_045_EN_SM.webp'),
  ('A4b-046', 'A4b', 46, 'Pheromosa', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_046_EN_SM.webp'),
  ('A4b-047', 'A4b', 47, 'Kartana', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_047_EN_SM.webp'),
  ('A4b-048', 'A4b', 48, 'Kartana', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_048_EN_SM.webp'),
  ('A4b-049', 'A4b', 49, 'Sprigatito', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_049_EN_SM.webp'),
  ('A4b-050', 'A4b', 50, 'Sprigatito', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_050_EN_SM.webp'),
  ('A4b-051', 'A4b', 51, 'Floragato', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_051_EN_SM.webp'),
  ('A4b-052', 'A4b', 52, 'Floragato', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_052_EN_SM.webp'),
  ('A4b-053', 'A4b', 53, 'Meowscarada', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_053_EN_SM.webp'),
  ('A4b-054', 'A4b', 54, 'Meowscarada', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_054_EN_SM.webp'),
  ('A4b-055', 'A4b', 55, 'Charmander', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_055_EN_SM.webp'),
  ('A4b-056', 'A4b', 56, 'Charmander', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_056_EN_SM.webp'),
  ('A4b-057', 'A4b', 57, 'Charmeleon', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_057_EN_SM.webp'),
  ('A4b-058', 'A4b', 58, 'Charmeleon', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_058_EN_SM.webp'),
  ('A4b-059', 'A4b', 59, 'Charizard ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_059_EN_SM.webp'),
  ('A4b-060', 'A4b', 60, 'Charizard ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_060_EN_SM.webp'),
  ('A4b-061', 'A4b', 61, 'Growlithe', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_061_EN_SM.webp'),
  ('A4b-062', 'A4b', 62, 'Growlithe', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_062_EN_SM.webp'),
  ('A4b-063', 'A4b', 63, 'Arcanine ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_063_EN_SM.webp'),
  ('A4b-064', 'A4b', 64, 'Flareon', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_064_EN_SM.webp'),
  ('A4b-065', 'A4b', 65, 'Flareon', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_065_EN_SM.webp'),
  ('A4b-066', 'A4b', 66, 'Flareon ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_066_EN_SM.webp'),
  ('A4b-067', 'A4b', 67, 'Moltres ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_067_EN_SM.webp'),
  ('A4b-068', 'A4b', 68, 'Ho-Oh ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_068_EN_SM.webp'),
  ('A4b-069', 'A4b', 69, 'Torkoal', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_069_EN_SM.webp'),
  ('A4b-070', 'A4b', 70, 'Torkoal', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_070_EN_SM.webp'),
  ('A4b-071', 'A4b', 71, 'Chimchar', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_071_EN_SM.webp'),
  ('A4b-072', 'A4b', 72, 'Chimchar', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_072_EN_SM.webp'),
  ('A4b-073', 'A4b', 73, 'Monferno', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_073_EN_SM.webp'),
  ('A4b-074', 'A4b', 74, 'Monferno', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_074_EN_SM.webp'),
  ('A4b-075', 'A4b', 75, 'Infernape ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_075_EN_SM.webp'),
  ('A4b-076', 'A4b', 76, 'Heatran', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_076_EN_SM.webp'),
  ('A4b-077', 'A4b', 77, 'Heatran', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_077_EN_SM.webp'),
  ('A4b-078', 'A4b', 78, 'Litten', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_078_EN_SM.webp'),
  ('A4b-079', 'A4b', 79, 'Litten', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_079_EN_SM.webp'),
  ('A4b-080', 'A4b', 80, 'Torracat', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_080_EN_SM.webp'),
  ('A4b-081', 'A4b', 81, 'Torracat', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_081_EN_SM.webp'),
  ('A4b-082', 'A4b', 82, 'Incineroar ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_082_EN_SM.webp'),
  ('A4b-083', 'A4b', 83, 'Squirtle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_083_EN_SM.webp'),
  ('A4b-084', 'A4b', 84, 'Squirtle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_084_EN_SM.webp'),
  ('A4b-085', 'A4b', 85, 'Wartortle', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_085_EN_SM.webp'),
  ('A4b-086', 'A4b', 86, 'Wartortle', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_086_EN_SM.webp'),
  ('A4b-087', 'A4b', 87, 'Blastoise ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_087_EN_SM.webp'),
  ('A4b-088', 'A4b', 88, 'Horsea', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_088_EN_SM.webp'),
  ('A4b-089', 'A4b', 89, 'Horsea', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_089_EN_SM.webp'),
  ('A4b-090', 'A4b', 90, 'Seadra', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_090_EN_SM.webp'),
  ('A4b-091', 'A4b', 91, 'Seadra', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_091_EN_SM.webp'),
  ('A4b-092', 'A4b', 92, 'Kingdra ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_092_EN_SM.webp'),
  ('A4b-093', 'A4b', 93, 'Staryu', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_093_EN_SM.webp'),
  ('A4b-094', 'A4b', 94, 'Staryu', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_094_EN_SM.webp'),
  ('A4b-095', 'A4b', 95, 'Starmie ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_095_EN_SM.webp'),
  ('A4b-096', 'A4b', 96, 'Magikarp', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_096_EN_SM.webp'),
  ('A4b-097', 'A4b', 97, 'Magikarp', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_097_EN_SM.webp'),
  ('A4b-098', 'A4b', 98, 'Gyarados ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_098_EN_SM.webp'),
  ('A4b-099', 'A4b', 99, 'Vaporeon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_099_EN_SM.webp'),
  ('A4b-100', 'A4b', 100, 'Vaporeon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_100_EN_SM.webp'),
  ('A4b-101', 'A4b', 101, 'Articuno ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_101_EN_SM.webp'),
  ('A4b-102', 'A4b', 102, 'Corphish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_102_EN_SM.webp'),
  ('A4b-103', 'A4b', 103, 'Corphish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_103_EN_SM.webp'),
  ('A4b-104', 'A4b', 104, 'Crawdaunt', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_104_EN_SM.webp'),
  ('A4b-105', 'A4b', 105, 'Crawdaunt', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_105_EN_SM.webp'),
  ('A4b-106', 'A4b', 106, 'Glaceon ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_106_EN_SM.webp'),
  ('A4b-107', 'A4b', 107, 'Palkia ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_107_EN_SM.webp'),
  ('A4b-108', 'A4b', 108, 'Manaphy', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_108_EN_SM.webp'),
  ('A4b-109', 'A4b', 109, 'Manaphy', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_109_EN_SM.webp'),
  ('A4b-110', 'A4b', 110, 'Froakie', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_110_EN_SM.webp'),
  ('A4b-111', 'A4b', 111, 'Froakie', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_111_EN_SM.webp'),
  ('A4b-112', 'A4b', 112, 'Frogadier', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_112_EN_SM.webp'),
  ('A4b-113', 'A4b', 113, 'Frogadier', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_113_EN_SM.webp'),
  ('A4b-114', 'A4b', 114, 'Greninja', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_114_EN_SM.webp'),
  ('A4b-115', 'A4b', 115, 'Greninja', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_115_EN_SM.webp'),
  ('A4b-116', 'A4b', 116, 'Popplio', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_116_EN_SM.webp'),
  ('A4b-117', 'A4b', 117, 'Popplio', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_117_EN_SM.webp'),
  ('A4b-118', 'A4b', 118, 'Brionne', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_118_EN_SM.webp'),
  ('A4b-119', 'A4b', 119, 'Brionne', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_119_EN_SM.webp'),
  ('A4b-120', 'A4b', 120, 'Primarina ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_120_EN_SM.webp'),
  ('A4b-121', 'A4b', 121, 'Crabominable ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_121_EN_SM.webp'),
  ('A4b-122', 'A4b', 122, 'Wishiwashi', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_122_EN_SM.webp'),
  ('A4b-123', 'A4b', 123, 'Wishiwashi', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_123_EN_SM.webp'),
  ('A4b-124', 'A4b', 124, 'Wishiwashi ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_124_EN_SM.webp'),
  ('A4b-125', 'A4b', 125, 'Wiglett', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_125_EN_SM.webp'),
  ('A4b-126', 'A4b', 126, 'Wiglett', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_126_EN_SM.webp'),
  ('A4b-127', 'A4b', 127, 'Wugtrio ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_127_EN_SM.webp'),
  ('A4b-128', 'A4b', 128, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_128_EN_SM.webp'),
  ('A4b-129', 'A4b', 129, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_129_EN_SM.webp'),
  ('A4b-130', 'A4b', 130, 'Alolan Raichu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_130_EN_SM.webp'),
  ('A4b-131', 'A4b', 131, 'Pikachu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_131_EN_SM.webp'),
  ('A4b-132', 'A4b', 132, 'Pikachu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_132_EN_SM.webp'),
  ('A4b-133', 'A4b', 133, 'Magnemite', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_133_EN_SM.webp'),
  ('A4b-134', 'A4b', 134, 'Magnemite', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_134_EN_SM.webp'),
  ('A4b-135', 'A4b', 135, 'Magneton', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_135_EN_SM.webp'),
  ('A4b-136', 'A4b', 136, 'Magneton', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_136_EN_SM.webp'),
  ('A4b-137', 'A4b', 137, 'Magnezone', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_137_EN_SM.webp'),
  ('A4b-138', 'A4b', 138, 'Magnezone', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_138_EN_SM.webp'),
  ('A4b-139', 'A4b', 139, 'Zapdos ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_139_EN_SM.webp'),
  ('A4b-140', 'A4b', 140, 'Chinchou', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_140_EN_SM.webp'),
  ('A4b-141', 'A4b', 141, 'Chinchou', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_141_EN_SM.webp'),
  ('A4b-142', 'A4b', 142, 'Lanturn ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_142_EN_SM.webp'),
  ('A4b-143', 'A4b', 143, 'Pachirisu', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_143_EN_SM.webp'),
  ('A4b-144', 'A4b', 144, 'Pachirisu', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_144_EN_SM.webp'),
  ('A4b-145', 'A4b', 145, 'Pachirisu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_145_EN_SM.webp'),
  ('A4b-146', 'A4b', 146, 'Oricorio', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_146_EN_SM.webp'),
  ('A4b-147', 'A4b', 147, 'Oricorio', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_147_EN_SM.webp'),
  ('A4b-148', 'A4b', 148, 'Tapu Koko ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_148_EN_SM.webp'),
  ('A4b-149', 'A4b', 149, 'Zeraora', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_149_EN_SM.webp'),
  ('A4b-150', 'A4b', 150, 'Zeraora', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_150_EN_SM.webp'),
  ('A4b-151', 'A4b', 151, 'Gastly', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_151_EN_SM.webp'),
  ('A4b-152', 'A4b', 152, 'Gastly', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_152_EN_SM.webp'),
  ('A4b-153', 'A4b', 153, 'Haunter', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_153_EN_SM.webp'),
  ('A4b-154', 'A4b', 154, 'Haunter', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_154_EN_SM.webp'),
  ('A4b-155', 'A4b', 155, 'Gengar ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_155_EN_SM.webp'),
  ('A4b-156', 'A4b', 156, 'Jynx', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_156_EN_SM.webp'),
  ('A4b-157', 'A4b', 157, 'Jynx', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_157_EN_SM.webp'),
  ('A4b-158', 'A4b', 158, 'Mewtwo ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_158_EN_SM.webp'),
  ('A4b-159', 'A4b', 159, 'Mew ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_159_EN_SM.webp'),
  ('A4b-160', 'A4b', 160, 'Espeon ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_160_EN_SM.webp'),
  ('A4b-161', 'A4b', 161, 'Misdreavus', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_161_EN_SM.webp'),
  ('A4b-162', 'A4b', 162, 'Misdreavus', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_162_EN_SM.webp'),
  ('A4b-163', 'A4b', 163, 'Mismagius ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_163_EN_SM.webp'),
  ('A4b-164', 'A4b', 164, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_164_EN_SM.webp'),
  ('A4b-165', 'A4b', 165, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_165_EN_SM.webp'),
  ('A4b-166', 'A4b', 166, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_166_EN_SM.webp'),
  ('A4b-167', 'A4b', 167, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_167_EN_SM.webp'),
  ('A4b-168', 'A4b', 168, 'Gardevoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_168_EN_SM.webp'),
  ('A4b-169', 'A4b', 169, 'Gardevoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_169_EN_SM.webp'),
  ('A4b-170', 'A4b', 170, 'Giratina', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_170_EN_SM.webp'),
  ('A4b-171', 'A4b', 171, 'Giratina', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_171_EN_SM.webp'),
  ('A4b-172', 'A4b', 172, 'Giratina ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_172_EN_SM.webp'),
  ('A4b-173', 'A4b', 173, 'Swirlix', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_173_EN_SM.webp'),
  ('A4b-174', 'A4b', 174, 'Swirlix', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_174_EN_SM.webp'),
  ('A4b-175', 'A4b', 175, 'Slurpuff', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_175_EN_SM.webp'),
  ('A4b-176', 'A4b', 176, 'Slurpuff', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_176_EN_SM.webp'),
  ('A4b-177', 'A4b', 177, 'Sylveon ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_177_EN_SM.webp'),
  ('A4b-178', 'A4b', 178, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_178_EN_SM.webp'),
  ('A4b-179', 'A4b', 179, 'Oricorio', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_179_EN_SM.webp'),
  ('A4b-180', 'A4b', 180, 'Cosmog', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_180_EN_SM.webp'),
  ('A4b-181', 'A4b', 181, 'Cosmog', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_181_EN_SM.webp'),
  ('A4b-182', 'A4b', 182, 'Cosmoem', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_182_EN_SM.webp'),
  ('A4b-183', 'A4b', 183, 'Cosmoem', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_183_EN_SM.webp'),
  ('A4b-184', 'A4b', 184, 'Lunala ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_184_EN_SM.webp'),
  ('A4b-185', 'A4b', 185, 'Milcery', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_185_EN_SM.webp'),
  ('A4b-186', 'A4b', 186, 'Milcery', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_186_EN_SM.webp'),
  ('A4b-187', 'A4b', 187, 'Alcremie', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_187_EN_SM.webp'),
  ('A4b-188', 'A4b', 188, 'Alcremie', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_188_EN_SM.webp'),
  ('A4b-189', 'A4b', 189, 'Machop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_189_EN_SM.webp'),
  ('A4b-190', 'A4b', 190, 'Machop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_190_EN_SM.webp'),
  ('A4b-191', 'A4b', 191, 'Machoke', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_191_EN_SM.webp'),
  ('A4b-192', 'A4b', 192, 'Machoke', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_192_EN_SM.webp'),
  ('A4b-193', 'A4b', 193, 'Machamp ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_193_EN_SM.webp'),
  ('A4b-194', 'A4b', 194, 'Cubone', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_194_EN_SM.webp'),
  ('A4b-195', 'A4b', 195, 'Cubone', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_195_EN_SM.webp'),
  ('A4b-196', 'A4b', 196, 'Marowak ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_196_EN_SM.webp'),
  ('A4b-197', 'A4b', 197, 'Aerodactyl ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_197_EN_SM.webp'),
  ('A4b-198', 'A4b', 198, 'Sudowoodo', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_198_EN_SM.webp'),
  ('A4b-199', 'A4b', 199, 'Sudowoodo', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_199_EN_SM.webp'),
  ('A4b-200', 'A4b', 200, 'Phanpy', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_200_EN_SM.webp'),
  ('A4b-201', 'A4b', 201, 'Phanpy', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_201_EN_SM.webp'),
  ('A4b-202', 'A4b', 202, 'Donphan ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_202_EN_SM.webp'),
  ('A4b-203', 'A4b', 203, 'Nosepass', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_203_EN_SM.webp'),
  ('A4b-204', 'A4b', 204, 'Nosepass', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_204_EN_SM.webp'),
  ('A4b-205', 'A4b', 205, 'Gible', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_205_EN_SM.webp'),
  ('A4b-206', 'A4b', 206, 'Gible', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_206_EN_SM.webp'),
  ('A4b-207', 'A4b', 207, 'Gabite', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_207_EN_SM.webp'),
  ('A4b-208', 'A4b', 208, 'Gabite', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_208_EN_SM.webp'),
  ('A4b-209', 'A4b', 209, 'Garchomp ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_209_EN_SM.webp'),
  ('A4b-210', 'A4b', 210, 'Riolu', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_210_EN_SM.webp'),
  ('A4b-211', 'A4b', 211, 'Riolu', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_211_EN_SM.webp'),
  ('A4b-212', 'A4b', 212, 'Lucario', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_212_EN_SM.webp'),
  ('A4b-213', 'A4b', 213, 'Lucario', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_213_EN_SM.webp'),
  ('A4b-214', 'A4b', 214, 'Lucario ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_214_EN_SM.webp'),
  ('A4b-215', 'A4b', 215, 'Gallade ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_215_EN_SM.webp'),
  ('A4b-216', 'A4b', 216, 'Drilbur', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_216_EN_SM.webp'),
  ('A4b-217', 'A4b', 217, 'Drilbur', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_217_EN_SM.webp'),
  ('A4b-218', 'A4b', 218, 'Crabrawler', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_218_EN_SM.webp'),
  ('A4b-219', 'A4b', 219, 'Crabrawler', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_219_EN_SM.webp'),
  ('A4b-220', 'A4b', 220, 'Rockruff', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_220_EN_SM.webp'),
  ('A4b-221', 'A4b', 221, 'Rockruff', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_221_EN_SM.webp'),
  ('A4b-222', 'A4b', 222, 'Lycanroc ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_222_EN_SM.webp'),
  ('A4b-223', 'A4b', 223, 'Passimian ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_223_EN_SM.webp'),
  ('A4b-224', 'A4b', 224, 'Marshadow', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_224_EN_SM.webp'),
  ('A4b-225', 'A4b', 225, 'Marshadow', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_225_EN_SM.webp'),
  ('A4b-226', 'A4b', 226, 'Zubat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_226_EN_SM.webp'),
  ('A4b-227', 'A4b', 227, 'Zubat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_227_EN_SM.webp'),
  ('A4b-228', 'A4b', 228, 'Golbat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_228_EN_SM.webp'),
  ('A4b-229', 'A4b', 229, 'Golbat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_229_EN_SM.webp'),
  ('A4b-230', 'A4b', 230, 'Crobat', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_230_EN_SM.webp'),
  ('A4b-231', 'A4b', 231, 'Crobat', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_231_EN_SM.webp'),
  ('A4b-232', 'A4b', 232, 'Crobat ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_232_EN_SM.webp'),
  ('A4b-233', 'A4b', 233, 'Alolan Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_233_EN_SM.webp'),
  ('A4b-234', 'A4b', 234, 'Alolan Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_234_EN_SM.webp'),
  ('A4b-235', 'A4b', 235, 'Alolan Muk ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_235_EN_SM.webp'),
  ('A4b-236', 'A4b', 236, 'Paldean Wooper', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_236_EN_SM.webp'),
  ('A4b-237', 'A4b', 237, 'Paldean Wooper', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_237_EN_SM.webp'),
  ('A4b-238', 'A4b', 238, 'Paldean Clodsire ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_238_EN_SM.webp'),
  ('A4b-239', 'A4b', 239, 'Umbreon', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_239_EN_SM.webp'),
  ('A4b-240', 'A4b', 240, 'Umbreon', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_240_EN_SM.webp'),
  ('A4b-241', 'A4b', 241, 'Umbreon ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_241_EN_SM.webp'),
  ('A4b-242', 'A4b', 242, 'Sneasel', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_242_EN_SM.webp'),
  ('A4b-243', 'A4b', 243, 'Sneasel', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_243_EN_SM.webp'),
  ('A4b-244', 'A4b', 244, 'Weavile ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_244_EN_SM.webp'),
  ('A4b-245', 'A4b', 245, 'Darkrai ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_245_EN_SM.webp'),
  ('A4b-246', 'A4b', 246, 'Nihilego', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_246_EN_SM.webp'),
  ('A4b-247', 'A4b', 247, 'Nihilego', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_247_EN_SM.webp'),
  ('A4b-248', 'A4b', 248, 'Guzzlord ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_248_EN_SM.webp'),
  ('A4b-249', 'A4b', 249, 'Alolan Diglett', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_249_EN_SM.webp'),
  ('A4b-250', 'A4b', 250, 'Alolan Diglett', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_250_EN_SM.webp'),
  ('A4b-251', 'A4b', 251, 'Alolan Dugtrio ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_251_EN_SM.webp'),
  ('A4b-252', 'A4b', 252, 'Skarmory ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_252_EN_SM.webp'),
  ('A4b-253', 'A4b', 253, 'Probopass ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_253_EN_SM.webp'),
  ('A4b-254', 'A4b', 254, 'Dialga ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_254_EN_SM.webp'),
  ('A4b-255', 'A4b', 255, 'Excadrill', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_255_EN_SM.webp'),
  ('A4b-256', 'A4b', 256, 'Excadrill', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_256_EN_SM.webp'),
  ('A4b-257', 'A4b', 257, 'Klefki', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_257_EN_SM.webp'),
  ('A4b-258', 'A4b', 258, 'Klefki', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_258_EN_SM.webp'),
  ('A4b-259', 'A4b', 259, 'Solgaleo ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_259_EN_SM.webp'),
  ('A4b-260', 'A4b', 260, 'Magearna', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_260_EN_SM.webp'),
  ('A4b-261', 'A4b', 261, 'Magearna', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_261_EN_SM.webp'),
  ('A4b-262', 'A4b', 262, 'Tinkatink', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_262_EN_SM.webp'),
  ('A4b-263', 'A4b', 263, 'Tinkatink', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_263_EN_SM.webp'),
  ('A4b-264', 'A4b', 264, 'Tinkatuff', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_264_EN_SM.webp'),
  ('A4b-265', 'A4b', 265, 'Tinkatuff', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_265_EN_SM.webp'),
  ('A4b-266', 'A4b', 266, 'Tinkaton ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_266_EN_SM.webp'),
  ('A4b-267', 'A4b', 267, 'Dratini', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_267_EN_SM.webp'),
  ('A4b-268', 'A4b', 268, 'Dratini', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_268_EN_SM.webp'),
  ('A4b-269', 'A4b', 269, 'Dragonair', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_269_EN_SM.webp'),
  ('A4b-270', 'A4b', 270, 'Dragonair', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_270_EN_SM.webp'),
  ('A4b-271', 'A4b', 271, 'Dragonite ex', 'pokemon', 'dragon', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_271_EN_SM.webp'),
  ('A4b-272', 'A4b', 272, 'Pidgey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_272_EN_SM.webp'),
  ('A4b-273', 'A4b', 273, 'Pidgey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_273_EN_SM.webp'),
  ('A4b-274', 'A4b', 274, 'Pidgeotto', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_274_EN_SM.webp'),
  ('A4b-275', 'A4b', 275, 'Pidgeotto', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_275_EN_SM.webp'),
  ('A4b-276', 'A4b', 276, 'Pidgeot ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_276_EN_SM.webp'),
  ('A4b-277', 'A4b', 277, 'Jigglypuff', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_277_EN_SM.webp'),
  ('A4b-278', 'A4b', 278, 'Jigglypuff', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_278_EN_SM.webp'),
  ('A4b-279', 'A4b', 279, 'Wigglytuff ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_279_EN_SM.webp'),
  ('A4b-280', 'A4b', 280, 'Farfetch''d', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_280_EN_SM.webp'),
  ('A4b-281', 'A4b', 281, 'Farfetch''d', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_281_EN_SM.webp'),
  ('A4b-282', 'A4b', 282, 'Lickitung', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_282_EN_SM.webp'),
  ('A4b-283', 'A4b', 283, 'Lickitung', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_283_EN_SM.webp'),
  ('A4b-284', 'A4b', 284, 'Lickilicky ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_284_EN_SM.webp'),
  ('A4b-285', 'A4b', 285, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_285_EN_SM.webp'),
  ('A4b-286', 'A4b', 286, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_286_EN_SM.webp'),
  ('A4b-287', 'A4b', 287, 'Eevee ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_287_EN_SM.webp'),
  ('A4b-288', 'A4b', 288, 'Snorlax ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_288_EN_SM.webp'),
  ('A4b-289', 'A4b', 289, 'Lugia ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_289_EN_SM.webp'),
  ('A4b-290', 'A4b', 290, 'Skitty', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_290_EN_SM.webp'),
  ('A4b-291', 'A4b', 291, 'Skitty', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_291_EN_SM.webp'),
  ('A4b-292', 'A4b', 292, 'Delcatty', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_292_EN_SM.webp'),
  ('A4b-293', 'A4b', 293, 'Delcatty', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_293_EN_SM.webp'),
  ('A4b-294', 'A4b', 294, 'Bidoof', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_294_EN_SM.webp'),
  ('A4b-295', 'A4b', 295, 'Bidoof', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_295_EN_SM.webp'),
  ('A4b-296', 'A4b', 296, 'Bibarel ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_296_EN_SM.webp'),
  ('A4b-297', 'A4b', 297, 'Shaymin', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_297_EN_SM.webp'),
  ('A4b-298', 'A4b', 298, 'Shaymin', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_298_EN_SM.webp'),
  ('A4b-299', 'A4b', 299, 'Arceus ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_299_EN_SM.webp'),
  ('A4b-300', 'A4b', 300, 'Type: Null', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_300_EN_SM.webp'),
  ('A4b-301', 'A4b', 301, 'Type: Null', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_301_EN_SM.webp'),
  ('A4b-302', 'A4b', 302, 'Silvally', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_302_EN_SM.webp'),
  ('A4b-303', 'A4b', 303, 'Silvally', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_303_EN_SM.webp'),
  ('A4b-304', 'A4b', 304, 'Celesteela', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_304_EN_SM.webp'),
  ('A4b-305', 'A4b', 305, 'Celesteela', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_305_EN_SM.webp'),
  ('A4b-306', 'A4b', 306, 'Cyclizar', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_306_EN_SM.webp'),
  ('A4b-307', 'A4b', 307, 'Cyclizar', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_307_EN_SM.webp'),
  ('A4b-308', 'A4b', 308, 'Eevee Bag', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_308_EN_SM.webp'),
  ('A4b-309', 'A4b', 309, 'Eevee Bag', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_309_EN_SM.webp'),
  ('A4b-310', 'A4b', 310, 'Elemental Switch', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_310_EN_SM.webp'),
  ('A4b-311', 'A4b', 311, 'Elemental Switch', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_311_EN_SM.webp'),
  ('A4b-312', 'A4b', 312, 'Old Amber', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_312_EN_SM.webp'),
  ('A4b-313', 'A4b', 313, 'Old Amber', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_313_EN_SM.webp'),
  ('A4b-314', 'A4b', 314, 'Rare Candy', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_314_EN_SM.webp'),
  ('A4b-315', 'A4b', 315, 'Rare Candy', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_315_EN_SM.webp'),
  ('A4b-316', 'A4b', 316, 'Pokémon Communication', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_316_EN_SM.webp'),
  ('A4b-317', 'A4b', 317, 'Pokémon Communication', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_317_EN_SM.webp'),
  ('A4b-318', 'A4b', 318, 'Electrical Cord', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_318_EN_SM.webp'),
  ('A4b-319', 'A4b', 319, 'Electrical Cord', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_319_EN_SM.webp'),
  ('A4b-320', 'A4b', 320, 'Giant Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_320_EN_SM.webp'),
  ('A4b-321', 'A4b', 321, 'Giant Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_321_EN_SM.webp'),
  ('A4b-322', 'A4b', 322, 'Rocky Helmet', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_322_EN_SM.webp'),
  ('A4b-323', 'A4b', 323, 'Rocky Helmet', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_323_EN_SM.webp'),
  ('A4b-324', 'A4b', 324, 'Leaf Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_324_EN_SM.webp'),
  ('A4b-325', 'A4b', 325, 'Leaf Cape', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_325_EN_SM.webp'),
  ('A4b-326', 'A4b', 326, 'Cyrus', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_326_EN_SM.webp'),
  ('A4b-327', 'A4b', 327, 'Cyrus', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_327_EN_SM.webp'),
  ('A4b-328', 'A4b', 328, 'Erika', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_328_EN_SM.webp'),
  ('A4b-329', 'A4b', 329, 'Erika', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_329_EN_SM.webp'),
  ('A4b-330', 'A4b', 330, 'Irida', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_330_EN_SM.webp'),
  ('A4b-331', 'A4b', 331, 'Irida', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_331_EN_SM.webp'),
  ('A4b-332', 'A4b', 332, 'Lyra', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_332_EN_SM.webp'),
  ('A4b-333', 'A4b', 333, 'Lyra', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_333_EN_SM.webp'),
  ('A4b-334', 'A4b', 334, 'Giovanni', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_334_EN_SM.webp'),
  ('A4b-335', 'A4b', 335, 'Giovanni', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_335_EN_SM.webp'),
  ('A4b-336', 'A4b', 336, 'Silver', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_336_EN_SM.webp'),
  ('A4b-337', 'A4b', 337, 'Silver', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_337_EN_SM.webp'),
  ('A4b-338', 'A4b', 338, 'Sabrina', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_338_EN_SM.webp'),
  ('A4b-339', 'A4b', 339, 'Sabrina', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_339_EN_SM.webp'),
  ('A4b-340', 'A4b', 340, 'Iono', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_340_EN_SM.webp'),
  ('A4b-341', 'A4b', 341, 'Iono', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_341_EN_SM.webp'),
  ('A4b-342', 'A4b', 342, 'Dawn', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_342_EN_SM.webp'),
  ('A4b-343', 'A4b', 343, 'Dawn', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_343_EN_SM.webp'),
  ('A4b-344', 'A4b', 344, 'Mars', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_344_EN_SM.webp'),
  ('A4b-345', 'A4b', 345, 'Mars', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_345_EN_SM.webp'),
  ('A4b-346', 'A4b', 346, 'Leaf', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_346_EN_SM.webp'),
  ('A4b-347', 'A4b', 347, 'Leaf', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_347_EN_SM.webp'),
  ('A4b-348', 'A4b', 348, 'Lillie', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_348_EN_SM.webp'),
  ('A4b-349', 'A4b', 349, 'Lillie', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_349_EN_SM.webp'),
  ('A4b-350', 'A4b', 350, 'Lusamine', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_350_EN_SM.webp'),
  ('A4b-351', 'A4b', 351, 'Lusamine', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_351_EN_SM.webp'),
  ('A4b-352', 'A4b', 352, 'Red', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_352_EN_SM.webp'),
  ('A4b-353', 'A4b', 353, 'Red', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_353_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A4b-354', 'A4b', 354, 'Floragato', 'pokemon', 'grass', null, 'star_1', 'A4b-051', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_354_EN_SM.webp'),
  ('A4b-355', 'A4b', 355, 'Crawdaunt', 'pokemon', 'water', null, 'star_1', 'A4b-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_355_EN_SM.webp'),
  ('A4b-356', 'A4b', 356, 'Greninja', 'pokemon', 'water', null, 'star_1', 'A4b-114', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_356_EN_SM.webp'),
  ('A4b-357', 'A4b', 357, 'Gardevoir', 'pokemon', 'psychic', null, 'star_1', 'A4b-168', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_357_EN_SM.webp'),
  ('A4b-358', 'A4b', 358, 'Slurpuff', 'pokemon', 'psychic', null, 'star_1', 'A4b-175', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_358_EN_SM.webp'),
  ('A4b-359', 'A4b', 359, 'Farfetch''d', 'pokemon', 'colorless', null, 'star_1', 'A4b-280', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_359_EN_SM.webp'),
  ('A4b-360', 'A4b', 360, 'Buzzwole ex', 'pokemon', 'grass', null, 'star_2', 'A4b-044', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_360_EN_SM.webp'),
  ('A4b-361', 'A4b', 361, 'Charizard ex', 'pokemon', 'fire', null, 'star_2', 'A4b-059', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_361_EN_SM.webp'),
  ('A4b-362', 'A4b', 362, 'Ho-Oh ex', 'pokemon', 'fire', null, 'star_2', 'A4b-068', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_362_EN_SM.webp'),
  ('A4b-363', 'A4b', 363, 'Palkia ex', 'pokemon', 'water', null, 'star_2', 'A4b-107', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_363_EN_SM.webp'),
  ('A4b-364', 'A4b', 364, 'Pikachu ex', 'pokemon', 'lightning', null, 'star_2', 'A4b-131', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_364_EN_SM.webp'),
  ('A4b-365', 'A4b', 365, 'Mewtwo ex', 'pokemon', 'psychic', null, 'star_2', 'A4b-158', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_365_EN_SM.webp'),
  ('A4b-366', 'A4b', 366, 'Mew ex', 'pokemon', 'psychic', null, 'star_2', 'A4b-159', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_366_EN_SM.webp'),
  ('A4b-367', 'A4b', 367, 'Lunala ex', 'pokemon', 'psychic', null, 'star_2', 'A4b-184', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_367_EN_SM.webp'),
  ('A4b-368', 'A4b', 368, 'Dialga ex', 'pokemon', 'metal', null, 'star_2', 'A4b-254', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_368_EN_SM.webp'),
  ('A4b-369', 'A4b', 369, 'Solgaleo ex', 'pokemon', 'metal', null, 'star_2', 'A4b-259', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_369_EN_SM.webp'),
  ('A4b-370', 'A4b', 370, 'Eevee ex', 'pokemon', 'colorless', null, 'star_2', 'A4b-287', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_370_EN_SM.webp'),
  ('A4b-371', 'A4b', 371, 'Lugia ex', 'pokemon', 'colorless', null, 'star_2', 'A4b-289', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_371_EN_SM.webp'),
  ('A4b-372', 'A4b', 372, 'Arceus ex', 'pokemon', 'colorless', null, 'star_2', 'A4b-299', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_372_EN_SM.webp'),
  ('A4b-373', 'A4b', 373, 'Professor''s Research', 'trainer', null, 'supporter', 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_373_EN_SM.webp'),
  ('A4b-374', 'A4b', 374, 'Lillie', 'trainer', null, 'supporter', 'star_2', 'A4b-348', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_374_EN_SM.webp'),
  ('A4b-375', 'A4b', 375, 'Lusamine', 'trainer', null, 'supporter', 'star_2', 'A4b-350', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_375_EN_SM.webp'),
  ('A4b-376', 'A4b', 376, 'Pikachu ex', 'pokemon', 'lightning', null, 'star_3', 'A4b-131', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_376_EN_SM.webp'),
  ('A4b-377', 'A4b', 377, 'Giratina ex', 'pokemon', 'psychic', null, 'star_2', 'A4b-172', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_377_EN_SM.webp'),
  ('A4b-378', 'A4b', 378, 'Darkrai ex', 'pokemon', 'darkness', null, 'star_2', 'A4b-245', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_378_EN_SM.webp'),
  ('A4b-379', 'A4b', 379, 'Rare Candy', 'trainer', null, 'item', 'crown', 'A4b-314', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4b/A4b_379_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 379 cards, numbered 1 through 379.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'A4b';
