-- Team Rocket's Ambition (B4a) per-card acquisition probabilities.
-- Sources checked 2026-08-29:
-- https://bulbapedia.bulbagarden.net/wiki/Team_Rocket's_Ambition_(TCG_Pocket)
-- https://pocket.limitlesstcg.com/cards/B4a
-- https://bulbapedia.bulbagarden.net/wiki/Paradox_Drive_(TCG_Pocket)#Offering_rates
-- https://bulbapedia.bulbagarden.net/wiki/Everyday_Wonders_(TCG_Pocket)#Offering_rates
--
-- Definition used by card_pack_odds.pull_probability:
-- P(the card appears at least once in one opened pack).
--
-- Team Rocket's Ambition card lists are published, but the public per-card
-- offering-rate table is not yet filled in on the primary reference pages.
-- These rates use the same single themed-booster slot allocation published
-- for recent comparable sets and apply it to B4a's actual rarity counts.
--
-- Themed-booster pack-type rates used:
--   regular pack:            94.711%
--   regular pack + 1 card:    5.238%
--   rare pack:                0.050%
--
-- In regular packs with a bonus card, Bulbapedia states that the first five
-- cards use the same rates as regular packs without a bonus card. Shiny cards
-- are only available in the sixth-card bonus slot.
--
-- The source publishes per-card rates rounded to three decimal percentage
-- points. These calculations intentionally use those published values.
--
-- Bulbapedia separates one-star and two-star shiny rates from regular
-- one-star and two-star rates. Limitless renders these with the same visible
-- star glyphs in the list view, so this seed applies shiny rates by collector
-- number: B4a-095 through B4a-104 are shiny_1 and B4a-105 through B4a-108
-- are shiny_2.

begin;

insert into public.card_pack_odds (
  pack_id,
  card_id,
  pull_probability,
  source_note,
  verified_at
)
values
  ('b4a-team-rockets-ambition', 'B4a-001', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-002', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-003', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-004', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-005', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-006', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-007', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-008', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-009', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-010', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-011', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-012', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-013', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-014', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-015', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-016', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-017', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-018', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-019', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-020', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-021', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-022', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-023', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-024', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-025', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-026', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-027', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-028', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-029', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-030', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-031', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-032', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-033', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-034', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-035', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-036', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-037', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-038', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-039', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-040', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-041', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-042', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-043', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-044', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-045', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-046', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-047', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-048', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-049', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-050', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-051', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-052', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-053', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-054', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-055', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-056', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-057', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-058', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-059', 0.0166071371::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-060', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-061', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-062', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-063', 0.0310778922::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-064', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-065', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-066', 0.0908044962::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-067', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-068', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-069', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-070', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-071', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-072', 0.0568525377::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-073', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-074', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-075', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-076', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-077', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-078', 0.0214315803::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-079', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-080', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-081', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-082', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-083', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-084', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-085', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-086', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-087', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-088', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-089', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-090', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-091', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-092', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-093', 0.0017545410::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-094', 0.0111804344::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-095', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-096', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-097', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-098', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-099', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-100', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-101', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-102', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-103', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-104', 0.0035712684::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-105', 0.0041668290::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-106', 0.0041668290::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-107', 0.0041668290::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-108', 0.0041668290::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-109', 0.0010951564::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29'),
  ('b4a-team-rockets-ambition', 'B4a-110', 0.0010951564::numeric, 'Derived from the standard themed-booster Offering Rates structure and the Team Rocket''s Ambition Limitless/Bulbapedia card list; includes regular, regular-plus-bonus, and rare pack paths; cards B4a-095 through B4a-104 use shiny_1 rates and cards B4a-105 through B4a-108 use shiny_2 rates; probability means at least once per opened pack.', date '2026-08-29')
on conflict (pack_id, card_id) do update set
  pull_probability = excluded.pull_probability,
  source_note = excluded.source_note,
  verified_at = excluded.verified_at,
  updated_at = now();

-- Stop and roll back if the catalog, pack, or generated odds are incomplete.
do $$
declare
  team_rockets_ambition_cards integer;
  team_rockets_ambition_packs integer;
  team_rockets_ambition_odds integer;
begin
  select count(*)
  into team_rockets_ambition_cards
  from public.cards
  where set_id = 'B4a';

  select count(*)
  into team_rockets_ambition_packs
  from public.packs
  where set_id = 'B4a';

  select count(*)
  into team_rockets_ambition_odds
  from public.card_pack_odds
  where pack_id = 'b4a-team-rockets-ambition';

  if team_rockets_ambition_cards <> 110 then
    raise exception
      'Expected 110 Team Rocket's Ambition cards, found %',
      team_rockets_ambition_cards;
  end if;

  if team_rockets_ambition_packs <> 1 then
    raise exception
      'Expected 1 Team Rocket's Ambition pack, found %',
      team_rockets_ambition_packs;
  end if;

  if team_rockets_ambition_odds <> 110 then
    raise exception
      'Expected 110 Team Rocket's Ambition odds rows, found %',
      team_rockets_ambition_odds;
  end if;
end
$$;

commit;

-- Expected: 110 total records for the Team Rocket's Ambition pack.
select
  cards.rarity,
  count(*) as cards,
  min(card_pack_odds.pull_probability) as min_pull_probability,
  max(card_pack_odds.pull_probability) as max_pull_probability
from public.card_pack_odds
join public.cards
  on cards.id = card_pack_odds.card_id
where card_pack_odds.pack_id = 'b4a-team-rockets-ambition'
group by cards.rarity
order by min(cards.collector_number);
