-- Mega Rising (B1): 226 main-set cards and 105 secret cards.
-- Source checked 2026-06-25: https://pocket.limitlesstcg.com/cards/B1?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B1-001', 'B1', 1, 'Pinsir', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_001_EN_SM.webp'),
  ('B1-002', 'B1', 2, 'Mega Pinsir ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_002_EN_SM.webp'),
  ('B1-003', 'B1', 3, 'Wurmple', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_003_EN_SM.webp'),
  ('B1-004', 'B1', 4, 'Silcoon', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_004_EN_SM.webp'),
  ('B1-005', 'B1', 5, 'Beautifly', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_005_EN_SM.webp'),
  ('B1-006', 'B1', 6, 'Cascoon', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_006_EN_SM.webp'),
  ('B1-007', 'B1', 7, 'Dustox', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_007_EN_SM.webp'),
  ('B1-008', 'B1', 8, 'Seedot', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_008_EN_SM.webp'),
  ('B1-009', 'B1', 9, 'Nuzleaf', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_009_EN_SM.webp'),
  ('B1-010', 'B1', 10, 'Shiftry', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_010_EN_SM.webp'),
  ('B1-011', 'B1', 11, 'Shroomish', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_011_EN_SM.webp'),
  ('B1-012', 'B1', 12, 'Breloom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_012_EN_SM.webp'),
  ('B1-013', 'B1', 13, 'Pansage', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_013_EN_SM.webp'),
  ('B1-014', 'B1', 14, 'Simisage', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_014_EN_SM.webp'),
  ('B1-015', 'B1', 15, 'Cottonee', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_015_EN_SM.webp'),
  ('B1-016', 'B1', 16, 'Whimsicott ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_016_EN_SM.webp'),
  ('B1-017', 'B1', 17, 'Petilil', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_017_EN_SM.webp'),
  ('B1-018', 'B1', 18, 'Lilligant', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_018_EN_SM.webp'),
  ('B1-019', 'B1', 19, 'Maractus', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_019_EN_SM.webp'),
  ('B1-020', 'B1', 20, 'Virizion', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_020_EN_SM.webp'),
  ('B1-021', 'B1', 21, 'Skiddo', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_021_EN_SM.webp'),
  ('B1-022', 'B1', 22, 'Gogoat', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_022_EN_SM.webp'),
  ('B1-023', 'B1', 23, 'Phantump', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_023_EN_SM.webp'),
  ('B1-024', 'B1', 24, 'Trevenant', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_024_EN_SM.webp'),
  ('B1-025', 'B1', 25, 'Grookey', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_025_EN_SM.webp'),
  ('B1-026', 'B1', 26, 'Thwackey', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_026_EN_SM.webp'),
  ('B1-027', 'B1', 27, 'Rillaboom', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_027_EN_SM.webp'),
  ('B1-028', 'B1', 28, 'Growlithe', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_028_EN_SM.webp'),
  ('B1-029', 'B1', 29, 'Arcanine', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_029_EN_SM.webp'),
  ('B1-030', 'B1', 30, 'Ponyta', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_030_EN_SM.webp'),
  ('B1-031', 'B1', 31, 'Rapidash ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_031_EN_SM.webp'),
  ('B1-032', 'B1', 32, 'Ho-Oh', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_032_EN_SM.webp'),
  ('B1-033', 'B1', 33, 'Torchic', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_033_EN_SM.webp'),
  ('B1-034', 'B1', 34, 'Combusken', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_034_EN_SM.webp'),
  ('B1-035', 'B1', 35, 'Blaziken', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_035_EN_SM.webp'),
  ('B1-036', 'B1', 36, 'Mega Blaziken ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_036_EN_SM.webp'),
  ('B1-037', 'B1', 37, 'Pansear', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_037_EN_SM.webp'),
  ('B1-038', 'B1', 38, 'Simisear', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_038_EN_SM.webp'),
  ('B1-039', 'B1', 39, 'Darumaka', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_039_EN_SM.webp'),
  ('B1-040', 'B1', 40, 'Darmanitan', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_040_EN_SM.webp'),
  ('B1-041', 'B1', 41, 'Litwick', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_041_EN_SM.webp'),
  ('B1-042', 'B1', 42, 'Lampent', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_042_EN_SM.webp'),
  ('B1-043', 'B1', 43, 'Chandelure', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_043_EN_SM.webp'),
  ('B1-044', 'B1', 44, 'Heatmor', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_044_EN_SM.webp'),
  ('B1-045', 'B1', 45, 'Litleo', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_045_EN_SM.webp'),
  ('B1-046', 'B1', 46, 'Pyroar', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_046_EN_SM.webp'),
  ('B1-047', 'B1', 47, 'Turtonator', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_047_EN_SM.webp'),
  ('B1-048', 'B1', 48, 'Psyduck', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_048_EN_SM.webp'),
  ('B1-049', 'B1', 49, 'Golduck', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_049_EN_SM.webp'),
  ('B1-050', 'B1', 50, 'Magikarp', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_050_EN_SM.webp'),
  ('B1-051', 'B1', 51, 'Gyarados', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_051_EN_SM.webp'),
  ('B1-052', 'B1', 52, 'Mega Gyarados ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_052_EN_SM.webp'),
  ('B1-053', 'B1', 53, 'Lotad', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_053_EN_SM.webp'),
  ('B1-054', 'B1', 54, 'Lombre', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_054_EN_SM.webp'),
  ('B1-055', 'B1', 55, 'Ludicolo', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_055_EN_SM.webp'),
  ('B1-056', 'B1', 56, 'Wailmer', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_056_EN_SM.webp'),
  ('B1-057', 'B1', 57, 'Wailord', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_057_EN_SM.webp'),
  ('B1-058', 'B1', 58, 'Corphish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_058_EN_SM.webp'),
  ('B1-059', 'B1', 59, 'Crawdaunt', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_059_EN_SM.webp'),
  ('B1-060', 'B1', 60, 'Luvdisc', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_060_EN_SM.webp'),
  ('B1-061', 'B1', 61, 'Panpour', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_061_EN_SM.webp'),
  ('B1-062', 'B1', 62, 'Simipour', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_062_EN_SM.webp'),
  ('B1-063', 'B1', 63, 'Tympole', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_063_EN_SM.webp'),
  ('B1-064', 'B1', 64, 'Palpitoad', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_064_EN_SM.webp'),
  ('B1-065', 'B1', 65, 'Seismitoad', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_065_EN_SM.webp'),
  ('B1-066', 'B1', 66, 'Tirtouga', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_066_EN_SM.webp'),
  ('B1-067', 'B1', 67, 'Carracosta', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_067_EN_SM.webp'),
  ('B1-068', 'B1', 68, 'Frillish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_068_EN_SM.webp'),
  ('B1-069', 'B1', 69, 'Jellicent', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_069_EN_SM.webp'),
  ('B1-070', 'B1', 70, 'Keldeo', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_070_EN_SM.webp'),
  ('B1-071', 'B1', 71, 'Froakie', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_071_EN_SM.webp'),
  ('B1-072', 'B1', 72, 'Frogadier', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_072_EN_SM.webp'),
  ('B1-073', 'B1', 73, 'Greninja ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_073_EN_SM.webp'),
  ('B1-074', 'B1', 74, 'Bergmite', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_074_EN_SM.webp'),
  ('B1-075', 'B1', 75, 'Avalugg', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_075_EN_SM.webp'),
  ('B1-076', 'B1', 76, 'Chewtle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_076_EN_SM.webp'),
  ('B1-077', 'B1', 77, 'Drednaw', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_077_EN_SM.webp'),
  ('B1-078', 'B1', 78, 'Arrokuda', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_078_EN_SM.webp'),
  ('B1-079', 'B1', 79, 'Barraskewda', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_079_EN_SM.webp'),
  ('B1-080', 'B1', 80, 'Eiscue', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_080_EN_SM.webp'),
  ('B1-081', 'B1', 81, 'Jolteon ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_081_EN_SM.webp'),
  ('B1-082', 'B1', 82, 'Mareep', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_082_EN_SM.webp'),
  ('B1-083', 'B1', 83, 'Flaaffy', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_083_EN_SM.webp'),
  ('B1-084', 'B1', 84, 'Ampharos', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_084_EN_SM.webp'),
  ('B1-085', 'B1', 85, 'Mega Ampharos ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_085_EN_SM.webp'),
  ('B1-086', 'B1', 86, 'Shinx', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_086_EN_SM.webp'),
  ('B1-087', 'B1', 87, 'Luxio', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_087_EN_SM.webp'),
  ('B1-088', 'B1', 88, 'Luxray', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_088_EN_SM.webp'),
  ('B1-089', 'B1', 89, 'Pachirisu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_089_EN_SM.webp'),
  ('B1-090', 'B1', 90, 'Blitzle', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_090_EN_SM.webp'),
  ('B1-091', 'B1', 91, 'Zebstrika', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_091_EN_SM.webp'),
  ('B1-092', 'B1', 92, 'Joltik', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_092_EN_SM.webp'),
  ('B1-093', 'B1', 93, 'Galvantula', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_093_EN_SM.webp'),
  ('B1-094', 'B1', 94, 'Dedenne', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_094_EN_SM.webp'),
  ('B1-095', 'B1', 95, 'Yamper', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_095_EN_SM.webp'),
  ('B1-096', 'B1', 96, 'Boltund', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_096_EN_SM.webp'),
  ('B1-097', 'B1', 97, 'Natu', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_097_EN_SM.webp'),
  ('B1-098', 'B1', 98, 'Xatu', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_098_EN_SM.webp'),
  ('B1-099', 'B1', 99, 'Misdreavus', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_099_EN_SM.webp'),
  ('B1-100', 'B1', 100, 'Mismagius', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_100_EN_SM.webp'),
  ('B1-101', 'B1', 101, 'Sableye', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_101_EN_SM.webp'),
  ('B1-102', 'B1', 102, 'Mega Altaria ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_102_EN_SM.webp'),
  ('B1-103', 'B1', 103, 'Duskull', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_103_EN_SM.webp'),
  ('B1-104', 'B1', 104, 'Dusclops', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_104_EN_SM.webp'),
  ('B1-105', 'B1', 105, 'Dusknoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_105_EN_SM.webp'),
  ('B1-106', 'B1', 106, 'Jirachi', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_106_EN_SM.webp'),
  ('B1-107', 'B1', 107, 'Drifloon', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_107_EN_SM.webp'),
  ('B1-108', 'B1', 108, 'Drifblim', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_108_EN_SM.webp'),
  ('B1-109', 'B1', 109, 'Chingling', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_109_EN_SM.webp'),
  ('B1-110', 'B1', 110, 'Yamask', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_110_EN_SM.webp'),
  ('B1-111', 'B1', 111, 'Cofagrigus', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_111_EN_SM.webp'),
  ('B1-112', 'B1', 112, 'Gothita', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_112_EN_SM.webp'),
  ('B1-113', 'B1', 113, 'Gothorita', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_113_EN_SM.webp'),
  ('B1-114', 'B1', 114, 'Gothitelle', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_114_EN_SM.webp'),
  ('B1-115', 'B1', 115, 'Spritzee', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_115_EN_SM.webp'),
  ('B1-116', 'B1', 116, 'Aromatisse', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_116_EN_SM.webp'),
  ('B1-117', 'B1', 117, 'Swirlix', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_117_EN_SM.webp'),
  ('B1-118', 'B1', 118, 'Slurpuff', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_118_EN_SM.webp'),
  ('B1-119', 'B1', 119, 'Carbink', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_119_EN_SM.webp'),
  ('B1-120', 'B1', 120, 'Klefki', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_120_EN_SM.webp'),
  ('B1-121', 'B1', 121, 'Indeedee ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_121_EN_SM.webp'),
  ('B1-122', 'B1', 122, 'Sandshrew', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_122_EN_SM.webp'),
  ('B1-123', 'B1', 123, 'Sandslash', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_123_EN_SM.webp'),
  ('B1-124', 'B1', 124, 'Hitmonchan ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_124_EN_SM.webp'),
  ('B1-125', 'B1', 125, 'Sudowoodo', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_125_EN_SM.webp'),
  ('B1-126', 'B1', 126, 'Makuhita', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_126_EN_SM.webp'),
  ('B1-127', 'B1', 127, 'Hariyama', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_127_EN_SM.webp'),
  ('B1-128', 'B1', 128, 'Hippopotas', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_128_EN_SM.webp'),
  ('B1-129', 'B1', 129, 'Hippowdon', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_129_EN_SM.webp'),
  ('B1-130', 'B1', 130, 'Sandile', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_130_EN_SM.webp'),
  ('B1-131', 'B1', 131, 'Krokorok', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_131_EN_SM.webp'),
  ('B1-132', 'B1', 132, 'Krookodile', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_132_EN_SM.webp'),
  ('B1-133', 'B1', 133, 'Archen', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_133_EN_SM.webp'),
  ('B1-134', 'B1', 134, 'Archeops', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_134_EN_SM.webp'),
  ('B1-135', 'B1', 135, 'Golett', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_135_EN_SM.webp'),
  ('B1-136', 'B1', 136, 'Golurk', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_136_EN_SM.webp'),
  ('B1-137', 'B1', 137, 'Terrakion', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_137_EN_SM.webp'),
  ('B1-138', 'B1', 138, 'Pancham', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_138_EN_SM.webp'),
  ('B1-139', 'B1', 139, 'Crabrawler', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_139_EN_SM.webp'),
  ('B1-140', 'B1', 140, 'Crabominable', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_140_EN_SM.webp'),
  ('B1-141', 'B1', 141, 'Stufful', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_141_EN_SM.webp'),
  ('B1-142', 'B1', 142, 'Bewear', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_142_EN_SM.webp'),
  ('B1-143', 'B1', 143, 'Sandygast', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_143_EN_SM.webp'),
  ('B1-144', 'B1', 144, 'Palossand', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_144_EN_SM.webp'),
  ('B1-145', 'B1', 145, 'Rolycoly', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_145_EN_SM.webp'),
  ('B1-146', 'B1', 146, 'Carkol', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_146_EN_SM.webp'),
  ('B1-147', 'B1', 147, 'Coalossal', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_147_EN_SM.webp'),
  ('B1-148', 'B1', 148, 'Murkrow', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_148_EN_SM.webp'),
  ('B1-149', 'B1', 149, 'Honchkrow', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_149_EN_SM.webp'),
  ('B1-150', 'B1', 150, 'Absol', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_150_EN_SM.webp'),
  ('B1-151', 'B1', 151, 'Mega Absol ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_151_EN_SM.webp'),
  ('B1-152', 'B1', 152, 'Skorupi', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_152_EN_SM.webp'),
  ('B1-153', 'B1', 153, 'Drapion', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_153_EN_SM.webp'),
  ('B1-154', 'B1', 154, 'Darkrai', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_154_EN_SM.webp'),
  ('B1-155', 'B1', 155, 'Deino', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_155_EN_SM.webp'),
  ('B1-156', 'B1', 156, 'Zweilous', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_156_EN_SM.webp'),
  ('B1-157', 'B1', 157, 'Hydreigon', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_157_EN_SM.webp'),
  ('B1-158', 'B1', 158, 'Pangoro', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_158_EN_SM.webp'),
  ('B1-159', 'B1', 159, 'Skrelp', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_159_EN_SM.webp'),
  ('B1-160', 'B1', 160, 'Dragalge ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_160_EN_SM.webp'),
  ('B1-161', 'B1', 161, 'Mareanie', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_161_EN_SM.webp'),
  ('B1-162', 'B1', 162, 'Toxapex', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_162_EN_SM.webp'),
  ('B1-163', 'B1', 163, 'Impidimp', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_163_EN_SM.webp'),
  ('B1-164', 'B1', 164, 'Morgrem', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_164_EN_SM.webp'),
  ('B1-165', 'B1', 165, 'Grimmsnarl', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_165_EN_SM.webp'),
  ('B1-166', 'B1', 166, 'Ferroseed', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_166_EN_SM.webp'),
  ('B1-167', 'B1', 167, 'Ferrothorn', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_167_EN_SM.webp'),
  ('B1-168', 'B1', 168, 'Durant', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_168_EN_SM.webp'),
  ('B1-169', 'B1', 169, 'Cobalion', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_169_EN_SM.webp'),
  ('B1-170', 'B1', 170, 'Honedge', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_170_EN_SM.webp'),
  ('B1-171', 'B1', 171, 'Doublade', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_171_EN_SM.webp'),
  ('B1-172', 'B1', 172, 'Aegislash', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_172_EN_SM.webp'),
  ('B1-173', 'B1', 173, 'Meltan', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_173_EN_SM.webp'),
  ('B1-174', 'B1', 174, 'Melmetal ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_174_EN_SM.webp'),
  ('B1-175', 'B1', 175, 'Corviknight', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_175_EN_SM.webp'),
  ('B1-176', 'B1', 176, 'Druddigon', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_176_EN_SM.webp'),
  ('B1-177', 'B1', 177, 'Goomy', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_177_EN_SM.webp'),
  ('B1-178', 'B1', 178, 'Sliggoo', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_178_EN_SM.webp'),
  ('B1-179', 'B1', 179, 'Goodra', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_179_EN_SM.webp'),
  ('B1-180', 'B1', 180, 'Pidgey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_180_EN_SM.webp'),
  ('B1-181', 'B1', 181, 'Pidgeotto', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_181_EN_SM.webp'),
  ('B1-182', 'B1', 182, 'Pidgeot', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_182_EN_SM.webp'),
  ('B1-183', 'B1', 183, 'Tauros ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_183_EN_SM.webp'),
  ('B1-184', 'B1', 184, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_184_EN_SM.webp'),
  ('B1-185', 'B1', 185, 'Aipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_185_EN_SM.webp'),
  ('B1-186', 'B1', 186, 'Ambipom', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_186_EN_SM.webp'),
  ('B1-187', 'B1', 187, 'Miltank', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_187_EN_SM.webp'),
  ('B1-188', 'B1', 188, 'Zigzagoon', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_188_EN_SM.webp'),
  ('B1-189', 'B1', 189, 'Linoone', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_189_EN_SM.webp'),
  ('B1-190', 'B1', 190, 'Whismur', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_190_EN_SM.webp'),
  ('B1-191', 'B1', 191, 'Loudred', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_191_EN_SM.webp'),
  ('B1-192', 'B1', 192, 'Exploud', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_192_EN_SM.webp'),
  ('B1-193', 'B1', 193, 'Skitty', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_193_EN_SM.webp'),
  ('B1-194', 'B1', 194, 'Delcatty', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_194_EN_SM.webp'),
  ('B1-195', 'B1', 195, 'Spinda', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_195_EN_SM.webp'),
  ('B1-196', 'B1', 196, 'Swablu', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_196_EN_SM.webp'),
  ('B1-197', 'B1', 197, 'Altaria', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_197_EN_SM.webp'),
  ('B1-198', 'B1', 198, 'Chatot', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_198_EN_SM.webp'),
  ('B1-199', 'B1', 199, 'Patrat', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_199_EN_SM.webp'),
  ('B1-200', 'B1', 200, 'Watchog', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_200_EN_SM.webp'),
  ('B1-201', 'B1', 201, 'Lillipup', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_201_EN_SM.webp'),
  ('B1-202', 'B1', 202, 'Herdier', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_202_EN_SM.webp'),
  ('B1-203', 'B1', 203, 'Stoutland', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_203_EN_SM.webp'),
  ('B1-204', 'B1', 204, 'Rufflet', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_204_EN_SM.webp'),
  ('B1-205', 'B1', 205, 'Braviary', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_205_EN_SM.webp'),
  ('B1-206', 'B1', 206, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_206_EN_SM.webp'),
  ('B1-207', 'B1', 207, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_207_EN_SM.webp'),
  ('B1-208', 'B1', 208, 'Furfrou', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_208_EN_SM.webp'),
  ('B1-209', 'B1', 209, 'Rookidee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_209_EN_SM.webp'),
  ('B1-210', 'B1', 210, 'Corvisquire', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_210_EN_SM.webp'),
  ('B1-211', 'B1', 211, 'Wooloo', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_211_EN_SM.webp'),
  ('B1-212', 'B1', 212, 'Dubwool', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_212_EN_SM.webp'),
  ('B1-213', 'B1', 213, 'Prank Spinner', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_213_EN_SM.webp'),
  ('B1-214', 'B1', 214, 'Plume Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_214_EN_SM.webp'),
  ('B1-215', 'B1', 215, 'Hitting Hammer', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_215_EN_SM.webp'),
  ('B1-216', 'B1', 216, 'Cover Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_216_EN_SM.webp'),
  ('B1-217', 'B1', 217, 'Flame Patch', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_217_EN_SM.webp'),
  ('B1-218', 'B1', 218, 'Sitrus Berry', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_218_EN_SM.webp'),
  ('B1-219', 'B1', 219, 'Heavy Helmet', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_219_EN_SM.webp'),
  ('B1-220', 'B1', 220, 'Lucky Mittens', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_220_EN_SM.webp'),
  ('B1-221', 'B1', 221, 'Marlon', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_221_EN_SM.webp'),
  ('B1-222', 'B1', 222, 'Hala', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_222_EN_SM.webp'),
  ('B1-223', 'B1', 223, 'May', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_223_EN_SM.webp'),
  ('B1-224', 'B1', 224, 'Fantina', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_224_EN_SM.webp'),
  ('B1-225', 'B1', 225, 'Copycat', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_225_EN_SM.webp'),
  ('B1-226', 'B1', 226, 'Lisia', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_226_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B1-227', 'B1', 227, 'Beautifly', 'pokemon', 'grass', null, 'star_1', 'B1-005', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_227_EN_SM.webp'),
  ('B1-228', 'B1', 228, 'Skiddo', 'pokemon', 'grass', null, 'star_1', 'B1-021', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_228_EN_SM.webp'),
  ('B1-229', 'B1', 229, 'Rillaboom', 'pokemon', 'grass', null, 'star_1', 'B1-027', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_229_EN_SM.webp'),
  ('B1-230', 'B1', 230, 'Growlithe', 'pokemon', 'fire', null, 'star_1', 'B1-028', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_230_EN_SM.webp'),
  ('B1-231', 'B1', 231, 'Chandelure', 'pokemon', 'fire', null, 'star_1', 'B1-043', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_231_EN_SM.webp'),
  ('B1-232', 'B1', 232, 'Magikarp', 'pokemon', 'water', null, 'star_1', 'B1-050', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_232_EN_SM.webp'),
  ('B1-233', 'B1', 233, 'Ludicolo', 'pokemon', 'water', null, 'star_1', 'B1-055', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_233_EN_SM.webp'),
  ('B1-234', 'B1', 234, 'Jellicent', 'pokemon', 'water', null, 'star_1', 'B1-069', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_234_EN_SM.webp'),
  ('B1-235', 'B1', 235, 'Keldeo', 'pokemon', 'water', null, 'star_1', 'B1-070', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_235_EN_SM.webp'),
  ('B1-236', 'B1', 236, 'Eiscue', 'pokemon', 'water', null, 'star_1', 'B1-080', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_236_EN_SM.webp'),
  ('B1-237', 'B1', 237, 'Luxray', 'pokemon', 'lightning', null, 'star_1', 'B1-088', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_237_EN_SM.webp'),
  ('B1-238', 'B1', 238, 'Cofagrigus', 'pokemon', 'psychic', null, 'star_1', 'B1-111', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_238_EN_SM.webp'),
  ('B1-239', 'B1', 239, 'Gothita', 'pokemon', 'psychic', null, 'star_1', 'B1-112', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_239_EN_SM.webp'),
  ('B1-240', 'B1', 240, 'Makuhita', 'pokemon', 'fighting', null, 'star_1', 'B1-126', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_240_EN_SM.webp'),
  ('B1-241', 'B1', 241, 'Hippowdon', 'pokemon', 'fighting', null, 'star_1', 'B1-129', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_241_EN_SM.webp'),
  ('B1-242', 'B1', 242, 'Archeops', 'pokemon', 'fighting', null, 'star_1', 'B1-134', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_242_EN_SM.webp'),
  ('B1-243', 'B1', 243, 'Pancham', 'pokemon', 'fighting', null, 'star_1', 'B1-138', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_243_EN_SM.webp'),
  ('B1-244', 'B1', 244, 'Honchkrow', 'pokemon', 'darkness', null, 'star_1', 'B1-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_244_EN_SM.webp'),
  ('B1-245', 'B1', 245, 'Hydreigon', 'pokemon', 'darkness', null, 'star_1', 'B1-157', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_245_EN_SM.webp'),
  ('B1-246', 'B1', 246, 'Corviknight', 'pokemon', 'metal', null, 'star_1', 'B1-175', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_246_EN_SM.webp'),
  ('B1-247', 'B1', 247, 'Goomy', 'pokemon', 'dragon', null, 'star_1', 'B1-177', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_247_EN_SM.webp'),
  ('B1-248', 'B1', 248, 'Delcatty', 'pokemon', 'colorless', null, 'star_1', 'B1-194', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_248_EN_SM.webp'),
  ('B1-249', 'B1', 249, 'Stoutland', 'pokemon', 'colorless', null, 'star_1', 'B1-203', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_249_EN_SM.webp'),
  ('B1-250', 'B1', 250, 'Rufflet', 'pokemon', 'colorless', null, 'star_1', 'B1-204', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_250_EN_SM.webp'),
  ('B1-251', 'B1', 251, 'Mega Pinsir ex', 'pokemon', 'grass', null, 'star_2', 'B1-002', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_251_EN_SM.webp'),
  ('B1-252', 'B1', 252, 'Whimsicott ex', 'pokemon', 'grass', null, 'star_2', 'B1-016', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_252_EN_SM.webp'),
  ('B1-253', 'B1', 253, 'Rapidash ex', 'pokemon', 'fire', null, 'star_2', 'B1-031', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_253_EN_SM.webp'),
  ('B1-254', 'B1', 254, 'Mega Blaziken ex', 'pokemon', 'fire', null, 'star_2', 'B1-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_254_EN_SM.webp'),
  ('B1-255', 'B1', 255, 'Mega Gyarados ex', 'pokemon', 'water', null, 'star_2', 'B1-052', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_255_EN_SM.webp'),
  ('B1-256', 'B1', 256, 'Greninja ex', 'pokemon', 'water', null, 'star_2', 'B1-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_256_EN_SM.webp'),
  ('B1-257', 'B1', 257, 'Jolteon ex', 'pokemon', 'lightning', null, 'star_2', 'B1-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_257_EN_SM.webp'),
  ('B1-258', 'B1', 258, 'Mega Ampharos ex', 'pokemon', 'lightning', null, 'star_2', 'B1-085', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_258_EN_SM.webp'),
  ('B1-259', 'B1', 259, 'Mega Altaria ex', 'pokemon', 'psychic', null, 'star_2', 'B1-102', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_259_EN_SM.webp'),
  ('B1-260', 'B1', 260, 'Indeedee ex', 'pokemon', 'psychic', null, 'star_2', 'B1-121', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_260_EN_SM.webp'),
  ('B1-261', 'B1', 261, 'Hitmonchan ex', 'pokemon', 'fighting', null, 'star_2', 'B1-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_261_EN_SM.webp'),
  ('B1-262', 'B1', 262, 'Mega Absol ex', 'pokemon', 'darkness', null, 'star_2', 'B1-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_262_EN_SM.webp'),
  ('B1-263', 'B1', 263, 'Dragalge ex', 'pokemon', 'darkness', null, 'star_2', 'B1-160', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_263_EN_SM.webp'),
  ('B1-264', 'B1', 264, 'Melmetal ex', 'pokemon', 'metal', null, 'star_2', 'B1-174', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_264_EN_SM.webp'),
  ('B1-265', 'B1', 265, 'Tauros ex', 'pokemon', 'colorless', null, 'star_2', 'B1-183', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_265_EN_SM.webp'),
  ('B1-266', 'B1', 266, 'Marlon', 'trainer', null, 'supporter', 'star_2', 'B1-221', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_266_EN_SM.webp'),
  ('B1-267', 'B1', 267, 'Hala', 'trainer', null, 'supporter', 'star_2', 'B1-222', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_267_EN_SM.webp'),
  ('B1-268', 'B1', 268, 'May', 'trainer', null, 'supporter', 'star_2', 'B1-223', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_268_EN_SM.webp'),
  ('B1-269', 'B1', 269, 'Fantina', 'trainer', null, 'supporter', 'star_2', 'B1-224', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_269_EN_SM.webp'),
  ('B1-270', 'B1', 270, 'Copycat', 'trainer', null, 'supporter', 'star_2', 'B1-225', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_270_EN_SM.webp'),
  ('B1-271', 'B1', 271, 'Lisia', 'trainer', null, 'supporter', 'star_2', 'B1-226', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_271_EN_SM.webp'),
  ('B1-272', 'B1', 272, 'Mega Pinsir ex', 'pokemon', 'grass', null, 'star_2', 'B1-002', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_272_EN_SM.webp'),
  ('B1-273', 'B1', 273, 'Whimsicott ex', 'pokemon', 'grass', null, 'star_2', 'B1-016', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_273_EN_SM.webp'),
  ('B1-274', 'B1', 274, 'Rapidash ex', 'pokemon', 'fire', null, 'star_2', 'B1-031', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_274_EN_SM.webp'),
  ('B1-275', 'B1', 275, 'Greninja ex', 'pokemon', 'water', null, 'star_2', 'B1-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_275_EN_SM.webp'),
  ('B1-276', 'B1', 276, 'Jolteon ex', 'pokemon', 'lightning', null, 'star_2', 'B1-081', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_276_EN_SM.webp'),
  ('B1-277', 'B1', 277, 'Mega Ampharos ex', 'pokemon', 'lightning', null, 'star_2', 'B1-085', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_277_EN_SM.webp'),
  ('B1-278', 'B1', 278, 'Indeedee ex', 'pokemon', 'psychic', null, 'star_2', 'B1-121', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_278_EN_SM.webp'),
  ('B1-279', 'B1', 279, 'Hitmonchan ex', 'pokemon', 'fighting', null, 'star_2', 'B1-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_279_EN_SM.webp'),
  ('B1-280', 'B1', 280, 'Mega Absol ex', 'pokemon', 'darkness', null, 'star_2', 'B1-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_280_EN_SM.webp'),
  ('B1-281', 'B1', 281, 'Dragalge ex', 'pokemon', 'darkness', null, 'star_2', 'B1-160', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_281_EN_SM.webp'),
  ('B1-282', 'B1', 282, 'Melmetal ex', 'pokemon', 'metal', null, 'star_2', 'B1-174', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_282_EN_SM.webp'),
  ('B1-283', 'B1', 283, 'Tauros ex', 'pokemon', 'colorless', null, 'star_2', 'B1-183', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_283_EN_SM.webp'),
  ('B1-284', 'B1', 284, 'Mega Blaziken ex', 'pokemon', 'fire', null, 'star_3', 'B1-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_284_EN_SM.webp'),
  ('B1-285', 'B1', 285, 'Mega Gyarados ex', 'pokemon', 'water', null, 'star_3', 'B1-052', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_285_EN_SM.webp'),
  ('B1-286', 'B1', 286, 'Mega Altaria ex', 'pokemon', 'psychic', null, 'star_3', 'B1-102', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_286_EN_SM.webp'),
  ('B1-287', 'B1', 287, 'Bellsprout', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_287_EN_SM.webp'),
  ('B1-288', 'B1', 288, 'Weepinbell', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_288_EN_SM.webp'),
  ('B1-289', 'B1', 289, 'Victreebel', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_289_EN_SM.webp'),
  ('B1-290', 'B1', 290, 'Rowlet', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_290_EN_SM.webp'),
  ('B1-291', 'B1', 291, 'Dartrix', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_291_EN_SM.webp'),
  ('B1-292', 'B1', 292, 'Moltres', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_292_EN_SM.webp'),
  ('B1-293', 'B1', 293, 'Litten', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_293_EN_SM.webp'),
  ('B1-294', 'B1', 294, 'Torracat', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_294_EN_SM.webp'),
  ('B1-295', 'B1', 295, 'Poliwag', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_295_EN_SM.webp'),
  ('B1-296', 'B1', 296, 'Poliwhirl', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_296_EN_SM.webp'),
  ('B1-297', 'B1', 297, 'Poliwrath', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_297_EN_SM.webp'),
  ('B1-298', 'B1', 298, 'Articuno', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_298_EN_SM.webp'),
  ('B1-299', 'B1', 299, 'Manaphy', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_299_EN_SM.webp'),
  ('B1-300', 'B1', 300, 'Popplio', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_300_EN_SM.webp'),
  ('B1-301', 'B1', 301, 'Brionne', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_301_EN_SM.webp'),
  ('B1-302', 'B1', 302, 'Zapdos', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_302_EN_SM.webp'),
  ('B1-303', 'B1', 303, 'Oricorio', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_303_EN_SM.webp'),
  ('B1-304', 'B1', 304, 'Zeraora', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_304_EN_SM.webp'),
  ('B1-305', 'B1', 305, 'Drowzee', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_305_EN_SM.webp'),
  ('B1-306', 'B1', 306, 'Hypno', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_306_EN_SM.webp'),
  ('B1-307', 'B1', 307, 'Geodude', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_307_EN_SM.webp'),
  ('B1-308', 'B1', 308, 'Graveler', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_308_EN_SM.webp'),
  ('B1-309', 'B1', 309, 'Golem', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_309_EN_SM.webp'),
  ('B1-310', 'B1', 310, 'Rockruff', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_310_EN_SM.webp'),
  ('B1-311', 'B1', 311, 'Alolan Diglett', 'pokemon', 'metal', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_311_EN_SM.webp'),
  ('B1-312', 'B1', 312, 'Meowth', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_312_EN_SM.webp'),
  ('B1-313', 'B1', 313, 'Persian', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_313_EN_SM.webp'),
  ('B1-314', 'B1', 314, 'Doduo', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_314_EN_SM.webp'),
  ('B1-315', 'B1', 315, 'Dodrio', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_315_EN_SM.webp'),
  ('B1-316', 'B1', 316, 'Bidoof', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_316_EN_SM.webp'),
  ('B1-317', 'B1', 317, 'Decidueye ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_317_EN_SM.webp'),
  ('B1-318', 'B1', 318, 'Incineroar ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_318_EN_SM.webp'),
  ('B1-319', 'B1', 319, 'Palkia ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_319_EN_SM.webp'),
  ('B1-320', 'B1', 320, 'Primarina ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_320_EN_SM.webp'),
  ('B1-321', 'B1', 321, 'Pikachu ex', 'pokemon', 'lightning', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_321_EN_SM.webp'),
  ('B1-322', 'B1', 322, 'Tapu Koko ex', 'pokemon', 'lightning', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_322_EN_SM.webp'),
  ('B1-323', 'B1', 323, 'Lycanroc ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_323_EN_SM.webp'),
  ('B1-324', 'B1', 324, 'Passimian ex', 'pokemon', 'fighting', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_324_EN_SM.webp'),
  ('B1-325', 'B1', 325, 'Alolan Dugtrio ex', 'pokemon', 'metal', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_325_EN_SM.webp'),
  ('B1-326', 'B1', 326, 'Dialga ex', 'pokemon', 'metal', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_326_EN_SM.webp'),
  ('B1-327', 'B1', 327, 'Bibarel ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_327_EN_SM.webp'),
  ('B1-328', 'B1', 328, 'Arceus ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_328_EN_SM.webp'),
  ('B1-329', 'B1', 329, 'Lilligant', 'pokemon', 'grass', null, 'crown', 'B1-018', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_329_EN_SM.webp'),
  ('B1-330', 'B1', 330, 'Klefki', 'pokemon', 'psychic', null, 'crown', 'B1-120', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_330_EN_SM.webp'),
  ('B1-331', 'B1', 331, 'Flame Patch', 'trainer', null, 'item', 'crown', 'B1-217', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_331_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 331 cards, numbered 1 through 331.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'B1';
