-- Wisdom of Sea and Sky (A4): 161 main-set cards and 80 secret cards.
-- Source checked 2026-06-24: https://pocket.limitlesstcg.com/cards/A4?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A4-001', 'A4', 1, 'Oddish', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_001_EN_SM.webp'),
  ('A4-002', 'A4', 2, 'Gloom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_002_EN_SM.webp'),
  ('A4-003', 'A4', 3, 'Bellossom', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_003_EN_SM.webp'),
  ('A4-004', 'A4', 4, 'Tangela', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_004_EN_SM.webp'),
  ('A4-005', 'A4', 5, 'Tangrowth', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_005_EN_SM.webp'),
  ('A4-006', 'A4', 6, 'Scyther', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_006_EN_SM.webp'),
  ('A4-007', 'A4', 7, 'Pinsir', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_007_EN_SM.webp'),
  ('A4-008', 'A4', 8, 'Chikorita', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_008_EN_SM.webp'),
  ('A4-009', 'A4', 9, 'Bayleef', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_009_EN_SM.webp'),
  ('A4-010', 'A4', 10, 'Meganium', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_010_EN_SM.webp'),
  ('A4-011', 'A4', 11, 'Ledyba', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_011_EN_SM.webp'),
  ('A4-012', 'A4', 12, 'Ledian', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_012_EN_SM.webp'),
  ('A4-013', 'A4', 13, 'Hoppip', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_013_EN_SM.webp'),
  ('A4-014', 'A4', 14, 'Skiploom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_014_EN_SM.webp'),
  ('A4-015', 'A4', 15, 'Jumpluff', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_015_EN_SM.webp'),
  ('A4-016', 'A4', 16, 'Sunkern', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_016_EN_SM.webp'),
  ('A4-017', 'A4', 17, 'Sunflora', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_017_EN_SM.webp'),
  ('A4-018', 'A4', 18, 'Yanma', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_018_EN_SM.webp'),
  ('A4-019', 'A4', 19, 'Yanmega', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_019_EN_SM.webp'),
  ('A4-020', 'A4', 20, 'Pineco', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_020_EN_SM.webp'),
  ('A4-021', 'A4', 21, 'Shuckle ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_021_EN_SM.webp'),
  ('A4-022', 'A4', 22, 'Heracross', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_022_EN_SM.webp'),
  ('A4-023', 'A4', 23, 'Cherubi', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_023_EN_SM.webp'),
  ('A4-024', 'A4', 24, 'Cherrim', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_024_EN_SM.webp'),
  ('A4-025', 'A4', 25, 'Vulpix', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_025_EN_SM.webp'),
  ('A4-026', 'A4', 26, 'Ninetales', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_026_EN_SM.webp'),
  ('A4-027', 'A4', 27, 'Cyndaquil', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_027_EN_SM.webp'),
  ('A4-028', 'A4', 28, 'Quilava', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_028_EN_SM.webp'),
  ('A4-029', 'A4', 29, 'Typhlosion', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_029_EN_SM.webp'),
  ('A4-030', 'A4', 30, 'Slugma', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_030_EN_SM.webp'),
  ('A4-031', 'A4', 31, 'Magcargo', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_031_EN_SM.webp'),
  ('A4-032', 'A4', 32, 'Magby', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_032_EN_SM.webp'),
  ('A4-033', 'A4', 33, 'Entei', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_033_EN_SM.webp'),
  ('A4-034', 'A4', 34, 'Ho-Oh ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_034_EN_SM.webp'),
  ('A4-035', 'A4', 35, 'Darumaka', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_035_EN_SM.webp'),
  ('A4-036', 'A4', 36, 'Darmanitan', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_036_EN_SM.webp'),
  ('A4-037', 'A4', 37, 'Heatmor', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_037_EN_SM.webp'),
  ('A4-038', 'A4', 38, 'Poliwag', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_038_EN_SM.webp'),
  ('A4-039', 'A4', 39, 'Poliwhirl', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_039_EN_SM.webp'),
  ('A4-040', 'A4', 40, 'Politoed', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_040_EN_SM.webp'),
  ('A4-041', 'A4', 41, 'Horsea', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_041_EN_SM.webp'),
  ('A4-042', 'A4', 42, 'Seadra', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_042_EN_SM.webp'),
  ('A4-043', 'A4', 43, 'Kingdra ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_043_EN_SM.webp'),
  ('A4-044', 'A4', 44, 'Magikarp', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_044_EN_SM.webp'),
  ('A4-045', 'A4', 45, 'Gyarados', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_045_EN_SM.webp'),
  ('A4-046', 'A4', 46, 'Totodile', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_046_EN_SM.webp'),
  ('A4-047', 'A4', 47, 'Croconaw', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_047_EN_SM.webp'),
  ('A4-048', 'A4', 48, 'Feraligatr', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_048_EN_SM.webp'),
  ('A4-049', 'A4', 49, 'Marill', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_049_EN_SM.webp'),
  ('A4-050', 'A4', 50, 'Azumarill', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_050_EN_SM.webp'),
  ('A4-051', 'A4', 51, 'Wooper', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_051_EN_SM.webp'),
  ('A4-052', 'A4', 52, 'Quagsire', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_052_EN_SM.webp'),
  ('A4-053', 'A4', 53, 'Qwilfish', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_053_EN_SM.webp'),
  ('A4-054', 'A4', 54, 'Corsola', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_054_EN_SM.webp'),
  ('A4-055', 'A4', 55, 'Remoraid', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_055_EN_SM.webp'),
  ('A4-056', 'A4', 56, 'Octillery', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_056_EN_SM.webp'),
  ('A4-057', 'A4', 57, 'Delibird', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_057_EN_SM.webp'),
  ('A4-058', 'A4', 58, 'Mantine', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_058_EN_SM.webp'),
  ('A4-059', 'A4', 59, 'Suicune', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_059_EN_SM.webp'),
  ('A4-060', 'A4', 60, 'Corphish', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_060_EN_SM.webp'),
  ('A4-061', 'A4', 61, 'Crawdaunt', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_061_EN_SM.webp'),
  ('A4-062', 'A4', 62, 'Ducklett', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_062_EN_SM.webp'),
  ('A4-063', 'A4', 63, 'Swanna', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_063_EN_SM.webp'),
  ('A4-064', 'A4', 64, 'Chinchou', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_064_EN_SM.webp'),
  ('A4-065', 'A4', 65, 'Lanturn ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_065_EN_SM.webp'),
  ('A4-066', 'A4', 66, 'Pichu', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_066_EN_SM.webp'),
  ('A4-067', 'A4', 67, 'Mareep', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_067_EN_SM.webp'),
  ('A4-068', 'A4', 68, 'Flaaffy', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_068_EN_SM.webp'),
  ('A4-069', 'A4', 69, 'Ampharos', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_069_EN_SM.webp'),
  ('A4-070', 'A4', 70, 'Elekid', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_070_EN_SM.webp'),
  ('A4-071', 'A4', 71, 'Raikou', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_071_EN_SM.webp'),
  ('A4-072', 'A4', 72, 'Emolga', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_072_EN_SM.webp'),
  ('A4-073', 'A4', 73, 'Slowpoke', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_073_EN_SM.webp'),
  ('A4-074', 'A4', 74, 'Slowking', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_074_EN_SM.webp'),
  ('A4-075', 'A4', 75, 'Smoochum', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_075_EN_SM.webp'),
  ('A4-076', 'A4', 76, 'Jynx', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_076_EN_SM.webp'),
  ('A4-077', 'A4', 77, 'Cleffa', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_077_EN_SM.webp'),
  ('A4-078', 'A4', 78, 'Togepi', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_078_EN_SM.webp'),
  ('A4-079', 'A4', 79, 'Togetic', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_079_EN_SM.webp'),
  ('A4-080', 'A4', 80, 'Togekiss', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_080_EN_SM.webp'),
  ('A4-081', 'A4', 81, 'Natu', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_081_EN_SM.webp'),
  ('A4-082', 'A4', 82, 'Xatu', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_082_EN_SM.webp'),
  ('A4-083', 'A4', 83, 'Espeon ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_083_EN_SM.webp'),
  ('A4-084', 'A4', 84, 'Unown', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_084_EN_SM.webp'),
  ('A4-085', 'A4', 85, 'Unown', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_085_EN_SM.webp'),
  ('A4-086', 'A4', 86, 'Wobbuffet', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_086_EN_SM.webp'),
  ('A4-087', 'A4', 87, 'Girafarig', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_087_EN_SM.webp'),
  ('A4-088', 'A4', 88, 'Snubbull', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_088_EN_SM.webp'),
  ('A4-089', 'A4', 89, 'Granbull', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_089_EN_SM.webp'),
  ('A4-090', 'A4', 90, 'Munna', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_090_EN_SM.webp'),
  ('A4-091', 'A4', 91, 'Musharna', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_091_EN_SM.webp'),
  ('A4-092', 'A4', 92, 'Onix', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_092_EN_SM.webp'),
  ('A4-093', 'A4', 93, 'Sudowoodo', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_093_EN_SM.webp'),
  ('A4-094', 'A4', 94, 'Gligar', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_094_EN_SM.webp'),
  ('A4-095', 'A4', 95, 'Gliscor', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_095_EN_SM.webp'),
  ('A4-096', 'A4', 96, 'Swinub', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_096_EN_SM.webp'),
  ('A4-097', 'A4', 97, 'Piloswine', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_097_EN_SM.webp'),
  ('A4-098', 'A4', 98, 'Mamoswine', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_098_EN_SM.webp'),
  ('A4-099', 'A4', 99, 'Phanpy', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_099_EN_SM.webp'),
  ('A4-100', 'A4', 100, 'Donphan ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_100_EN_SM.webp'),
  ('A4-101', 'A4', 101, 'Tyrogue', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_101_EN_SM.webp'),
  ('A4-102', 'A4', 102, 'Hitmontop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_102_EN_SM.webp'),
  ('A4-103', 'A4', 103, 'Larvitar', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_103_EN_SM.webp'),
  ('A4-104', 'A4', 104, 'Pupitar', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_104_EN_SM.webp'),
  ('A4-105', 'A4', 105, 'Binacle', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_105_EN_SM.webp'),
  ('A4-106', 'A4', 106, 'Barbaracle', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_106_EN_SM.webp'),
  ('A4-107', 'A4', 107, 'Zubat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_107_EN_SM.webp'),
  ('A4-108', 'A4', 108, 'Golbat', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_108_EN_SM.webp'),
  ('A4-109', 'A4', 109, 'Crobat ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_109_EN_SM.webp'),
  ('A4-110', 'A4', 110, 'Spinarak', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_110_EN_SM.webp'),
  ('A4-111', 'A4', 111, 'Ariados', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_111_EN_SM.webp'),
  ('A4-112', 'A4', 112, 'Umbreon ex', 'pokemon', 'darkness', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_112_EN_SM.webp'),
  ('A4-113', 'A4', 113, 'Murkrow', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_113_EN_SM.webp'),
  ('A4-114', 'A4', 114, 'Honchkrow', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_114_EN_SM.webp'),
  ('A4-115', 'A4', 115, 'Sneasel', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_115_EN_SM.webp'),
  ('A4-116', 'A4', 116, 'Weavile', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_116_EN_SM.webp'),
  ('A4-117', 'A4', 117, 'Houndour', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_117_EN_SM.webp'),
  ('A4-118', 'A4', 118, 'Houndoom', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_118_EN_SM.webp'),
  ('A4-119', 'A4', 119, 'Tyranitar', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_119_EN_SM.webp'),
  ('A4-120', 'A4', 120, 'Absol', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_120_EN_SM.webp'),
  ('A4-121', 'A4', 121, 'Forretress', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_121_EN_SM.webp'),
  ('A4-122', 'A4', 122, 'Steelix', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_122_EN_SM.webp'),
  ('A4-123', 'A4', 123, 'Scizor', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_123_EN_SM.webp'),
  ('A4-124', 'A4', 124, 'Skarmory ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_124_EN_SM.webp'),
  ('A4-125', 'A4', 125, 'Mawile', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_125_EN_SM.webp'),
  ('A4-126', 'A4', 126, 'Klink', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_126_EN_SM.webp'),
  ('A4-127', 'A4', 127, 'Klang', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_127_EN_SM.webp'),
  ('A4-128', 'A4', 128, 'Klinklang', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_128_EN_SM.webp'),
  ('A4-129', 'A4', 129, 'Spearow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_129_EN_SM.webp'),
  ('A4-130', 'A4', 130, 'Fearow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_130_EN_SM.webp'),
  ('A4-131', 'A4', 131, 'Chansey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_131_EN_SM.webp'),
  ('A4-132', 'A4', 132, 'Blissey', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_132_EN_SM.webp'),
  ('A4-133', 'A4', 133, 'Kangaskhan', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_133_EN_SM.webp'),
  ('A4-134', 'A4', 134, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_134_EN_SM.webp'),
  ('A4-135', 'A4', 135, 'Porygon', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_135_EN_SM.webp'),
  ('A4-136', 'A4', 136, 'Porygon2', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_136_EN_SM.webp'),
  ('A4-137', 'A4', 137, 'Porygon-Z', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_137_EN_SM.webp'),
  ('A4-138', 'A4', 138, 'Sentret', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_138_EN_SM.webp'),
  ('A4-139', 'A4', 139, 'Furret', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_139_EN_SM.webp'),
  ('A4-140', 'A4', 140, 'Hoothoot', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_140_EN_SM.webp'),
  ('A4-141', 'A4', 141, 'Noctowl', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_141_EN_SM.webp'),
  ('A4-142', 'A4', 142, 'Aipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_142_EN_SM.webp'),
  ('A4-143', 'A4', 143, 'Ambipom', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_143_EN_SM.webp'),
  ('A4-144', 'A4', 144, 'Dunsparce', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_144_EN_SM.webp'),
  ('A4-145', 'A4', 145, 'Teddiursa', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_145_EN_SM.webp'),
  ('A4-146', 'A4', 146, 'Ursaring', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_146_EN_SM.webp'),
  ('A4-147', 'A4', 147, 'Stantler', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_147_EN_SM.webp'),
  ('A4-148', 'A4', 148, 'Smeargle', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_148_EN_SM.webp'),
  ('A4-149', 'A4', 149, 'Lugia ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_149_EN_SM.webp'),
  ('A4-150', 'A4', 150, 'Bouffalant', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_150_EN_SM.webp'),
  ('A4-151', 'A4', 151, 'Elemental Switch', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_151_EN_SM.webp'),
  ('A4-152', 'A4', 152, 'Squirt Bottle', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_152_EN_SM.webp'),
  ('A4-153', 'A4', 153, 'Steel Apron', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_153_EN_SM.webp'),
  ('A4-154', 'A4', 154, 'Dark Pendant', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_154_EN_SM.webp'),
  ('A4-155', 'A4', 155, 'Rescue Scarf', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_155_EN_SM.webp'),
  ('A4-156', 'A4', 156, 'Will', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_156_EN_SM.webp'),
  ('A4-157', 'A4', 157, 'Lyra', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_157_EN_SM.webp'),
  ('A4-158', 'A4', 158, 'Silver', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_158_EN_SM.webp'),
  ('A4-159', 'A4', 159, 'Fisher', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_159_EN_SM.webp'),
  ('A4-160', 'A4', 160, 'Jasmine', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_160_EN_SM.webp'),
  ('A4-161', 'A4', 161, 'Hiker', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_161_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A4-162', 'A4', 162, 'Chikorita', 'pokemon', 'grass', null, 'star_1', 'A4-008', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_162_EN_SM.webp'),
  ('A4-163', 'A4', 163, 'Bellossom', 'pokemon', 'grass', null, 'star_1', 'A4-003', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_163_EN_SM.webp'),
  ('A4-164', 'A4', 164, 'Heracross', 'pokemon', 'grass', null, 'star_1', 'A4-022', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_164_EN_SM.webp'),
  ('A4-165', 'A4', 165, 'Cyndaquil', 'pokemon', 'fire', null, 'star_1', 'A4-027', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_165_EN_SM.webp'),
  ('A4-166', 'A4', 166, 'Magby', 'pokemon', 'fire', null, 'star_1', 'A4-032', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_166_EN_SM.webp'),
  ('A4-167', 'A4', 167, 'Totodile', 'pokemon', 'water', null, 'star_1', 'A4-046', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_167_EN_SM.webp'),
  ('A4-168', 'A4', 168, 'Qwilfish', 'pokemon', 'water', null, 'star_1', 'A4-053', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_168_EN_SM.webp'),
  ('A4-169', 'A4', 169, 'Octillery', 'pokemon', 'water', null, 'star_1', 'A4-056', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_169_EN_SM.webp'),
  ('A4-170', 'A4', 170, 'Delibird', 'pokemon', 'water', null, 'star_1', 'A4-057', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_170_EN_SM.webp'),
  ('A4-171', 'A4', 171, 'Pichu', 'pokemon', 'lightning', null, 'star_1', 'A4-066', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_171_EN_SM.webp'),
  ('A4-172', 'A4', 172, 'Ampharos', 'pokemon', 'lightning', null, 'star_1', 'A4-069', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_172_EN_SM.webp'),
  ('A4-173', 'A4', 173, 'Togepi', 'pokemon', 'psychic', null, 'star_1', 'A4-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_173_EN_SM.webp'),
  ('A4-174', 'A4', 174, 'Xatu', 'pokemon', 'psychic', null, 'star_1', 'A4-082', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_174_EN_SM.webp'),
  ('A4-175', 'A4', 175, 'Wobbuffet', 'pokemon', 'psychic', null, 'star_1', 'A4-086', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_175_EN_SM.webp'),
  ('A4-176', 'A4', 176, 'Gligar', 'pokemon', 'fighting', null, 'star_1', 'A4-094', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_176_EN_SM.webp'),
  ('A4-177', 'A4', 177, 'Spinarak', 'pokemon', 'darkness', null, 'star_1', 'A4-110', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_177_EN_SM.webp'),
  ('A4-178', 'A4', 178, 'Murkrow', 'pokemon', 'darkness', null, 'star_1', 'A4-113', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_178_EN_SM.webp'),
  ('A4-179', 'A4', 179, 'Tyranitar', 'pokemon', 'darkness', null, 'star_1', 'A4-119', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_179_EN_SM.webp'),
  ('A4-180', 'A4', 180, 'Scizor', 'pokemon', 'metal', null, 'star_1', 'A4-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_180_EN_SM.webp'),
  ('A4-181', 'A4', 181, 'Sentret', 'pokemon', 'colorless', null, 'star_1', 'A4-138', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_181_EN_SM.webp'),
  ('A4-182', 'A4', 182, 'Hoothoot', 'pokemon', 'colorless', null, 'star_1', 'A4-140', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_182_EN_SM.webp'),
  ('A4-183', 'A4', 183, 'Stantler', 'pokemon', 'colorless', null, 'star_1', 'A4-147', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_183_EN_SM.webp'),
  ('A4-184', 'A4', 184, 'Smeargle', 'pokemon', 'colorless', null, 'star_1', 'A4-148', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_184_EN_SM.webp'),
  ('A4-185', 'A4', 185, 'Blissey', 'pokemon', 'colorless', null, 'star_1', 'A4-132', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_185_EN_SM.webp'),
  ('A4-186', 'A4', 186, 'Shuckle ex', 'pokemon', 'grass', null, 'star_2', 'A4-021', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_186_EN_SM.webp'),
  ('A4-187', 'A4', 187, 'Ho-Oh ex', 'pokemon', 'fire', null, 'star_2', 'A4-034', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_187_EN_SM.webp'),
  ('A4-188', 'A4', 188, 'Kingdra ex', 'pokemon', 'water', null, 'star_2', 'A4-043', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_188_EN_SM.webp'),
  ('A4-189', 'A4', 189, 'Lanturn ex', 'pokemon', 'lightning', null, 'star_2', 'A4-065', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_189_EN_SM.webp'),
  ('A4-190', 'A4', 190, 'Espeon ex', 'pokemon', 'psychic', null, 'star_2', 'A4-083', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_190_EN_SM.webp'),
  ('A4-191', 'A4', 191, 'Donphan ex', 'pokemon', 'fighting', null, 'star_2', 'A4-100', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_191_EN_SM.webp'),
  ('A4-192', 'A4', 192, 'Crobat ex', 'pokemon', 'darkness', null, 'star_2', 'A4-109', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_192_EN_SM.webp'),
  ('A4-193', 'A4', 193, 'Umbreon ex', 'pokemon', 'darkness', null, 'star_2', 'A4-112', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_193_EN_SM.webp'),
  ('A4-194', 'A4', 194, 'Skarmory ex', 'pokemon', 'metal', null, 'star_2', 'A4-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_194_EN_SM.webp'),
  ('A4-195', 'A4', 195, 'Lugia ex', 'pokemon', 'colorless', null, 'star_2', 'A4-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_195_EN_SM.webp'),
  ('A4-196', 'A4', 196, 'Will', 'trainer', null, 'supporter', 'star_2', 'A4-156', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_196_EN_SM.webp'),
  ('A4-197', 'A4', 197, 'Lyra', 'trainer', null, 'supporter', 'star_2', 'A4-157', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_197_EN_SM.webp'),
  ('A4-198', 'A4', 198, 'Silver', 'trainer', null, 'supporter', 'star_2', 'A4-158', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_198_EN_SM.webp'),
  ('A4-199', 'A4', 199, 'Fisher', 'trainer', null, 'supporter', 'star_2', 'A4-159', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_199_EN_SM.webp'),
  ('A4-200', 'A4', 200, 'Jasmine', 'trainer', null, 'supporter', 'star_2', 'A4-160', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_200_EN_SM.webp'),
  ('A4-201', 'A4', 201, 'Hiker', 'trainer', null, 'supporter', 'star_2', 'A4-161', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_201_EN_SM.webp'),
  ('A4-202', 'A4', 202, 'Shuckle ex', 'pokemon', 'grass', null, 'star_2', 'A4-021', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_202_EN_SM.webp'),
  ('A4-203', 'A4', 203, 'Kingdra ex', 'pokemon', 'water', null, 'star_2', 'A4-043', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_203_EN_SM.webp'),
  ('A4-204', 'A4', 204, 'Lanturn ex', 'pokemon', 'lightning', null, 'star_2', 'A4-065', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_204_EN_SM.webp'),
  ('A4-205', 'A4', 205, 'Espeon ex', 'pokemon', 'psychic', null, 'star_2', 'A4-083', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_205_EN_SM.webp'),
  ('A4-206', 'A4', 206, 'Donphan ex', 'pokemon', 'fighting', null, 'star_2', 'A4-100', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_206_EN_SM.webp'),
  ('A4-207', 'A4', 207, 'Crobat ex', 'pokemon', 'darkness', null, 'star_2', 'A4-109', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_207_EN_SM.webp'),
  ('A4-208', 'A4', 208, 'Umbreon ex', 'pokemon', 'darkness', null, 'star_2', 'A4-112', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_208_EN_SM.webp'),
  ('A4-209', 'A4', 209, 'Skarmory ex', 'pokemon', 'metal', null, 'star_2', 'A4-124', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_209_EN_SM.webp'),
  ('A4-210', 'A4', 210, 'Ho-Oh ex', 'pokemon', 'fire', null, 'star_3', 'A4-034', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_210_EN_SM.webp'),
  ('A4-211', 'A4', 211, 'Lugia ex', 'pokemon', 'colorless', null, 'star_3', 'A4-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_211_EN_SM.webp'),
  ('A4-212', 'A4', 212, 'Yanma', 'pokemon', 'grass', null, 'star_1', 'A4-018', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_212_EN_SM.webp'),
  ('A4-213', 'A4', 213, 'Flareon', 'pokemon', 'fire', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_213_EN_SM.webp'),
  ('A4-214', 'A4', 214, 'Magikarp', 'pokemon', 'water', null, 'star_1', 'A4-044', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_214_EN_SM.webp'),
  ('A4-215', 'A4', 215, 'Gyarados', 'pokemon', 'water', null, 'star_1', 'A4-045', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_215_EN_SM.webp'),
  ('A4-216', 'A4', 216, 'Vaporeon', 'pokemon', 'water', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_216_EN_SM.webp'),
  ('A4-217', 'A4', 217, 'Magnemite', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_217_EN_SM.webp'),
  ('A4-218', 'A4', 218, 'Magneton', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_218_EN_SM.webp'),
  ('A4-219', 'A4', 219, 'Jolteon', 'pokemon', 'lightning', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_219_EN_SM.webp'),
  ('A4-220', 'A4', 220, 'Misdreavus', 'pokemon', 'psychic', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_220_EN_SM.webp'),
  ('A4-221', 'A4', 221, 'Mankey', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_221_EN_SM.webp'),
  ('A4-222', 'A4', 222, 'Primeape', 'pokemon', 'fighting', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_222_EN_SM.webp'),
  ('A4-223', 'A4', 223, 'Nidoran♀', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_223_EN_SM.webp'),
  ('A4-224', 'A4', 224, 'Nidorina', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_224_EN_SM.webp'),
  ('A4-225', 'A4', 225, 'Nidoqueen', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_225_EN_SM.webp'),
  ('A4-226', 'A4', 226, 'Nidoran♂', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_226_EN_SM.webp'),
  ('A4-227', 'A4', 227, 'Nidorino', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_227_EN_SM.webp'),
  ('A4-228', 'A4', 228, 'Nidoking', 'pokemon', 'darkness', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_228_EN_SM.webp'),
  ('A4-229', 'A4', 229, 'Sneasel', 'pokemon', 'darkness', null, 'star_1', 'A4-115', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_229_EN_SM.webp'),
  ('A4-230', 'A4', 230, 'Lickitung', 'pokemon', 'colorless', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_230_EN_SM.webp'),
  ('A4-231', 'A4', 231, 'Eevee', 'pokemon', 'colorless', null, 'star_1', 'A4-134', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_231_EN_SM.webp'),
  ('A4-232', 'A4', 232, 'Yanmega ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_232_EN_SM.webp'),
  ('A4-233', 'A4', 233, 'Leafeon ex', 'pokemon', 'grass', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_233_EN_SM.webp'),
  ('A4-234', 'A4', 234, 'Gyarados ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_234_EN_SM.webp'),
  ('A4-235', 'A4', 235, 'Glaceon ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_235_EN_SM.webp'),
  ('A4-236', 'A4', 236, 'Pachirisu ex', 'pokemon', 'lightning', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_236_EN_SM.webp'),
  ('A4-237', 'A4', 237, 'Mismagius ex', 'pokemon', 'psychic', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_237_EN_SM.webp'),
  ('A4-238', 'A4', 238, 'Weavile ex', 'pokemon', 'darkness', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_238_EN_SM.webp'),
  ('A4-239', 'A4', 239, 'Lickilicky ex', 'pokemon', 'colorless', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_239_EN_SM.webp'),
  ('A4-240', 'A4', 240, 'Ho-Oh ex', 'pokemon', 'fire', null, 'crown', 'A4-034', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_240_EN_SM.webp'),
  ('A4-241', 'A4', 241, 'Lugia ex', 'pokemon', 'colorless', null, 'crown', 'A4-149', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_241_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 241 cards, numbered 1 through 241.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'A4';
