-- Genetic Apex (A1): 226 main-set cards and 60 secret cards.
-- Source checked 2026-06-24: https://pocket.limitlesstcg.com/cards/A1
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A1-001', 'A1', 1, 'Bulbasaur', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_001_EN_SM.webp'),
  ('A1-002', 'A1', 2, 'Ivysaur', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_002_EN_SM.webp'),
  ('A1-003', 'A1', 3, 'Venusaur', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_003_EN_SM.webp'),
  ('A1-004', 'A1', 4, 'Venusaur ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_004_EN_SM.webp'),
  ('A1-005', 'A1', 5, 'Caterpie', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_005_EN_SM.webp'),
  ('A1-006', 'A1', 6, 'Metapod', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_006_EN_SM.webp'),
  ('A1-007', 'A1', 7, 'Butterfree', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_007_EN_SM.webp'),
  ('A1-008', 'A1', 8, 'Weedle', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_008_EN_SM.webp'),
  ('A1-009', 'A1', 9, 'Kakuna', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_009_EN_SM.webp'),
  ('A1-010', 'A1', 10, 'Beedrill', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_010_EN_SM.webp'),
  ('A1-011', 'A1', 11, 'Oddish', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_011_EN_SM.webp'),
  ('A1-012', 'A1', 12, 'Gloom', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_012_EN_SM.webp'),
  ('A1-013', 'A1', 13, 'Vileplume', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_013_EN_SM.webp'),
  ('A1-014', 'A1', 14, 'Paras', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_014_EN_SM.webp'),
  ('A1-015', 'A1', 15, 'Parasect', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_015_EN_SM.webp'),
  ('A1-016', 'A1', 16, 'Venonat', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_016_EN_SM.webp'),
  ('A1-017', 'A1', 17, 'Venomoth', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_017_EN_SM.webp'),
  ('A1-018', 'A1', 18, 'Bellsprout', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_018_EN_SM.webp'),
  ('A1-019', 'A1', 19, 'Weepinbell', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_019_EN_SM.webp'),
  ('A1-020', 'A1', 20, 'Victreebel', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_020_EN_SM.webp'),
  ('A1-021', 'A1', 21, 'Exeggcute', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_021_EN_SM.webp'),
  ('A1-022', 'A1', 22, 'Exeggutor', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_022_EN_SM.webp'),
  ('A1-023', 'A1', 23, 'Exeggutor ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_023_EN_SM.webp'),
  ('A1-024', 'A1', 24, 'Tangela', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_024_EN_SM.webp'),
  ('A1-025', 'A1', 25, 'Scyther', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_025_EN_SM.webp'),
  ('A1-026', 'A1', 26, 'Pinsir', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_026_EN_SM.webp'),
  ('A1-027', 'A1', 27, 'Cottonee', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_027_EN_SM.webp'),
  ('A1-028', 'A1', 28, 'Whimsicott', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_028_EN_SM.webp'),
  ('A1-029', 'A1', 29, 'Petilil', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_029_EN_SM.webp'),
  ('A1-030', 'A1', 30, 'Lilligant', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_030_EN_SM.webp'),
  ('A1-031', 'A1', 31, 'Skiddo', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_031_EN_SM.webp'),
  ('A1-032', 'A1', 32, 'Gogoat', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_032_EN_SM.webp'),
  ('A1-033', 'A1', 33, 'Charmander', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_033_EN_SM.webp'),
  ('A1-034', 'A1', 34, 'Charmeleon', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_034_EN_SM.webp'),
  ('A1-035', 'A1', 35, 'Charizard', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_035_EN_SM.webp'),
  ('A1-036', 'A1', 36, 'Charizard ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_036_EN_SM.webp'),
  ('A1-037', 'A1', 37, 'Vulpix', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_037_EN_SM.webp'),
  ('A1-038', 'A1', 38, 'Ninetales', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_038_EN_SM.webp'),
  ('A1-039', 'A1', 39, 'Growlithe', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_039_EN_SM.webp'),
  ('A1-040', 'A1', 40, 'Arcanine', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_040_EN_SM.webp'),
  ('A1-041', 'A1', 41, 'Arcanine ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_041_EN_SM.webp'),
  ('A1-042', 'A1', 42, 'Ponyta', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_042_EN_SM.webp'),
  ('A1-043', 'A1', 43, 'Rapidash', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_043_EN_SM.webp'),
  ('A1-044', 'A1', 44, 'Magmar', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_044_EN_SM.webp'),
  ('A1-045', 'A1', 45, 'Flareon', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_045_EN_SM.webp'),
  ('A1-046', 'A1', 46, 'Moltres', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_046_EN_SM.webp'),
  ('A1-047', 'A1', 47, 'Moltres ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_047_EN_SM.webp'),
  ('A1-048', 'A1', 48, 'Heatmor', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_048_EN_SM.webp'),
  ('A1-049', 'A1', 49, 'Salandit', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_049_EN_SM.webp'),
  ('A1-050', 'A1', 50, 'Salazzle', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_050_EN_SM.webp'),
  ('A1-051', 'A1', 51, 'Sizzlipede', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_051_EN_SM.webp'),
  ('A1-052', 'A1', 52, 'Centiskorch', 'pokemon', 'fire', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_052_EN_SM.webp'),
  ('A1-053', 'A1', 53, 'Squirtle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_053_EN_SM.webp'),
  ('A1-054', 'A1', 54, 'Wartortle', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_054_EN_SM.webp'),
  ('A1-055', 'A1', 55, 'Blastoise', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_055_EN_SM.webp'),
  ('A1-056', 'A1', 56, 'Blastoise ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_056_EN_SM.webp'),
  ('A1-057', 'A1', 57, 'Psyduck', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_057_EN_SM.webp'),
  ('A1-058', 'A1', 58, 'Golduck', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_058_EN_SM.webp'),
  ('A1-059', 'A1', 59, 'Poliwag', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_059_EN_SM.webp'),
  ('A1-060', 'A1', 60, 'Poliwhirl', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_060_EN_SM.webp'),
  ('A1-061', 'A1', 61, 'Poliwrath', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_061_EN_SM.webp'),
  ('A1-062', 'A1', 62, 'Tentacool', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_062_EN_SM.webp'),
  ('A1-063', 'A1', 63, 'Tentacruel', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_063_EN_SM.webp'),
  ('A1-064', 'A1', 64, 'Seel', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_064_EN_SM.webp'),
  ('A1-065', 'A1', 65, 'Dewgong', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_065_EN_SM.webp'),
  ('A1-066', 'A1', 66, 'Shellder', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_066_EN_SM.webp'),
  ('A1-067', 'A1', 67, 'Cloyster', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_067_EN_SM.webp'),
  ('A1-068', 'A1', 68, 'Krabby', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_068_EN_SM.webp'),
  ('A1-069', 'A1', 69, 'Kingler', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_069_EN_SM.webp'),
  ('A1-070', 'A1', 70, 'Horsea', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_070_EN_SM.webp'),
  ('A1-071', 'A1', 71, 'Seadra', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_071_EN_SM.webp'),
  ('A1-072', 'A1', 72, 'Goldeen', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_072_EN_SM.webp'),
  ('A1-073', 'A1', 73, 'Seaking', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_073_EN_SM.webp'),
  ('A1-074', 'A1', 74, 'Staryu', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_074_EN_SM.webp'),
  ('A1-075', 'A1', 75, 'Starmie', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_075_EN_SM.webp'),
  ('A1-076', 'A1', 76, 'Starmie ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_076_EN_SM.webp'),
  ('A1-077', 'A1', 77, 'Magikarp', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_077_EN_SM.webp'),
  ('A1-078', 'A1', 78, 'Gyarados', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_078_EN_SM.webp'),
  ('A1-079', 'A1', 79, 'Lapras', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_079_EN_SM.webp'),
  ('A1-080', 'A1', 80, 'Vaporeon', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_080_EN_SM.webp'),
  ('A1-081', 'A1', 81, 'Omanyte', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_081_EN_SM.webp'),
  ('A1-082', 'A1', 82, 'Omastar', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_082_EN_SM.webp'),
  ('A1-083', 'A1', 83, 'Articuno', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_083_EN_SM.webp'),
  ('A1-084', 'A1', 84, 'Articuno ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_084_EN_SM.webp'),
  ('A1-085', 'A1', 85, 'Ducklett', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_085_EN_SM.webp'),
  ('A1-086', 'A1', 86, 'Swanna', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_086_EN_SM.webp'),
  ('A1-087', 'A1', 87, 'Froakie', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_087_EN_SM.webp'),
  ('A1-088', 'A1', 88, 'Frogadier', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_088_EN_SM.webp'),
  ('A1-089', 'A1', 89, 'Greninja', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_089_EN_SM.webp'),
  ('A1-090', 'A1', 90, 'Pyukumuku', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_090_EN_SM.webp'),
  ('A1-091', 'A1', 91, 'Bruxish', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_091_EN_SM.webp'),
  ('A1-092', 'A1', 92, 'Snom', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_092_EN_SM.webp'),
  ('A1-093', 'A1', 93, 'Frosmoth', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_093_EN_SM.webp'),
  ('A1-094', 'A1', 94, 'Pikachu', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_094_EN_SM.webp'),
  ('A1-095', 'A1', 95, 'Raichu', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_095_EN_SM.webp'),
  ('A1-096', 'A1', 96, 'Pikachu ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_096_EN_SM.webp'),
  ('A1-097', 'A1', 97, 'Magnemite', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_097_EN_SM.webp'),
  ('A1-098', 'A1', 98, 'Magneton', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_098_EN_SM.webp'),
  ('A1-099', 'A1', 99, 'Voltorb', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_099_EN_SM.webp'),
  ('A1-100', 'A1', 100, 'Electrode', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_100_EN_SM.webp'),
  ('A1-101', 'A1', 101, 'Electabuzz', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_101_EN_SM.webp'),
  ('A1-102', 'A1', 102, 'Jolteon', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_102_EN_SM.webp'),
  ('A1-103', 'A1', 103, 'Zapdos', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_103_EN_SM.webp'),
  ('A1-104', 'A1', 104, 'Zapdos ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_104_EN_SM.webp'),
  ('A1-105', 'A1', 105, 'Blitzle', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_105_EN_SM.webp'),
  ('A1-106', 'A1', 106, 'Zebstrika', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_106_EN_SM.webp'),
  ('A1-107', 'A1', 107, 'Tynamo', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_107_EN_SM.webp'),
  ('A1-108', 'A1', 108, 'Eelektrik', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_108_EN_SM.webp'),
  ('A1-109', 'A1', 109, 'Eelektross', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_109_EN_SM.webp'),
  ('A1-110', 'A1', 110, 'Helioptile', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_110_EN_SM.webp'),
  ('A1-111', 'A1', 111, 'Heliolisk', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_111_EN_SM.webp'),
  ('A1-112', 'A1', 112, 'Pincurchin', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_112_EN_SM.webp'),
  ('A1-113', 'A1', 113, 'Clefairy', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_113_EN_SM.webp'),
  ('A1-114', 'A1', 114, 'Clefable', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_114_EN_SM.webp'),
  ('A1-115', 'A1', 115, 'Abra', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_115_EN_SM.webp'),
  ('A1-116', 'A1', 116, 'Kadabra', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_116_EN_SM.webp'),
  ('A1-117', 'A1', 117, 'Alakazam', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_117_EN_SM.webp'),
  ('A1-118', 'A1', 118, 'Slowpoke', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_118_EN_SM.webp'),
  ('A1-119', 'A1', 119, 'Slowbro', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_119_EN_SM.webp'),
  ('A1-120', 'A1', 120, 'Gastly', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_120_EN_SM.webp'),
  ('A1-121', 'A1', 121, 'Haunter', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_121_EN_SM.webp'),
  ('A1-122', 'A1', 122, 'Gengar', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_122_EN_SM.webp'),
  ('A1-123', 'A1', 123, 'Gengar ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_123_EN_SM.webp'),
  ('A1-124', 'A1', 124, 'Drowzee', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_124_EN_SM.webp'),
  ('A1-125', 'A1', 125, 'Hypno', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_125_EN_SM.webp'),
  ('A1-126', 'A1', 126, 'Mr. Mime', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_126_EN_SM.webp'),
  ('A1-127', 'A1', 127, 'Jynx', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_127_EN_SM.webp'),
  ('A1-128', 'A1', 128, 'Mewtwo', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_128_EN_SM.webp'),
  ('A1-129', 'A1', 129, 'Mewtwo ex', 'pokemon', 'psychic', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_129_EN_SM.webp'),
  ('A1-130', 'A1', 130, 'Ralts', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_130_EN_SM.webp'),
  ('A1-131', 'A1', 131, 'Kirlia', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_131_EN_SM.webp'),
  ('A1-132', 'A1', 132, 'Gardevoir', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_132_EN_SM.webp'),
  ('A1-133', 'A1', 133, 'Woobat', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_133_EN_SM.webp'),
  ('A1-134', 'A1', 134, 'Swoobat', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_134_EN_SM.webp'),
  ('A1-135', 'A1', 135, 'Golett', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_135_EN_SM.webp'),
  ('A1-136', 'A1', 136, 'Golurk', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_136_EN_SM.webp'),
  ('A1-137', 'A1', 137, 'Sandshrew', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_137_EN_SM.webp'),
  ('A1-138', 'A1', 138, 'Sandslash', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_138_EN_SM.webp'),
  ('A1-139', 'A1', 139, 'Diglett', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_139_EN_SM.webp'),
  ('A1-140', 'A1', 140, 'Dugtrio', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_140_EN_SM.webp'),
  ('A1-141', 'A1', 141, 'Mankey', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_141_EN_SM.webp'),
  ('A1-142', 'A1', 142, 'Primeape', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_142_EN_SM.webp'),
  ('A1-143', 'A1', 143, 'Machop', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_143_EN_SM.webp'),
  ('A1-144', 'A1', 144, 'Machoke', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_144_EN_SM.webp'),
  ('A1-145', 'A1', 145, 'Machamp', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_145_EN_SM.webp'),
  ('A1-146', 'A1', 146, 'Machamp ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_146_EN_SM.webp'),
  ('A1-147', 'A1', 147, 'Geodude', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_147_EN_SM.webp'),
  ('A1-148', 'A1', 148, 'Graveler', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_148_EN_SM.webp'),
  ('A1-149', 'A1', 149, 'Golem', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_149_EN_SM.webp'),
  ('A1-150', 'A1', 150, 'Onix', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_150_EN_SM.webp'),
  ('A1-151', 'A1', 151, 'Cubone', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_151_EN_SM.webp'),
  ('A1-152', 'A1', 152, 'Marowak', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_152_EN_SM.webp'),
  ('A1-153', 'A1', 153, 'Marowak ex', 'pokemon', 'fighting', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_153_EN_SM.webp'),
  ('A1-154', 'A1', 154, 'Hitmonlee', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_154_EN_SM.webp'),
  ('A1-155', 'A1', 155, 'Hitmonchan', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_155_EN_SM.webp'),
  ('A1-156', 'A1', 156, 'Rhyhorn', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_156_EN_SM.webp'),
  ('A1-157', 'A1', 157, 'Rhydon', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_157_EN_SM.webp'),
  ('A1-158', 'A1', 158, 'Kabuto', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_158_EN_SM.webp'),
  ('A1-159', 'A1', 159, 'Kabutops', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_159_EN_SM.webp'),
  ('A1-160', 'A1', 160, 'Mienfoo', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_160_EN_SM.webp'),
  ('A1-161', 'A1', 161, 'Mienshao', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_161_EN_SM.webp'),
  ('A1-162', 'A1', 162, 'Clobbopus', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_162_EN_SM.webp'),
  ('A1-163', 'A1', 163, 'Grapploct', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_163_EN_SM.webp'),
  ('A1-164', 'A1', 164, 'Ekans', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_164_EN_SM.webp'),
  ('A1-165', 'A1', 165, 'Arbok', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_165_EN_SM.webp'),
  ('A1-166', 'A1', 166, 'Nidoran♀', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_166_EN_SM.webp'),
  ('A1-167', 'A1', 167, 'Nidorina', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_167_EN_SM.webp'),
  ('A1-168', 'A1', 168, 'Nidoqueen', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_168_EN_SM.webp'),
  ('A1-169', 'A1', 169, 'Nidoran♂', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_169_EN_SM.webp'),
  ('A1-170', 'A1', 170, 'Nidorino', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_170_EN_SM.webp'),
  ('A1-171', 'A1', 171, 'Nidoking', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_171_EN_SM.webp'),
  ('A1-172', 'A1', 172, 'Zubat', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_172_EN_SM.webp'),
  ('A1-173', 'A1', 173, 'Golbat', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_173_EN_SM.webp'),
  ('A1-174', 'A1', 174, 'Grimer', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_174_EN_SM.webp'),
  ('A1-175', 'A1', 175, 'Muk', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_175_EN_SM.webp'),
  ('A1-176', 'A1', 176, 'Koffing', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_176_EN_SM.webp'),
  ('A1-177', 'A1', 177, 'Weezing', 'pokemon', 'darkness', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_177_EN_SM.webp'),
  ('A1-178', 'A1', 178, 'Mawile', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_178_EN_SM.webp'),
  ('A1-179', 'A1', 179, 'Pawniard', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_179_EN_SM.webp'),
  ('A1-180', 'A1', 180, 'Bisharp', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_180_EN_SM.webp'),
  ('A1-181', 'A1', 181, 'Meltan', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_181_EN_SM.webp'),
  ('A1-182', 'A1', 182, 'Melmetal', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_182_EN_SM.webp'),
  ('A1-183', 'A1', 183, 'Dratini', 'pokemon', 'dragon', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_183_EN_SM.webp'),
  ('A1-184', 'A1', 184, 'Dragonair', 'pokemon', 'dragon', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_184_EN_SM.webp'),
  ('A1-185', 'A1', 185, 'Dragonite', 'pokemon', 'dragon', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_185_EN_SM.webp'),
  ('A1-186', 'A1', 186, 'Pidgey', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_186_EN_SM.webp'),
  ('A1-187', 'A1', 187, 'Pidgeotto', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_187_EN_SM.webp'),
  ('A1-188', 'A1', 188, 'Pidgeot', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_188_EN_SM.webp'),
  ('A1-189', 'A1', 189, 'Rattata', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_189_EN_SM.webp'),
  ('A1-190', 'A1', 190, 'Raticate', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_190_EN_SM.webp'),
  ('A1-191', 'A1', 191, 'Spearow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_191_EN_SM.webp'),
  ('A1-192', 'A1', 192, 'Fearow', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_192_EN_SM.webp'),
  ('A1-193', 'A1', 193, 'Jigglypuff', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_193_EN_SM.webp'),
  ('A1-194', 'A1', 194, 'Wigglytuff', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_194_EN_SM.webp'),
  ('A1-195', 'A1', 195, 'Wigglytuff ex', 'pokemon', 'colorless', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_195_EN_SM.webp'),
  ('A1-196', 'A1', 196, 'Meowth', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_196_EN_SM.webp'),
  ('A1-197', 'A1', 197, 'Persian', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_197_EN_SM.webp'),
  ('A1-198', 'A1', 198, 'Farfetch''d', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_198_EN_SM.webp'),
  ('A1-199', 'A1', 199, 'Doduo', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_199_EN_SM.webp'),
  ('A1-200', 'A1', 200, 'Dodrio', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_200_EN_SM.webp'),
  ('A1-201', 'A1', 201, 'Lickitung', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_201_EN_SM.webp'),
  ('A1-202', 'A1', 202, 'Chansey', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_202_EN_SM.webp'),
  ('A1-203', 'A1', 203, 'Kangaskhan', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_203_EN_SM.webp'),
  ('A1-204', 'A1', 204, 'Tauros', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_204_EN_SM.webp'),
  ('A1-205', 'A1', 205, 'Ditto', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_205_EN_SM.webp'),
  ('A1-206', 'A1', 206, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_206_EN_SM.webp'),
  ('A1-207', 'A1', 207, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_207_EN_SM.webp'),
  ('A1-208', 'A1', 208, 'Eevee', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_208_EN_SM.webp'),
  ('A1-209', 'A1', 209, 'Porygon', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_209_EN_SM.webp'),
  ('A1-210', 'A1', 210, 'Aerodactyl', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_210_EN_SM.webp'),
  ('A1-211', 'A1', 211, 'Snorlax', 'pokemon', 'colorless', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_211_EN_SM.webp'),
  ('A1-212', 'A1', 212, 'Minccino', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_212_EN_SM.webp'),
  ('A1-213', 'A1', 213, 'Cinccino', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_213_EN_SM.webp'),
  ('A1-214', 'A1', 214, 'Wooloo', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_214_EN_SM.webp'),
  ('A1-215', 'A1', 215, 'Dubwool', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_215_EN_SM.webp'),
  ('A1-216', 'A1', 216, 'Helix Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_216_EN_SM.webp'),
  ('A1-217', 'A1', 217, 'Dome Fossil', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_217_EN_SM.webp'),
  ('A1-218', 'A1', 218, 'Old Amber', 'trainer', null, 'item', 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_218_EN_SM.webp'),
  ('A1-219', 'A1', 219, 'Erika', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_219_EN_SM.webp'),
  ('A1-220', 'A1', 220, 'Misty', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_220_EN_SM.webp'),
  ('A1-221', 'A1', 221, 'Blaine', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_221_EN_SM.webp'),
  ('A1-222', 'A1', 222, 'Koga', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_222_EN_SM.webp'),
  ('A1-223', 'A1', 223, 'Giovanni', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_223_EN_SM.webp'),
  ('A1-224', 'A1', 224, 'Brock', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_224_EN_SM.webp'),
  ('A1-225', 'A1', 225, 'Sabrina', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_225_EN_SM.webp'),
  ('A1-226', 'A1', 226, 'Lt. Surge', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_226_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('A1-227', 'A1', 227, 'Bulbasaur', 'pokemon', 'grass', null, 'star_1', 'A1-001', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_227_EN_SM.webp'),
  ('A1-228', 'A1', 228, 'Gloom', 'pokemon', 'grass', null, 'star_1', 'A1-012', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_228_EN_SM.webp'),
  ('A1-229', 'A1', 229, 'Pinsir', 'pokemon', 'grass', null, 'star_1', 'A1-026', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_229_EN_SM.webp'),
  ('A1-230', 'A1', 230, 'Charmander', 'pokemon', 'fire', null, 'star_1', 'A1-033', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_230_EN_SM.webp'),
  ('A1-231', 'A1', 231, 'Rapidash', 'pokemon', 'fire', null, 'star_1', 'A1-043', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_231_EN_SM.webp'),
  ('A1-232', 'A1', 232, 'Squirtle', 'pokemon', 'water', null, 'star_1', 'A1-053', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_232_EN_SM.webp'),
  ('A1-233', 'A1', 233, 'Gyarados', 'pokemon', 'water', null, 'star_1', 'A1-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_233_EN_SM.webp'),
  ('A1-234', 'A1', 234, 'Lapras', 'pokemon', 'water', null, 'star_1', 'A1-079', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_234_EN_SM.webp'),
  ('A1-235', 'A1', 235, 'Electrode', 'pokemon', 'lightning', null, 'star_1', 'A1-100', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_235_EN_SM.webp'),
  ('A1-236', 'A1', 236, 'Alakazam', 'pokemon', 'psychic', null, 'star_1', 'A1-117', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_236_EN_SM.webp'),
  ('A1-237', 'A1', 237, 'Slowpoke', 'pokemon', 'psychic', null, 'star_1', 'A1-118', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_237_EN_SM.webp'),
  ('A1-238', 'A1', 238, 'Diglett', 'pokemon', 'fighting', null, 'star_1', 'A1-139', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_238_EN_SM.webp'),
  ('A1-239', 'A1', 239, 'Cubone', 'pokemon', 'fighting', null, 'star_1', 'A1-151', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_239_EN_SM.webp'),
  ('A1-240', 'A1', 240, 'Nidoqueen', 'pokemon', 'darkness', null, 'star_1', 'A1-168', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_240_EN_SM.webp'),
  ('A1-241', 'A1', 241, 'Nidoking', 'pokemon', 'darkness', null, 'star_1', 'A1-171', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_241_EN_SM.webp'),
  ('A1-242', 'A1', 242, 'Golbat', 'pokemon', 'darkness', null, 'star_1', 'A1-173', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_242_EN_SM.webp'),
  ('A1-243', 'A1', 243, 'Weezing', 'pokemon', 'darkness', null, 'star_1', 'A1-177', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_243_EN_SM.webp'),
  ('A1-244', 'A1', 244, 'Dragonite', 'pokemon', 'dragon', null, 'star_1', 'A1-185', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_244_EN_SM.webp'),
  ('A1-245', 'A1', 245, 'Pidgeot', 'pokemon', 'colorless', null, 'star_1', 'A1-188', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_245_EN_SM.webp'),
  ('A1-246', 'A1', 246, 'Meowth', 'pokemon', 'colorless', null, 'star_1', 'A1-196', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_246_EN_SM.webp'),
  ('A1-247', 'A1', 247, 'Ditto', 'pokemon', 'colorless', null, 'star_1', 'A1-205', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_247_EN_SM.webp'),
  ('A1-248', 'A1', 248, 'Eevee', 'pokemon', 'colorless', null, 'star_1', 'A1-206', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_248_EN_SM.webp'),
  ('A1-249', 'A1', 249, 'Porygon', 'pokemon', 'colorless', null, 'star_1', 'A1-209', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_249_EN_SM.webp'),
  ('A1-250', 'A1', 250, 'Snorlax', 'pokemon', 'colorless', null, 'star_1', 'A1-211', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_250_EN_SM.webp'),
  ('A1-251', 'A1', 251, 'Venusaur ex', 'pokemon', 'grass', null, 'star_2', 'A1-004', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_251_EN_SM.webp'),
  ('A1-252', 'A1', 252, 'Exeggutor ex', 'pokemon', 'grass', null, 'star_2', 'A1-023', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_252_EN_SM.webp'),
  ('A1-253', 'A1', 253, 'Charizard ex', 'pokemon', 'fire', null, 'star_2', 'A1-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_253_EN_SM.webp'),
  ('A1-254', 'A1', 254, 'Arcanine ex', 'pokemon', 'fire', null, 'star_2', 'A1-041', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_254_EN_SM.webp'),
  ('A1-255', 'A1', 255, 'Moltres ex', 'pokemon', 'fire', null, 'star_2', 'A1-047', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_255_EN_SM.webp'),
  ('A1-256', 'A1', 256, 'Blastoise ex', 'pokemon', 'water', null, 'star_2', 'A1-056', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_256_EN_SM.webp'),
  ('A1-257', 'A1', 257, 'Starmie ex', 'pokemon', 'water', null, 'star_2', 'A1-076', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_257_EN_SM.webp'),
  ('A1-258', 'A1', 258, 'Articuno ex', 'pokemon', 'water', null, 'star_2', 'A1-084', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_258_EN_SM.webp'),
  ('A1-259', 'A1', 259, 'Pikachu ex', 'pokemon', 'lightning', null, 'star_2', 'A1-096', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_259_EN_SM.webp'),
  ('A1-260', 'A1', 260, 'Zapdos ex', 'pokemon', 'lightning', null, 'star_2', 'A1-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_260_EN_SM.webp'),
  ('A1-261', 'A1', 261, 'Gengar ex', 'pokemon', 'psychic', null, 'star_2', 'A1-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_261_EN_SM.webp'),
  ('A1-262', 'A1', 262, 'Mewtwo ex', 'pokemon', 'psychic', null, 'star_2', 'A1-129', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_262_EN_SM.webp'),
  ('A1-263', 'A1', 263, 'Machamp ex', 'pokemon', 'fighting', null, 'star_2', 'A1-146', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_263_EN_SM.webp'),
  ('A1-264', 'A1', 264, 'Marowak ex', 'pokemon', 'fighting', null, 'star_2', 'A1-153', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_264_EN_SM.webp'),
  ('A1-265', 'A1', 265, 'Wigglytuff ex', 'pokemon', 'colorless', null, 'star_2', 'A1-195', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_265_EN_SM.webp'),
  ('A1-266', 'A1', 266, 'Erika', 'trainer', null, 'supporter', 'star_2', 'A1-219', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_266_EN_SM.webp'),
  ('A1-267', 'A1', 267, 'Misty', 'trainer', null, 'supporter', 'star_2', 'A1-220', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_267_EN_SM.webp'),
  ('A1-268', 'A1', 268, 'Blaine', 'trainer', null, 'supporter', 'star_2', 'A1-221', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_268_EN_SM.webp'),
  ('A1-269', 'A1', 269, 'Koga', 'trainer', null, 'supporter', 'star_2', 'A1-222', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_269_EN_SM.webp'),
  ('A1-270', 'A1', 270, 'Giovanni', 'trainer', null, 'supporter', 'star_2', 'A1-223', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_270_EN_SM.webp'),
  ('A1-271', 'A1', 271, 'Brock', 'trainer', null, 'supporter', 'star_2', 'A1-224', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_271_EN_SM.webp'),
  ('A1-272', 'A1', 272, 'Sabrina', 'trainer', null, 'supporter', 'star_2', 'A1-225', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_272_EN_SM.webp'),
  ('A1-273', 'A1', 273, 'Lt. Surge', 'trainer', null, 'supporter', 'star_2', 'A1-226', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_273_EN_SM.webp'),
  ('A1-274', 'A1', 274, 'Moltres ex', 'pokemon', 'fire', null, 'star_2', 'A1-047', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_274_EN_SM.webp'),
  ('A1-275', 'A1', 275, 'Articuno ex', 'pokemon', 'water', null, 'star_2', 'A1-084', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_275_EN_SM.webp'),
  ('A1-276', 'A1', 276, 'Zapdos ex', 'pokemon', 'lightning', null, 'star_2', 'A1-104', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_276_EN_SM.webp'),
  ('A1-277', 'A1', 277, 'Gengar ex', 'pokemon', 'psychic', null, 'star_2', 'A1-123', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_277_EN_SM.webp'),
  ('A1-278', 'A1', 278, 'Machamp ex', 'pokemon', 'fighting', null, 'star_2', 'A1-146', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_278_EN_SM.webp'),
  ('A1-279', 'A1', 279, 'Wigglytuff ex', 'pokemon', 'colorless', null, 'star_2', 'A1-195', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_279_EN_SM.webp'),
  ('A1-280', 'A1', 280, 'Charizard ex', 'pokemon', 'fire', null, 'star_3', 'A1-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_280_EN_SM.webp'),
  ('A1-281', 'A1', 281, 'Pikachu ex', 'pokemon', 'lightning', null, 'star_3', 'A1-096', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_281_EN_SM.webp'),
  ('A1-282', 'A1', 282, 'Mewtwo ex', 'pokemon', 'psychic', null, 'star_3', 'A1-129', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_282_EN_SM.webp'),
  ('A1-283', 'A1', 283, 'Mew', 'pokemon', 'psychic', null, 'star_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_283_EN_SM.webp'),
  ('A1-284', 'A1', 284, 'Charizard ex', 'pokemon', 'fire', null, 'crown', 'A1-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_284_EN_SM.webp'),
  ('A1-285', 'A1', 285, 'Pikachu ex', 'pokemon', 'lightning', null, 'crown', 'A1-096', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_285_EN_SM.webp'),
  ('A1-286', 'A1', 286, 'Mewtwo ex', 'pokemon', 'psychic', null, 'crown', 'A1-129', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_286_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 286 cards, numbered 1 through 286.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'A1';
