-- Paldean Wonders (B2a): 93 main-set cards and 38 secret cards.
-- Source checked 2026-06-25: https://pocket.limitlesstcg.com/cards/B2a?display=list&show=all
--
-- Rarity convention:
-- diamond_1 .. diamond_4, star_1 .. star_3, crown
--
-- Image URLs below are third-party CDN URLs. Mirror appropriately licensed
-- assets into storage you control before relying on them in production.

begin;

insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B2a-001', 'B2a', 1, 'Sprigatito', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_001_EN_SM.webp'),
  ('B2a-002', 'B2a', 2, 'Floragato', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_002_EN_SM.webp'),
  ('B2a-003', 'B2a', 3, 'Meowscarada ex', 'pokemon', 'grass', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_003_EN_SM.webp'),
  ('B2a-004', 'B2a', 4, 'Tarountula', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_004_EN_SM.webp'),
  ('B2a-005', 'B2a', 5, 'Spidops', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_005_EN_SM.webp'),
  ('B2a-006', 'B2a', 6, 'Nymble', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_006_EN_SM.webp'),
  ('B2a-007', 'B2a', 7, 'Smoliv', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_007_EN_SM.webp'),
  ('B2a-008', 'B2a', 8, 'Dolliv', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_008_EN_SM.webp'),
  ('B2a-009', 'B2a', 9, 'Arboliva', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_009_EN_SM.webp'),
  ('B2a-010', 'B2a', 10, 'Bramblin', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_010_EN_SM.webp'),
  ('B2a-011', 'B2a', 11, 'Brambleghast', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_011_EN_SM.webp'),
  ('B2a-012', 'B2a', 12, 'Capsakid', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_012_EN_SM.webp'),
  ('B2a-013', 'B2a', 13, 'Scovillain', 'pokemon', 'grass', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_013_EN_SM.webp'),
  ('B2a-014', 'B2a', 14, 'Rellor', 'pokemon', 'grass', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_014_EN_SM.webp'),
  ('B2a-015', 'B2a', 15, 'Wo-Chien', 'pokemon', 'grass', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_015_EN_SM.webp'),
  ('B2a-016', 'B2a', 16, 'Fuecoco', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_016_EN_SM.webp'),
  ('B2a-017', 'B2a', 17, 'Crocalor', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_017_EN_SM.webp'),
  ('B2a-018', 'B2a', 18, 'Skeledirge', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_018_EN_SM.webp'),
  ('B2a-019', 'B2a', 19, 'Charcadet', 'pokemon', 'fire', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_019_EN_SM.webp'),
  ('B2a-020', 'B2a', 20, 'Armarouge ex', 'pokemon', 'fire', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_020_EN_SM.webp'),
  ('B2a-021', 'B2a', 21, 'Chi-Yu', 'pokemon', 'fire', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_021_EN_SM.webp'),
  ('B2a-022', 'B2a', 22, 'Quaxly', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_022_EN_SM.webp'),
  ('B2a-023', 'B2a', 23, 'Quaxwell', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_023_EN_SM.webp'),
  ('B2a-024', 'B2a', 24, 'Quaquaval', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_024_EN_SM.webp'),
  ('B2a-025', 'B2a', 25, 'Wiglett', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_025_EN_SM.webp'),
  ('B2a-026', 'B2a', 26, 'Wugtrio', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_026_EN_SM.webp'),
  ('B2a-027', 'B2a', 27, 'Finizen', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_027_EN_SM.webp'),
  ('B2a-028', 'B2a', 28, 'Palafin', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_028_EN_SM.webp'),
  ('B2a-029', 'B2a', 29, 'Cetoddle', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_029_EN_SM.webp'),
  ('B2a-030', 'B2a', 30, 'Cetitan', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_030_EN_SM.webp'),
  ('B2a-031', 'B2a', 31, 'Veluza', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_031_EN_SM.webp'),
  ('B2a-032', 'B2a', 32, 'Dondozo', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_032_EN_SM.webp'),
  ('B2a-033', 'B2a', 33, 'Tatsugiri', 'pokemon', 'water', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_033_EN_SM.webp'),
  ('B2a-034', 'B2a', 34, 'Frigibax', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_034_EN_SM.webp'),
  ('B2a-035', 'B2a', 35, 'Arctibax', 'pokemon', 'water', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_035_EN_SM.webp'),
  ('B2a-036', 'B2a', 36, 'Baxcalibur', 'pokemon', 'water', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_036_EN_SM.webp'),
  ('B2a-037', 'B2a', 37, 'Chien-Pao ex', 'pokemon', 'water', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_037_EN_SM.webp'),
  ('B2a-038', 'B2a', 38, 'Pawmi', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_038_EN_SM.webp'),
  ('B2a-039', 'B2a', 39, 'Pawmo', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_039_EN_SM.webp'),
  ('B2a-040', 'B2a', 40, 'Pawmot', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_040_EN_SM.webp'),
  ('B2a-041', 'B2a', 41, 'Tadbulb', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_041_EN_SM.webp'),
  ('B2a-042', 'B2a', 42, 'Bellibolt ex', 'pokemon', 'lightning', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_042_EN_SM.webp'),
  ('B2a-043', 'B2a', 43, 'Wattrel', 'pokemon', 'lightning', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_043_EN_SM.webp'),
  ('B2a-044', 'B2a', 44, 'Kilowattrel', 'pokemon', 'lightning', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_044_EN_SM.webp'),
  ('B2a-045', 'B2a', 45, 'Miraidon', 'pokemon', 'lightning', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_045_EN_SM.webp'),
  ('B2a-046', 'B2a', 46, 'Fidough', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_046_EN_SM.webp'),
  ('B2a-047', 'B2a', 47, 'Dachsbun', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_047_EN_SM.webp'),
  ('B2a-048', 'B2a', 48, 'Ceruledge', 'pokemon', 'psychic', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_048_EN_SM.webp'),
  ('B2a-049', 'B2a', 49, 'Rabsca', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_049_EN_SM.webp'),
  ('B2a-050', 'B2a', 50, 'Flittle', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_050_EN_SM.webp'),
  ('B2a-051', 'B2a', 51, 'Espathra', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_051_EN_SM.webp'),
  ('B2a-052', 'B2a', 52, 'Greavard', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_052_EN_SM.webp'),
  ('B2a-053', 'B2a', 53, 'Houndstone', 'pokemon', 'psychic', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_053_EN_SM.webp'),
  ('B2a-054', 'B2a', 54, 'Gimmighoul', 'pokemon', 'psychic', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_054_EN_SM.webp'),
  ('B2a-055', 'B2a', 55, 'Mankey', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_055_EN_SM.webp'),
  ('B2a-056', 'B2a', 56, 'Primeape', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_056_EN_SM.webp'),
  ('B2a-057', 'B2a', 57, 'Annihilape', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_057_EN_SM.webp'),
  ('B2a-058', 'B2a', 58, 'Paldean Tauros', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_058_EN_SM.webp'),
  ('B2a-059', 'B2a', 59, 'Toedscool', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_059_EN_SM.webp'),
  ('B2a-060', 'B2a', 60, 'Toedscruel', 'pokemon', 'fighting', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_060_EN_SM.webp'),
  ('B2a-061', 'B2a', 61, 'Klawf', 'pokemon', 'fighting', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_061_EN_SM.webp'),
  ('B2a-062', 'B2a', 62, 'Ting-Lu', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_062_EN_SM.webp'),
  ('B2a-063', 'B2a', 63, 'Koraidon', 'pokemon', 'fighting', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_063_EN_SM.webp'),
  ('B2a-064', 'B2a', 64, 'Paldean Wooper', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_064_EN_SM.webp'),
  ('B2a-065', 'B2a', 65, 'Paldean Clodsire', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_065_EN_SM.webp'),
  ('B2a-066', 'B2a', 66, 'Lokix', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_066_EN_SM.webp'),
  ('B2a-067', 'B2a', 67, 'Maschiff', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_067_EN_SM.webp'),
  ('B2a-068', 'B2a', 68, 'Mabosstiff', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_068_EN_SM.webp'),
  ('B2a-069', 'B2a', 69, 'Shroodle', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_069_EN_SM.webp'),
  ('B2a-070', 'B2a', 70, 'Grafaiai', 'pokemon', 'darkness', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_070_EN_SM.webp'),
  ('B2a-071', 'B2a', 71, 'Bombirdier', 'pokemon', 'darkness', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_071_EN_SM.webp'),
  ('B2a-072', 'B2a', 72, 'Tinkatink', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_072_EN_SM.webp'),
  ('B2a-073', 'B2a', 73, 'Tinkatuff', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_073_EN_SM.webp'),
  ('B2a-074', 'B2a', 74, 'Tinkaton', 'pokemon', 'metal', null, 'diamond_3', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_074_EN_SM.webp'),
  ('B2a-075', 'B2a', 75, 'Varoom', 'pokemon', 'metal', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_075_EN_SM.webp'),
  ('B2a-076', 'B2a', 76, 'Revavroom', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_076_EN_SM.webp'),
  ('B2a-077', 'B2a', 77, 'Orthworm', 'pokemon', 'metal', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_077_EN_SM.webp'),
  ('B2a-078', 'B2a', 78, 'Gholdengo ex', 'pokemon', 'metal', null, 'diamond_4', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_078_EN_SM.webp'),
  ('B2a-079', 'B2a', 79, 'Lechonk', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_079_EN_SM.webp'),
  ('B2a-080', 'B2a', 80, 'Oinkologne', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_080_EN_SM.webp'),
  ('B2a-081', 'B2a', 81, 'Tandemaus', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_081_EN_SM.webp'),
  ('B2a-082', 'B2a', 82, 'Maushold', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_082_EN_SM.webp'),
  ('B2a-083', 'B2a', 83, 'Squawkabilly', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_083_EN_SM.webp'),
  ('B2a-084', 'B2a', 84, 'Cyclizar', 'pokemon', 'colorless', null, 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_084_EN_SM.webp'),
  ('B2a-085', 'B2a', 85, 'Flamigo', 'pokemon', 'colorless', null, 'diamond_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_085_EN_SM.webp'),
  ('B2a-086', 'B2a', 86, 'Electric Generator', 'trainer', null, 'item', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_086_EN_SM.webp'),
  ('B2a-087', 'B2a', 87, 'Big Air Balloon', 'trainer', null, 'pokemon_tool', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_087_EN_SM.webp'),
  ('B2a-088', 'B2a', 88, 'Team Star Grunt', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_088_EN_SM.webp'),
  ('B2a-089', 'B2a', 89, 'Iono', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_089_EN_SM.webp'),
  ('B2a-090', 'B2a', 90, 'Nemona', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_090_EN_SM.webp'),
  ('B2a-091', 'B2a', 91, 'Arven', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_091_EN_SM.webp'),
  ('B2a-092', 'B2a', 92, 'Penny', 'trainer', null, 'supporter', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_092_EN_SM.webp'),
  ('B2a-093', 'B2a', 93, 'Mesagoza', 'trainer', null, 'stadium', 'diamond_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_093_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

-- Insert secret-art variants after their referenced base cards.
insert into public.cards (
  id, set_id, collector_number, name, category,
  energy_type, trainer_type, rarity, variant_of_card_id, image_url
) values
  ('B2a-094', 'B2a', 94, 'Fuecoco', 'pokemon', 'fire', null, 'star_1', 'B2a-016', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_094_EN_SM.webp'),
  ('B2a-095', 'B2a', 95, 'Greavard', 'pokemon', 'psychic', null, 'star_1', 'B2a-052', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_095_EN_SM.webp'),
  ('B2a-096', 'B2a', 96, 'Gimmighoul', 'pokemon', 'psychic', null, 'star_1', 'B2a-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_096_EN_SM.webp'),
  ('B2a-097', 'B2a', 97, 'Paldean Wooper', 'pokemon', 'darkness', null, 'star_1', 'B2a-064', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_097_EN_SM.webp'),
  ('B2a-098', 'B2a', 98, 'Orthworm', 'pokemon', 'metal', null, 'star_1', 'B2a-077', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_098_EN_SM.webp'),
  ('B2a-099', 'B2a', 99, 'Maushold', 'pokemon', 'colorless', null, 'star_1', 'B2a-082', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_099_EN_SM.webp'),
  ('B2a-100', 'B2a', 100, 'Meowscarada ex', 'pokemon', 'grass', null, 'star_2', 'B2a-003', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_100_EN_SM.webp'),
  ('B2a-101', 'B2a', 101, 'Armarouge ex', 'pokemon', 'fire', null, 'star_2', 'B2a-020', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_101_EN_SM.webp'),
  ('B2a-102', 'B2a', 102, 'Chien-Pao ex', 'pokemon', 'water', null, 'star_2', 'B2a-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_102_EN_SM.webp'),
  ('B2a-103', 'B2a', 103, 'Bellibolt ex', 'pokemon', 'lightning', null, 'star_2', 'B2a-042', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_103_EN_SM.webp'),
  ('B2a-104', 'B2a', 104, 'Gholdengo ex', 'pokemon', 'metal', null, 'star_2', 'B2a-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_104_EN_SM.webp'),
  ('B2a-105', 'B2a', 105, 'Team Star Grunt', 'trainer', null, 'supporter', 'star_2', 'B2a-088', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_105_EN_SM.webp'),
  ('B2a-106', 'B2a', 106, 'Iono', 'trainer', null, 'supporter', 'star_2', 'B2a-089', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_106_EN_SM.webp'),
  ('B2a-107', 'B2a', 107, 'Nemona', 'trainer', null, 'supporter', 'star_2', 'B2a-090', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_107_EN_SM.webp'),
  ('B2a-108', 'B2a', 108, 'Arven', 'trainer', null, 'supporter', 'star_2', 'B2a-091', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_108_EN_SM.webp'),
  ('B2a-109', 'B2a', 109, 'Penny', 'trainer', null, 'supporter', 'star_2', 'B2a-092', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_109_EN_SM.webp'),
  ('B2a-110', 'B2a', 110, 'Meowscarada ex', 'pokemon', 'grass', null, 'star_2', 'B2a-003', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_110_EN_SM.webp'),
  ('B2a-111', 'B2a', 111, 'Armarouge ex', 'pokemon', 'fire', null, 'star_2', 'B2a-020', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_111_EN_SM.webp'),
  ('B2a-112', 'B2a', 112, 'Chien-Pao ex', 'pokemon', 'water', null, 'star_2', 'B2a-037', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_112_EN_SM.webp'),
  ('B2a-113', 'B2a', 113, 'Bellibolt ex', 'pokemon', 'lightning', null, 'star_2', 'B2a-042', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_113_EN_SM.webp'),
  ('B2a-114', 'B2a', 114, 'Gholdengo ex', 'pokemon', 'metal', null, 'star_2', 'B2a-078', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_114_EN_SM.webp'),
  ('B2a-115', 'B2a', 115, 'Arven', 'trainer', null, 'supporter', 'star_3', 'B2a-091', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_115_EN_SM.webp'),
  ('B2a-116', 'B2a', 116, 'Sprigatito', 'pokemon', 'grass', null, 'star_1', 'B2a-001', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_116_EN_SM.webp'),
  ('B2a-117', 'B2a', 117, 'Floragato', 'pokemon', 'grass', null, 'star_1', 'B2a-002', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_117_EN_SM.webp'),
  ('B2a-118', 'B2a', 118, 'Meowscarada', 'pokemon', 'grass', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_118_EN_SM.webp'),
  ('B2a-119', 'B2a', 119, 'Pawmi', 'pokemon', 'lightning', null, 'star_1', 'B2a-038', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_119_EN_SM.webp'),
  ('B2a-120', 'B2a', 120, 'Pawmo', 'pokemon', 'lightning', null, 'star_1', 'B2a-039', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_120_EN_SM.webp'),
  ('B2a-121', 'B2a', 121, 'Pawmot', 'pokemon', 'lightning', null, 'star_1', 'B2a-040', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_121_EN_SM.webp'),
  ('B2a-122', 'B2a', 122, 'Gimmighoul', 'pokemon', 'psychic', null, 'star_1', 'B2a-054', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_122_EN_SM.webp'),
  ('B2a-123', 'B2a', 123, 'Tinkatink', 'pokemon', 'metal', null, 'star_1', 'B2a-072', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_123_EN_SM.webp'),
  ('B2a-124', 'B2a', 124, 'Tinkatuff', 'pokemon', 'metal', null, 'star_1', 'B2a-073', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_124_EN_SM.webp'),
  ('B2a-125', 'B2a', 125, 'Gholdengo', 'pokemon', 'metal', null, 'star_1', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_125_EN_SM.webp'),
  ('B2a-126', 'B2a', 126, 'Entei ex', 'pokemon', 'fire', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_126_EN_SM.webp'),
  ('B2a-127', 'B2a', 127, 'Suicune ex', 'pokemon', 'water', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_127_EN_SM.webp'),
  ('B2a-128', 'B2a', 128, 'Raikou ex', 'pokemon', 'lightning', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_128_EN_SM.webp'),
  ('B2a-129', 'B2a', 129, 'Tinkaton ex', 'pokemon', 'metal', null, 'star_2', null, 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_129_EN_SM.webp'),
  ('B2a-130', 'B2a', 130, 'Baxcalibur', 'pokemon', 'water', null, 'crown', 'B2a-036', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_130_EN_SM.webp'),
  ('B2a-131', 'B2a', 131, 'Electric Generator', 'trainer', null, 'item', 'crown', 'B2a-086', 'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_131_EN_SM.webp')
on conflict (id) do update set
  set_id = excluded.set_id,
  collector_number = excluded.collector_number,
  name = excluded.name,
  category = excluded.category,
  energy_type = excluded.energy_type,
  trainer_type = excluded.trainer_type,
  rarity = excluded.rarity,
  variant_of_card_id = excluded.variant_of_card_id,
  image_url = excluded.image_url,
  updated_at = now();

commit;

-- Expected result: 131 cards, numbered 1 through 131.
select
  count(*) as card_count,
  min(collector_number) as first_number,
  max(collector_number) as last_number
from public.cards
where set_id = 'B2a';
